rootProject.name = 'sumup-java'

include(':sumup')
project(':sumup').projectDir = file('src')
project(':sumup').name = 'sumup-sdk'

include(':examples:basic')
project(':examples:basic').projectDir = file('examples/basic')

include(':examples:card-reader-checkout')
project(':examples:card-reader-checkout').projectDir = file('examples/card-reader-checkout')
