// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk;

import com.sumup.sdk.clients.CheckoutsClient;
import com.sumup.sdk.clients.CustomersClient;
import com.sumup.sdk.clients.MembersClient;
import com.sumup.sdk.clients.MembershipsClient;
import com.sumup.sdk.clients.MerchantsClient;
import com.sumup.sdk.clients.PayoutsClient;
import com.sumup.sdk.clients.ReadersClient;
import com.sumup.sdk.clients.ReceiptsClient;
import com.sumup.sdk.clients.RolesClient;
import com.sumup.sdk.clients.SubaccountsClient;
import com.sumup.sdk.clients.TransactionsClient;
import com.sumup.sdk.core.ApiClient;
import java.net.http.HttpClient;
import java.time.Duration;
import java.util.Objects;

/**
 * Entry point for the SumUp Java SDK. Use {@link Builder} to configure HTTP behavior and access
 * grouped API clients via the provided accessor methods.
 */
public final class SumUpClient {
  private final ApiClient apiClient;
  private final CheckoutsClient checkouts;
  private final CustomersClient customers;
  private final MembersClient members;
  private final MembershipsClient memberships;
  private final MerchantsClient merchants;
  private final PayoutsClient payouts;
  private final ReadersClient readers;
  private final ReceiptsClient receipts;
  private final RolesClient roles;
  private final SubaccountsClient subaccounts;
  private final TransactionsClient transactions;

  /** Creates a SumUpClient using the API key from the SUMUP_API_KEY environment variable. */
  public SumUpClient() {
    this(readApiKeyFromEnv());
  }

  /**
   * Creates a SumUpClient using the provided API key.
   *
   * @param apiKey API key used to authorize requests.
   */
  public SumUpClient(String apiKey) {
    this(ApiClient.builder().accessToken(Objects.requireNonNull(apiKey, "apiKey")).build());
  }

  private static String readApiKeyFromEnv() {
    String apiKey = System.getenv("SUMUP_API_KEY");
    if (apiKey == null || apiKey.isBlank()) {
      throw new IllegalStateException("SUMUP_API_KEY environment variable is not set");
    }
    return apiKey;
  }

  /**
   * Creates a SumUpClient using the provided ApiClient.
   *
   * @param apiClient Configured core ApiClient instance.
   */
  private SumUpClient(ApiClient apiClient) {
    this.apiClient = Objects.requireNonNull(apiClient, "apiClient");
    this.checkouts = new CheckoutsClient(this.apiClient);
    this.customers = new CustomersClient(this.apiClient);
    this.members = new MembersClient(this.apiClient);
    this.memberships = new MembershipsClient(this.apiClient);
    this.merchants = new MerchantsClient(this.apiClient);
    this.payouts = new PayoutsClient(this.apiClient);
    this.readers = new ReadersClient(this.apiClient);
    this.receipts = new ReceiptsClient(this.apiClient);
    this.roles = new RolesClient(this.apiClient);
    this.subaccounts = new SubaccountsClient(this.apiClient);
    this.transactions = new TransactionsClient(this.apiClient);
  }

  /**
   * Creates a new builder for SumUpClient.
   *
   * @return Builder used to configure and create SumUpClient instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /**
   * Returns the underlying ApiClient used to send HTTP requests.
   *
   * @return Configured ApiClient.
   */
  public ApiClient apiClient() {
    return apiClient;
  }

  /**
   * Returns the CheckoutsClient client for the "Checkouts" API group.
   *
   * @return Client for the associated API group.
   */
  public CheckoutsClient checkouts() {
    return checkouts;
  }

  /**
   * Returns the CustomersClient client for the "Customers" API group.
   *
   * @return Client for the associated API group.
   */
  public CustomersClient customers() {
    return customers;
  }

  /**
   * Returns the MembersClient client for the "Members" API group.
   *
   * @return Client for the associated API group.
   */
  public MembersClient members() {
    return members;
  }

  /**
   * Returns the MembershipsClient client for the "Memberships" API group.
   *
   * @return Client for the associated API group.
   */
  public MembershipsClient memberships() {
    return memberships;
  }

  /**
   * Returns the MerchantsClient client for the "Merchants" API group.
   *
   * @return Client for the associated API group.
   */
  public MerchantsClient merchants() {
    return merchants;
  }

  /**
   * Returns the PayoutsClient client for the "Payouts" API group.
   *
   * @return Client for the associated API group.
   */
  public PayoutsClient payouts() {
    return payouts;
  }

  /**
   * Returns the ReadersClient client for the "Readers" API group.
   *
   * @return Client for the associated API group.
   */
  public ReadersClient readers() {
    return readers;
  }

  /**
   * Returns the ReceiptsClient client for the "Receipts" API group.
   *
   * @return Client for the associated API group.
   */
  public ReceiptsClient receipts() {
    return receipts;
  }

  /**
   * Returns the RolesClient client for the "Roles" API group.
   *
   * @return Client for the associated API group.
   */
  public RolesClient roles() {
    return roles;
  }

  /**
   * Returns the SubaccountsClient client for the "Subaccounts" API group.
   *
   * @return Client for the associated API group.
   */
  public SubaccountsClient subaccounts() {
    return subaccounts;
  }

  /**
   * Returns the TransactionsClient client for the "Transactions" API group.
   *
   * @return Client for the associated API group.
   */
  public TransactionsClient transactions() {
    return transactions;
  }

  /** Builder that configures and creates SumUpClient instances. */
  public static final class Builder {
    private ApiClient apiClient;
    private final ApiClient.Builder apiClientBuilder = ApiClient.builder();

    /**
     * Uses the provided ApiClient instead of building one from scratch.
     *
     * @param apiClient Preconfigured ApiClient instance.
     * @return This builder instance.
     */
    public Builder apiClient(ApiClient apiClient) {
      this.apiClient = Objects.requireNonNull(apiClient, "apiClient");
      return this;
    }

    /**
     * Overrides the base URI used by the underlying ApiClient.
     *
     * @param baseUri Base URI for all requests.
     * @return This builder instance.
     */
    public Builder baseUri(String baseUri) {
      this.apiClientBuilder.baseUri(baseUri);
      return this;
    }

    /**
     * Supplies a custom HttpClient implementation.
     *
     * @param httpClient HTTP client to use when executing requests.
     * @return This builder instance.
     */
    public Builder httpClient(HttpClient httpClient) {
      this.apiClientBuilder.httpClient(httpClient);
      return this;
    }

    /**
     * Sets the HTTP connection timeout.
     *
     * @param timeout Desired connection timeout.
     * @return This builder instance.
     */
    public Builder connectTimeout(Duration timeout) {
      this.apiClientBuilder.connectTimeout(timeout);
      return this;
    }

    /**
     * Sets the per-request timeout.
     *
     * @param timeout Desired request timeout.
     * @return This builder instance.
     */
    public Builder requestTimeout(Duration timeout) {
      this.apiClientBuilder.requestTimeout(timeout);
      return this;
    }

    /**
     * Configures the OAuth access token used for Authorization headers.
     *
     * @param accessToken OAuth access token.
     * @return This builder instance.
     */
    public Builder accessToken(String accessToken) {
      this.apiClientBuilder.accessToken(accessToken);
      return this;
    }

    /**
     * Builds a SumUpClient using the supplied configuration.
     *
     * @return Configured SumUpClient.
     */
    public SumUpClient build() {
      ApiClient resolved = this.apiClient != null ? this.apiClient : this.apiClientBuilder.build();
      return new SumUpClient(resolved);
    }
  }
}
