// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** Profile information. */
public record AccountLegacy(
    /** The role of the user. */
    com.sumup.sdk.models.AccountLegacyType type,

    /** Username of the user profile. */
    String username) {
  /**
   * Creates a builder for AccountLegacy.
   *
   * @return Builder that constructs immutable AccountLegacy instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for AccountLegacy instances. */
  public static final class Builder {
    private com.sumup.sdk.models.AccountLegacyType type;
    private String username;

    private Builder() {}

    /**
     * Sets the value for {@code type}.
     *
     * @param type The role of the user.
     * @return This builder instance.
     */
    public Builder type(com.sumup.sdk.models.AccountLegacyType type) {
      this.type = type;
      return this;
    }

    /**
     * Sets the value for {@code username}.
     *
     * @param username Username of the user profile.
     * @return This builder instance.
     */
    public Builder username(String username) {
      this.username = username;
      return this;
    }

    /**
     * Builds an immutable AccountLegacy instance.
     *
     * @return Immutable AccountLegacy.
     */
    public AccountLegacy build() {
      return new AccountLegacy(type, username);
    }
  }
}
