// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** The role of the user. */
public enum AccountLegacyType {
  NORMAL("normal"),
  OPERATOR("operator");

  private final String value;

  AccountLegacyType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static AccountLegacyType fromValue(String value) {
    if (value == null) {
      return null;
    }
    for (AccountLegacyType entry : values()) {
      if (entry.value.equals(value)) {
        return entry;
      }
    }
    throw new IllegalArgumentException("Unknown AccountLegacyType value: " + value);
  }
}
