// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** Details of the registered address. */
public record AddressWithDetails(
    /** Address line 1 */
    String addressLine1,

    /** Address line 2 */
    String addressLine2,

    /** City */
    String city,

    /** undefined */
    String company,

    /** Country ISO 3166-1 code */
    String country,

    /** Country Details */
    com.sumup.sdk.models.CountryDetails countryDetails,

    /** undefined */
    String firstName,

    /** Landline number */
    String landline,

    /** undefined */
    String lastName,

    /** Postal code */
    String postCode,

    /** Region code */
    String regionCode,

    /** Country region id */
    Double regionId,

    /** Region name */
    String regionName,

    /** undefined */
    String stateId,

    /** TimeOffset Details */
    com.sumup.sdk.models.TimeoffsetDetails timeoffsetDetails) {
  /**
   * Creates a builder for AddressWithDetails.
   *
   * @return Builder that constructs immutable AddressWithDetails instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for AddressWithDetails instances. */
  public static final class Builder {
    private String addressLine1;
    private String addressLine2;
    private String city;
    private String company;
    private String country;
    private com.sumup.sdk.models.CountryDetails countryDetails;
    private String firstName;
    private String landline;
    private String lastName;
    private String postCode;
    private String regionCode;
    private Double regionId;
    private String regionName;
    private String stateId;
    private com.sumup.sdk.models.TimeoffsetDetails timeoffsetDetails;

    private Builder() {}

    /**
     * Sets the value for {@code addressLine1}.
     *
     * @param addressLine1 Address line 1
     * @return This builder instance.
     */
    public Builder addressLine1(String addressLine1) {
      this.addressLine1 = addressLine1;
      return this;
    }

    /**
     * Sets the value for {@code addressLine2}.
     *
     * @param addressLine2 Address line 2
     * @return This builder instance.
     */
    public Builder addressLine2(String addressLine2) {
      this.addressLine2 = addressLine2;
      return this;
    }

    /**
     * Sets the value for {@code city}.
     *
     * @param city City
     * @return This builder instance.
     */
    public Builder city(String city) {
      this.city = city;
      return this;
    }

    /**
     * Sets the value for {@code company}.
     *
     * @param company undefined
     * @return This builder instance.
     */
    public Builder company(String company) {
      this.company = company;
      return this;
    }

    /**
     * Sets the value for {@code country}.
     *
     * @param country Country ISO 3166-1 code
     * @return This builder instance.
     */
    public Builder country(String country) {
      this.country = country;
      return this;
    }

    /**
     * Sets the value for {@code countryDetails}.
     *
     * @param countryDetails Country Details
     * @return This builder instance.
     */
    public Builder countryDetails(com.sumup.sdk.models.CountryDetails countryDetails) {
      this.countryDetails = countryDetails;
      return this;
    }

    /**
     * Sets the value for {@code firstName}.
     *
     * @param firstName undefined
     * @return This builder instance.
     */
    public Builder firstName(String firstName) {
      this.firstName = firstName;
      return this;
    }

    /**
     * Sets the value for {@code landline}.
     *
     * @param landline Landline number
     * @return This builder instance.
     */
    public Builder landline(String landline) {
      this.landline = landline;
      return this;
    }

    /**
     * Sets the value for {@code lastName}.
     *
     * @param lastName undefined
     * @return This builder instance.
     */
    public Builder lastName(String lastName) {
      this.lastName = lastName;
      return this;
    }

    /**
     * Sets the value for {@code postCode}.
     *
     * @param postCode Postal code
     * @return This builder instance.
     */
    public Builder postCode(String postCode) {
      this.postCode = postCode;
      return this;
    }

    /**
     * Sets the value for {@code regionCode}.
     *
     * @param regionCode Region code
     * @return This builder instance.
     */
    public Builder regionCode(String regionCode) {
      this.regionCode = regionCode;
      return this;
    }

    /**
     * Sets the value for {@code regionId}.
     *
     * @param regionId Country region id
     * @return This builder instance.
     */
    public Builder regionId(Double regionId) {
      this.regionId = regionId;
      return this;
    }

    /**
     * Sets the value for {@code regionName}.
     *
     * @param regionName Region name
     * @return This builder instance.
     */
    public Builder regionName(String regionName) {
      this.regionName = regionName;
      return this;
    }

    /**
     * Sets the value for {@code stateId}.
     *
     * @param stateId undefined
     * @return This builder instance.
     */
    public Builder stateId(String stateId) {
      this.stateId = stateId;
      return this;
    }

    /**
     * Sets the value for {@code timeoffsetDetails}.
     *
     * @param timeoffsetDetails TimeOffset Details
     * @return This builder instance.
     */
    public Builder timeoffsetDetails(com.sumup.sdk.models.TimeoffsetDetails timeoffsetDetails) {
      this.timeoffsetDetails = timeoffsetDetails;
      return this;
    }

    /**
     * Builds an immutable AddressWithDetails instance.
     *
     * @return Immutable AddressWithDetails.
     */
    public AddressWithDetails build() {
      return new AddressWithDetails(
          addressLine1,
          addressLine2,
          city,
          company,
          country,
          countryDetails,
          firstName,
          landline,
          lastName,
          postCode,
          regionCode,
          regionId,
          regionName,
          stateId,
          timeoffsetDetails);
    }
  }
}
