// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

/**
 * Affiliate metadata for the transaction. It is a field that allow for integrators to track the
 * source of the transaction.
 */
public record Affiliate2(
    /**
     * Application ID of the affiliate. It is a unique identifier for the application and should be
     * set by the integrator in the [Affiliate Keys](https://developer.sumup.com/affiliate-keys)
     * page.
     */
    String appId,

    /**
     * Foreign transaction ID of the affiliate. It is a unique identifier for the transaction. It
     * can be used later to fetch the transaction details via the [Transactions
     * API](https://developer.sumup.com/api/transactions/get).
     */
    String foreignTransactionId,

    /**
     * Key of the affiliate. It is a unique identifier for the key and should be generated by the
     * integrator in the [Affiliate Keys](https://developer.sumup.com/affiliate-keys) page.
     */
    String key,

    /**
     * Additional metadata for the transaction. It is key-value object that can be associated with
     * the transaction.
     */
    java.util.Map<String, Object> tags) {
  /**
   * Creates a builder for Affiliate2.
   *
   * @return Builder that constructs immutable Affiliate2 instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for Affiliate2 instances. */
  public static final class Builder {
    private String appId;
    private String foreignTransactionId;
    private String key;
    private java.util.Map<String, Object> tags;

    private Builder() {}

    /**
     * Sets the value for {@code appId}.
     *
     * @param appId Application ID of the affiliate. It is a unique identifier for the application
     *     and should be set by the integrator in the [Affiliate
     *     Keys](https://developer.sumup.com/affiliate-keys) page.
     * @return This builder instance.
     */
    public Builder appId(String appId) {
      this.appId = appId;
      return this;
    }

    /**
     * Sets the value for {@code foreignTransactionId}.
     *
     * @param foreignTransactionId Foreign transaction ID of the affiliate. It is a unique
     *     identifier for the transaction. It can be used later to fetch the transaction details via
     *     the [Transactions API](https://developer.sumup.com/api/transactions/get).
     * @return This builder instance.
     */
    public Builder foreignTransactionId(String foreignTransactionId) {
      this.foreignTransactionId = foreignTransactionId;
      return this;
    }

    /**
     * Sets the value for {@code key}.
     *
     * @param key Key of the affiliate. It is a unique identifier for the key and should be
     *     generated by the integrator in the [Affiliate
     *     Keys](https://developer.sumup.com/affiliate-keys) page.
     * @return This builder instance.
     */
    public Builder key(String key) {
      this.key = key;
      return this;
    }

    /**
     * Sets the value for {@code tags}.
     *
     * @param tags Additional metadata for the transaction. It is key-value object that can be
     *     associated with the transaction.
     * @return This builder instance.
     */
    public Builder tags(java.util.Map<String, Object> tags) {
      this.tags = tags;
      return this;
    }

    /**
     * Builds an immutable Affiliate2 instance.
     *
     * @return Immutable Affiliate2.
     */
    public Affiliate2 build() {
      return new Affiliate2(
          Objects.requireNonNull(appId, "appId"),
          Objects.requireNonNull(foreignTransactionId, "foreignTransactionId"),
          Objects.requireNonNull(key, "key"),
          tags);
    }
  }
}
