// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** Mobile app settings */
public record AppSettings(
    /** Advanced mode. */
    String advancedMode,

    /** Barcode scanner. */
    String barcodeScanner,

    /** Cash payment. */
    String cashPayment,

    /** Checkout preference */
    String checkoutPreference,

    /** Expected max transaction amount. */
    Double expectedMaxTransactionAmount,

    /** Include vat. */
    Boolean includeVat,

    /** Manual entry. */
    String manualEntry,

    /** Manual entry tutorial. */
    Boolean manualEntryTutorial,

    /** Mobile payment. */
    String mobilePayment,

    /** Mobile payment tutorial. */
    Boolean mobilePaymentTutorial,

    /** Reader payment. */
    String readerPayment,

    /** Referral. */
    String referral,

    /** Tax enabled. */
    Boolean taxEnabled,

    /** Terminal mode tutorial. */
    Boolean terminalModeTutorial,

    /** Tip rates. */
    java.util.List<Float> tipRates,

    /** Tipping. */
    String tipping) {
  /**
   * Creates a builder for AppSettings.
   *
   * @return Builder that constructs immutable AppSettings instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for AppSettings instances. */
  public static final class Builder {
    private String advancedMode;
    private String barcodeScanner;
    private String cashPayment;
    private String checkoutPreference;
    private Double expectedMaxTransactionAmount;
    private Boolean includeVat;
    private String manualEntry;
    private Boolean manualEntryTutorial;
    private String mobilePayment;
    private Boolean mobilePaymentTutorial;
    private String readerPayment;
    private String referral;
    private Boolean taxEnabled;
    private Boolean terminalModeTutorial;
    private java.util.List<Float> tipRates;
    private String tipping;

    private Builder() {}

    /**
     * Sets the value for {@code advancedMode}.
     *
     * @param advancedMode Advanced mode.
     * @return This builder instance.
     */
    public Builder advancedMode(String advancedMode) {
      this.advancedMode = advancedMode;
      return this;
    }

    /**
     * Sets the value for {@code barcodeScanner}.
     *
     * @param barcodeScanner Barcode scanner.
     * @return This builder instance.
     */
    public Builder barcodeScanner(String barcodeScanner) {
      this.barcodeScanner = barcodeScanner;
      return this;
    }

    /**
     * Sets the value for {@code cashPayment}.
     *
     * @param cashPayment Cash payment.
     * @return This builder instance.
     */
    public Builder cashPayment(String cashPayment) {
      this.cashPayment = cashPayment;
      return this;
    }

    /**
     * Sets the value for {@code checkoutPreference}.
     *
     * @param checkoutPreference Checkout preference
     * @return This builder instance.
     */
    public Builder checkoutPreference(String checkoutPreference) {
      this.checkoutPreference = checkoutPreference;
      return this;
    }

    /**
     * Sets the value for {@code expectedMaxTransactionAmount}.
     *
     * @param expectedMaxTransactionAmount Expected max transaction amount.
     * @return This builder instance.
     */
    public Builder expectedMaxTransactionAmount(Double expectedMaxTransactionAmount) {
      this.expectedMaxTransactionAmount = expectedMaxTransactionAmount;
      return this;
    }

    /**
     * Sets the value for {@code includeVat}.
     *
     * @param includeVat Include vat.
     * @return This builder instance.
     */
    public Builder includeVat(Boolean includeVat) {
      this.includeVat = includeVat;
      return this;
    }

    /**
     * Sets the value for {@code manualEntry}.
     *
     * @param manualEntry Manual entry.
     * @return This builder instance.
     */
    public Builder manualEntry(String manualEntry) {
      this.manualEntry = manualEntry;
      return this;
    }

    /**
     * Sets the value for {@code manualEntryTutorial}.
     *
     * @param manualEntryTutorial Manual entry tutorial.
     * @return This builder instance.
     */
    public Builder manualEntryTutorial(Boolean manualEntryTutorial) {
      this.manualEntryTutorial = manualEntryTutorial;
      return this;
    }

    /**
     * Sets the value for {@code mobilePayment}.
     *
     * @param mobilePayment Mobile payment.
     * @return This builder instance.
     */
    public Builder mobilePayment(String mobilePayment) {
      this.mobilePayment = mobilePayment;
      return this;
    }

    /**
     * Sets the value for {@code mobilePaymentTutorial}.
     *
     * @param mobilePaymentTutorial Mobile payment tutorial.
     * @return This builder instance.
     */
    public Builder mobilePaymentTutorial(Boolean mobilePaymentTutorial) {
      this.mobilePaymentTutorial = mobilePaymentTutorial;
      return this;
    }

    /**
     * Sets the value for {@code readerPayment}.
     *
     * @param readerPayment Reader payment.
     * @return This builder instance.
     */
    public Builder readerPayment(String readerPayment) {
      this.readerPayment = readerPayment;
      return this;
    }

    /**
     * Sets the value for {@code referral}.
     *
     * @param referral Referral.
     * @return This builder instance.
     */
    public Builder referral(String referral) {
      this.referral = referral;
      return this;
    }

    /**
     * Sets the value for {@code taxEnabled}.
     *
     * @param taxEnabled Tax enabled.
     * @return This builder instance.
     */
    public Builder taxEnabled(Boolean taxEnabled) {
      this.taxEnabled = taxEnabled;
      return this;
    }

    /**
     * Sets the value for {@code terminalModeTutorial}.
     *
     * @param terminalModeTutorial Terminal mode tutorial.
     * @return This builder instance.
     */
    public Builder terminalModeTutorial(Boolean terminalModeTutorial) {
      this.terminalModeTutorial = terminalModeTutorial;
      return this;
    }

    /**
     * Sets the value for {@code tipRates}.
     *
     * @param tipRates Tip rates.
     * @return This builder instance.
     */
    public Builder tipRates(java.util.List<Float> tipRates) {
      this.tipRates = tipRates;
      return this;
    }

    /**
     * Sets the value for {@code tipping}.
     *
     * @param tipping Tipping.
     * @return This builder instance.
     */
    public Builder tipping(String tipping) {
      this.tipping = tipping;
      return this;
    }

    /**
     * Builds an immutable AppSettings instance.
     *
     * @return Immutable AppSettings.
     */
    public AppSettings build() {
      return new AppSettings(
          advancedMode,
          barcodeScanner,
          cashPayment,
          checkoutPreference,
          expectedMaxTransactionAmount,
          includeVat,
          manualEntry,
          manualEntryTutorial,
          mobilePayment,
          mobilePaymentTutorial,
          readerPayment,
          referral,
          taxEnabled,
          terminalModeTutorial,
          tipRates,
          tipping);
    }
  }
}
