// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** Object attributes that are modifiable only by SumUp applications. */
public record Attributes(java.util.Map<String, Object> value) {}
