// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

/** Bank account details used when creating or updating a payout account. */
public record BankAccountPayload(
    /** Determines if this bank account is business or personal. */
    com.sumup.sdk.models.BankAccountPayloadAccountCategory accountCategory,

    /** Account holder name */
    String accountHolderName,

    /** Account number */
    String accountNumber,

    /** Type of the account. */
    com.sumup.sdk.models.BankAccountPayloadAccountType accountType,

    /** Bank code */
    String bankCode,

    /** Branch code */
    String branchCode,

    /** Check digit */
    String checkDigit,

    /** IBAN */
    String iban,

    /** Determines if this bank account will be primary. Default is false */
    Boolean primary,

    /** Determines the bank account status. */
    com.sumup.sdk.models.BankAccountPayloadStatus status,

    /** SWIFT code */
    String swift) {
  /**
   * Creates a builder for BankAccountPayload.
   *
   * @return Builder that constructs immutable BankAccountPayload instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for BankAccountPayload instances. */
  public static final class Builder {
    private com.sumup.sdk.models.BankAccountPayloadAccountCategory accountCategory;
    private String accountHolderName;
    private String accountNumber;
    private com.sumup.sdk.models.BankAccountPayloadAccountType accountType;
    private String bankCode;
    private String branchCode;
    private String checkDigit;
    private String iban;
    private Boolean primary;
    private com.sumup.sdk.models.BankAccountPayloadStatus status;
    private String swift;

    private Builder() {}

    /**
     * Sets the value for {@code accountCategory}.
     *
     * @param accountCategory Determines if this bank account is business or personal.
     * @return This builder instance.
     */
    public Builder accountCategory(
        com.sumup.sdk.models.BankAccountPayloadAccountCategory accountCategory) {
      this.accountCategory = accountCategory;
      return this;
    }

    /**
     * Sets the value for {@code accountHolderName}.
     *
     * @param accountHolderName Account holder name
     * @return This builder instance.
     */
    public Builder accountHolderName(String accountHolderName) {
      this.accountHolderName = accountHolderName;
      return this;
    }

    /**
     * Sets the value for {@code accountNumber}.
     *
     * @param accountNumber Account number
     * @return This builder instance.
     */
    public Builder accountNumber(String accountNumber) {
      this.accountNumber = accountNumber;
      return this;
    }

    /**
     * Sets the value for {@code accountType}.
     *
     * @param accountType Type of the account.
     * @return This builder instance.
     */
    public Builder accountType(com.sumup.sdk.models.BankAccountPayloadAccountType accountType) {
      this.accountType = accountType;
      return this;
    }

    /**
     * Sets the value for {@code bankCode}.
     *
     * @param bankCode Bank code
     * @return This builder instance.
     */
    public Builder bankCode(String bankCode) {
      this.bankCode = bankCode;
      return this;
    }

    /**
     * Sets the value for {@code branchCode}.
     *
     * @param branchCode Branch code
     * @return This builder instance.
     */
    public Builder branchCode(String branchCode) {
      this.branchCode = branchCode;
      return this;
    }

    /**
     * Sets the value for {@code checkDigit}.
     *
     * @param checkDigit Check digit
     * @return This builder instance.
     */
    public Builder checkDigit(String checkDigit) {
      this.checkDigit = checkDigit;
      return this;
    }

    /**
     * Sets the value for {@code iban}.
     *
     * @param iban IBAN
     * @return This builder instance.
     */
    public Builder iban(String iban) {
      this.iban = iban;
      return this;
    }

    /**
     * Sets the value for {@code primary}.
     *
     * @param primary Determines if this bank account will be primary. Default is false
     * @return This builder instance.
     */
    public Builder primary(Boolean primary) {
      this.primary = primary;
      return this;
    }

    /**
     * Sets the value for {@code status}.
     *
     * @param status Determines the bank account status.
     * @return This builder instance.
     */
    public Builder status(com.sumup.sdk.models.BankAccountPayloadStatus status) {
      this.status = status;
      return this;
    }

    /**
     * Sets the value for {@code swift}.
     *
     * @param swift SWIFT code
     * @return This builder instance.
     */
    public Builder swift(String swift) {
      this.swift = swift;
      return this;
    }

    /**
     * Builds an immutable BankAccountPayload instance.
     *
     * @return Immutable BankAccountPayload.
     */
    public BankAccountPayload build() {
      return new BankAccountPayload(
          accountCategory,
          Objects.requireNonNull(accountHolderName, "accountHolderName"),
          accountNumber,
          accountType,
          bankCode,
          branchCode,
          checkDigit,
          Objects.requireNonNull(iban, "iban"),
          primary,
          status,
          Objects.requireNonNull(swift, "swift"));
    }
  }
}
