// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

public record BaseError(
    /**
     * A unique identifier for the error instance. This can be used to trace the error back to the
     * server logs.
     */
    String instance,

    /** A human-readable message describing the error that occurred. */
    String message) {
  /**
   * Creates a builder for BaseError.
   *
   * @return Builder that constructs immutable BaseError instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for BaseError instances. */
  public static final class Builder {
    private String instance;
    private String message;

    private Builder() {}

    /**
     * Sets the value for {@code instance}.
     *
     * @param instance A unique identifier for the error instance. This can be used to trace the
     *     error back to the server logs.
     * @return This builder instance.
     */
    public Builder instance(String instance) {
      this.instance = instance;
      return this;
    }

    /**
     * Sets the value for {@code message}.
     *
     * @param message A human-readable message describing the error that occurred.
     * @return This builder instance.
     */
    public Builder message(String message) {
      this.message = message;
      return this;
    }

    /**
     * Builds an immutable BaseError instance.
     *
     * @return Immutable BaseError.
     */
    public BaseError build() {
      return new BaseError(instance, message);
    }
  }
}
