// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/**
 * Settings used to apply the Merchant's branding to email receipts, invoices, checkouts, and other
 * products.
 */
public record Branding(
    /** A hex color value representing the preferred background color of this merchant. */
    String backgroundColor,

    /** Footer text rendered on receipts and other customer-facing products. */
    String footerText,

    /** Data-URL encoded hero image for the merchant business. */
    String hero,

    /** An icon for the merchant. Must be square. */
    String icon,

    /**
     * A logo for the merchant that will be used in place of the icon and without the merchant's
     * name next to it if there's sufficient space.
     */
    String logo,

    /**
     * A hex color value representing the primary branding color of this merchant (your brand
     * color).
     */
    String primaryColor,

    /**
     * A hex color value representing the color of the text displayed on branding color of this
     * merchant.
     */
    String primaryColorFg,

    /**
     * A hex color value representing the secondary branding color of this merchant (accent color
     * used for buttons).
     */
    String secondaryColor,

    /**
     * A hex color value representing the color of the text displayed on secondary branding color of
     * this merchant.
     */
    String secondaryColorFg) {
  /**
   * Creates a builder for Branding.
   *
   * @return Builder that constructs immutable Branding instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for Branding instances. */
  public static final class Builder {
    private String backgroundColor;
    private String footerText;
    private String hero;
    private String icon;
    private String logo;
    private String primaryColor;
    private String primaryColorFg;
    private String secondaryColor;
    private String secondaryColorFg;

    private Builder() {}

    /**
     * Sets the value for {@code backgroundColor}.
     *
     * @param backgroundColor A hex color value representing the preferred background color of this
     *     merchant.
     * @return This builder instance.
     */
    public Builder backgroundColor(String backgroundColor) {
      this.backgroundColor = backgroundColor;
      return this;
    }

    /**
     * Sets the value for {@code footerText}.
     *
     * @param footerText Footer text rendered on receipts and other customer-facing products.
     * @return This builder instance.
     */
    public Builder footerText(String footerText) {
      this.footerText = footerText;
      return this;
    }

    /**
     * Sets the value for {@code hero}.
     *
     * @param hero Data-URL encoded hero image for the merchant business.
     * @return This builder instance.
     */
    public Builder hero(String hero) {
      this.hero = hero;
      return this;
    }

    /**
     * Sets the value for {@code icon}.
     *
     * @param icon An icon for the merchant. Must be square.
     * @return This builder instance.
     */
    public Builder icon(String icon) {
      this.icon = icon;
      return this;
    }

    /**
     * Sets the value for {@code logo}.
     *
     * @param logo A logo for the merchant that will be used in place of the icon and without the
     *     merchant's name next to it if there's sufficient space.
     * @return This builder instance.
     */
    public Builder logo(String logo) {
      this.logo = logo;
      return this;
    }

    /**
     * Sets the value for {@code primaryColor}.
     *
     * @param primaryColor A hex color value representing the primary branding color of this
     *     merchant (your brand color).
     * @return This builder instance.
     */
    public Builder primaryColor(String primaryColor) {
      this.primaryColor = primaryColor;
      return this;
    }

    /**
     * Sets the value for {@code primaryColorFg}.
     *
     * @param primaryColorFg A hex color value representing the color of the text displayed on
     *     branding color of this merchant.
     * @return This builder instance.
     */
    public Builder primaryColorFg(String primaryColorFg) {
      this.primaryColorFg = primaryColorFg;
      return this;
    }

    /**
     * Sets the value for {@code secondaryColor}.
     *
     * @param secondaryColor A hex color value representing the secondary branding color of this
     *     merchant (accent color used for buttons).
     * @return This builder instance.
     */
    public Builder secondaryColor(String secondaryColor) {
      this.secondaryColor = secondaryColor;
      return this;
    }

    /**
     * Sets the value for {@code secondaryColorFg}.
     *
     * @param secondaryColorFg A hex color value representing the color of the text displayed on
     *     secondary branding color of this merchant.
     * @return This builder instance.
     */
    public Builder secondaryColorFg(String secondaryColorFg) {
      this.secondaryColorFg = secondaryColorFg;
      return this;
    }

    /**
     * Builds an immutable Branding instance.
     *
     * @return Immutable Branding.
     */
    public Branding build() {
      return new Branding(
          backgroundColor,
          footerText,
          hero,
          icon,
          logo,
          primaryColor,
          primaryColorFg,
          secondaryColor,
          secondaryColorFg);
    }
  }
}
