// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

public record BusinessOwnersItem(
    /** Date of birth */
    String dateOfBirth,

    /** BO's first name */
    String firstName,

    /** BO's Landline */
    String landline,

    /** BO's last name of the user */
    String lastName,

    /** Mobile phone number */
    String mobilePhone,

    /** Ownership percentage */
    Double ownership) {
  /**
   * Creates a builder for BusinessOwnersItem.
   *
   * @return Builder that constructs immutable BusinessOwnersItem instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for BusinessOwnersItem instances. */
  public static final class Builder {
    private String dateOfBirth;
    private String firstName;
    private String landline;
    private String lastName;
    private String mobilePhone;
    private Double ownership;

    private Builder() {}

    /**
     * Sets the value for {@code dateOfBirth}.
     *
     * @param dateOfBirth Date of birth
     * @return This builder instance.
     */
    public Builder dateOfBirth(String dateOfBirth) {
      this.dateOfBirth = dateOfBirth;
      return this;
    }

    /**
     * Sets the value for {@code firstName}.
     *
     * @param firstName BO's first name
     * @return This builder instance.
     */
    public Builder firstName(String firstName) {
      this.firstName = firstName;
      return this;
    }

    /**
     * Sets the value for {@code landline}.
     *
     * @param landline BO's Landline
     * @return This builder instance.
     */
    public Builder landline(String landline) {
      this.landline = landline;
      return this;
    }

    /**
     * Sets the value for {@code lastName}.
     *
     * @param lastName BO's last name of the user
     * @return This builder instance.
     */
    public Builder lastName(String lastName) {
      this.lastName = lastName;
      return this;
    }

    /**
     * Sets the value for {@code mobilePhone}.
     *
     * @param mobilePhone Mobile phone number
     * @return This builder instance.
     */
    public Builder mobilePhone(String mobilePhone) {
      this.mobilePhone = mobilePhone;
      return this;
    }

    /**
     * Sets the value for {@code ownership}.
     *
     * @param ownership Ownership percentage
     * @return This builder instance.
     */
    public Builder ownership(Double ownership) {
      this.ownership = ownership;
      return this;
    }

    /**
     * Builds an immutable BusinessOwnersItem instance.
     *
     * @return Immutable BusinessOwnersItem.
     */
    public BusinessOwnersItem build() {
      return new BusinessOwnersItem(
          dateOfBirth, firstName, landline, lastName, mobilePhone, ownership);
    }
  }
}
