// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/**
 * Business information about the merchant. This information will be visible to the merchant's
 * customers.
 */
public record BusinessProfile(
    /**
     * An address somewhere in the world. The address fields used depend on the country conventions.
     * For example, in Great Britain, `city` is `post_town`. In the United States, the top-level
     * administrative unit used in addresses is `state`, whereas in Chile it's `region`. Whether an
     * address is valid or not depends on whether the locally required fields are present. Fields
     * not supported in a country will be ignored.
     */
    com.sumup.sdk.models.Address address,

    /**
     * Settings used to apply the Merchant's branding to email receipts, invoices, checkouts, and
     * other products.
     */
    com.sumup.sdk.models.Branding branding,

    /**
     * The descriptor is the text that your customer sees on their bank account statement. The more
     * recognisable your descriptor is, the less risk you have of receiving disputes (e.g.
     * chargebacks).
     */
    String dynamicDescriptor,

    /** A publicly available email address. */
    String email,

    /** The customer-facing business name. */
    String name,

    /** A publicly available phone number in [E.164](https://en.wikipedia.org/wiki/E.164) format. */
    com.sumup.sdk.models.PhoneNumber phoneNumber,

    /** The business's publicly available website. */
    String website) {
  /**
   * Creates a builder for BusinessProfile.
   *
   * @return Builder that constructs immutable BusinessProfile instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for BusinessProfile instances. */
  public static final class Builder {
    private com.sumup.sdk.models.Address address;
    private com.sumup.sdk.models.Branding branding;
    private String dynamicDescriptor;
    private String email;
    private String name;
    private com.sumup.sdk.models.PhoneNumber phoneNumber;
    private String website;

    private Builder() {}

    /**
     * Sets the value for {@code address}.
     *
     * @param address An address somewhere in the world. The address fields used depend on the
     *     country conventions. For example, in Great Britain, `city` is `post_town`. In the United
     *     States, the top-level administrative unit used in addresses is `state`, whereas in Chile
     *     it's `region`. Whether an address is valid or not depends on whether the locally required
     *     fields are present. Fields not supported in a country will be ignored.
     * @return This builder instance.
     */
    public Builder address(com.sumup.sdk.models.Address address) {
      this.address = address;
      return this;
    }

    /**
     * Sets the value for {@code branding}.
     *
     * @param branding Settings used to apply the Merchant's branding to email receipts, invoices,
     *     checkouts, and other products.
     * @return This builder instance.
     */
    public Builder branding(com.sumup.sdk.models.Branding branding) {
      this.branding = branding;
      return this;
    }

    /**
     * Sets the value for {@code dynamicDescriptor}.
     *
     * @param dynamicDescriptor The descriptor is the text that your customer sees on their bank
     *     account statement. The more recognisable your descriptor is, the less risk you have of
     *     receiving disputes (e.g. chargebacks).
     * @return This builder instance.
     */
    public Builder dynamicDescriptor(String dynamicDescriptor) {
      this.dynamicDescriptor = dynamicDescriptor;
      return this;
    }

    /**
     * Sets the value for {@code email}.
     *
     * @param email A publicly available email address.
     * @return This builder instance.
     */
    public Builder email(String email) {
      this.email = email;
      return this;
    }

    /**
     * Sets the value for {@code name}.
     *
     * @param name The customer-facing business name.
     * @return This builder instance.
     */
    public Builder name(String name) {
      this.name = name;
      return this;
    }

    /**
     * Sets the value for {@code phoneNumber}.
     *
     * @param phoneNumber A publicly available phone number in
     *     [E.164](https://en.wikipedia.org/wiki/E.164) format.
     * @return This builder instance.
     */
    public Builder phoneNumber(com.sumup.sdk.models.PhoneNumber phoneNumber) {
      this.phoneNumber = phoneNumber;
      return this;
    }

    /**
     * Sets the value for {@code website}.
     *
     * @param website The business's publicly available website.
     * @return This builder instance.
     */
    public Builder website(String website) {
      this.website = website;
      return this;
    }

    /**
     * Builds an immutable BusinessProfile instance.
     *
     * @return Immutable BusinessProfile.
     */
    public BusinessProfile build() {
      return new BusinessProfile(
          address, branding, dynamicDescriptor, email, name, phoneNumber, website);
    }
  }
}
