// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

/** Issuing card network of the payment card used for the transaction. */
public final class CardType {
  public static final CardType ALELO = new CardType("ALELO");
  public static final CardType AMEX = new CardType("AMEX");
  public static final CardType CONECS = new CardType("CONECS");
  public static final CardType CUP = new CardType("CUP");
  public static final CardType DINERS = new CardType("DINERS");
  public static final CardType DISCOVER = new CardType("DISCOVER");
  public static final CardType EFTPOS = new CardType("EFTPOS");
  public static final CardType ELO = new CardType("ELO");
  public static final CardType ELV = new CardType("ELV");
  public static final CardType GIROCARD = new CardType("GIROCARD");
  public static final CardType HIPERCARD = new CardType("HIPERCARD");
  public static final CardType INTERAC = new CardType("INTERAC");
  public static final CardType JCB = new CardType("JCB");
  public static final CardType MAESTRO = new CardType("MAESTRO");
  public static final CardType MASTERCARD = new CardType("MASTERCARD");
  public static final CardType PLUXEE = new CardType("PLUXEE");
  public static final CardType SWILE = new CardType("SWILE");
  public static final CardType TICKET = new CardType("TICKET");
  public static final CardType VISA = new CardType("VISA");
  public static final CardType VISA_ELECTRON = new CardType("VISA_ELECTRON");
  public static final CardType VISA_VPAY = new CardType("VISA_VPAY");
  public static final CardType VPAY = new CardType("VPAY");
  public static final CardType VR = new CardType("VR");
  public static final CardType UNKNOWN = new CardType("UNKNOWN");

  private final String value;

  private CardType(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a CardType for a value not yet known to this SDK version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static CardType of(String value) {
    return new CardType(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static CardType fromValue(String value) {
    return value == null ? null : new CardType(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof CardType that && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
