// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Issuing card network of the payment card used for the transaction. */
public enum CardType {
  AMEX("AMEX"),
  CUP("CUP"),
  DINERS("DINERS"),
  DISCOVER("DISCOVER"),
  ELO("ELO"),
  ELV("ELV"),
  HIPERCARD("HIPERCARD"),
  JCB("JCB"),
  MAESTRO("MAESTRO"),
  MASTERCARD("MASTERCARD"),
  VISA("VISA"),
  VISA_ELECTRON("VISA_ELECTRON"),
  VISA_VPAY("VISA_VPAY"),
  UNKNOWN("UNKNOWN");

  private final String value;

  CardType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static CardType fromValue(String value) {
    if (value == null) {
      return null;
    }
    for (CardType entry : values()) {
      if (entry.value.equals(value)) {
        return entry;
      }
    }
    throw new IllegalArgumentException("Unknown CardType value: " + value);
  }
}
