// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** Details of the payment card. */
public record CardResponse(
    /** Last 4 digits of the payment card number. */
    String last4Digits,

    /** Issuing card network of the payment card used for the transaction. */
    com.sumup.sdk.models.CardType type) {
  /**
   * Creates a builder for CardResponse.
   *
   * @return Builder that constructs immutable CardResponse instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for CardResponse instances. */
  public static final class Builder {
    private String last4Digits;
    private com.sumup.sdk.models.CardType type;

    private Builder() {}

    /**
     * Sets the value for {@code last4Digits}.
     *
     * @param last4Digits Last 4 digits of the payment card number.
     * @return This builder instance.
     */
    public Builder last4Digits(String last4Digits) {
      this.last4Digits = last4Digits;
      return this;
    }

    /**
     * Sets the value for {@code type}.
     *
     * @param type Issuing card network of the payment card used for the transaction.
     * @return This builder instance.
     */
    public Builder type(com.sumup.sdk.models.CardType type) {
      this.type = type;
      return this;
    }

    /**
     * Builds an immutable CardResponse instance.
     *
     * @return Immutable CardResponse.
     */
    public CardResponse build() {
      return new CardResponse(last4Digits, type);
    }
  }
}
