// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/**
 * Reflects the status of changes submitted through the `PATCH` endpoints for the merchant or
 * persons. If some changes have not been applied yet, the status will be `pending`. If all changes
 * have been applied, the status `done`. The status is only returned after write operations or on
 * read endpoints when the `version` query parameter is provided.
 */
public record ChangeStatus(String value) {}
