// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Current status of the checkout. */
public enum CheckoutCreateRequestStatus {
  PENDING("PENDING"),
  FAILED("FAILED"),
  PAID("PAID");

  private final String value;

  CheckoutCreateRequestStatus(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static CheckoutCreateRequestStatus fromValue(String value) {
    if (value == null) {
      return null;
    }
    for (CheckoutCreateRequestStatus entry : values()) {
      if (entry.value.equals(value)) {
        return entry;
      }
    }
    throw new IllegalArgumentException("Unknown CheckoutCreateRequestStatus value: " + value);
  }
}
