// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** Required action processing 3D Secure payments. */
public record CheckoutAcceptedNextStep(
    /**
     * Indicates allowed mechanisms for redirecting an end user. If both values are provided to
     * ensure a redirect takes place in either.
     */
    java.util.List<String> mechanism,

    /** Method used to complete the redirect. */
    String method,

    /**
     * Contains parameters essential for form redirection. Number of object keys and their content
     * can vary.
     */
    com.sumup.sdk.models.CheckoutAcceptedNextStepPayload payload,

    /** Refers to a url where the end user is redirected once the payment processing completes. */
    String redirectUrl,

    /** Where the end user is redirected. */
    String url) {
  /**
   * Creates a builder for CheckoutAcceptedNextStep.
   *
   * @return Builder that constructs immutable CheckoutAcceptedNextStep instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for CheckoutAcceptedNextStep instances. */
  public static final class Builder {
    private java.util.List<String> mechanism;
    private String method;
    private com.sumup.sdk.models.CheckoutAcceptedNextStepPayload payload;
    private String redirectUrl;
    private String url;

    private Builder() {}

    /**
     * Sets the value for {@code mechanism}.
     *
     * @param mechanism Indicates allowed mechanisms for redirecting an end user. If both values are
     *     provided to ensure a redirect takes place in either.
     * @return This builder instance.
     */
    public Builder mechanism(java.util.List<String> mechanism) {
      this.mechanism = mechanism;
      return this;
    }

    /**
     * Sets the value for {@code method}.
     *
     * @param method Method used to complete the redirect.
     * @return This builder instance.
     */
    public Builder method(String method) {
      this.method = method;
      return this;
    }

    /**
     * Sets the value for {@code payload}.
     *
     * @param payload Contains parameters essential for form redirection. Number of object keys and
     *     their content can vary.
     * @return This builder instance.
     */
    public Builder payload(com.sumup.sdk.models.CheckoutAcceptedNextStepPayload payload) {
      this.payload = payload;
      return this;
    }

    /**
     * Sets the value for {@code redirectUrl}.
     *
     * @param redirectUrl Refers to a url where the end user is redirected once the payment
     *     processing completes.
     * @return This builder instance.
     */
    public Builder redirectUrl(String redirectUrl) {
      this.redirectUrl = redirectUrl;
      return this;
    }

    /**
     * Sets the value for {@code url}.
     *
     * @param url Where the end user is redirected.
     * @return This builder instance.
     */
    public Builder url(String url) {
      this.url = url;
      return this;
    }

    /**
     * Builds an immutable CheckoutAcceptedNextStep instance.
     *
     * @return Immutable CheckoutAcceptedNextStep.
     */
    public CheckoutAcceptedNextStep build() {
      return new CheckoutAcceptedNextStep(mechanism, method, payload, redirectUrl, url);
    }
  }
}
