// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

public record CheckoutSuccess(com.sumup.sdk.models.Checkout value) {
  /**
   * Creates a builder for CheckoutSuccess.
   *
   * @return Builder that constructs immutable CheckoutSuccess instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for CheckoutSuccess instances. */
  public static final class Builder {
    private com.sumup.sdk.models.Checkout value;

    private Builder() {}

    /**
     * Sets the value for {@code value}.
     *
     * @param value Value for the value field.
     * @return This builder instance.
     */
    public Builder value(com.sumup.sdk.models.Checkout value) {
      this.value = value;
      return this;
    }

    /**
     * Builds an immutable CheckoutSuccess instance.
     *
     * @return Immutable CheckoutSuccess.
     */
    public CheckoutSuccess build() {
      return new CheckoutSuccess(value);
    }
  }
}
