// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/**
 * Contains parameters essential for form redirection. Number of object keys and their content can
 * vary.
 */
public record CheckoutAcceptedNextStepPayload(
    java.util.Map<String, Object> md,
    java.util.Map<String, Object> paReq,
    java.util.Map<String, Object> termUrl) {
  /**
   * Creates a builder for CheckoutAcceptedNextStepPayload.
   *
   * @return Builder that constructs immutable CheckoutAcceptedNextStepPayload instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for CheckoutAcceptedNextStepPayload instances. */
  public static final class Builder {
    private java.util.Map<String, Object> md;
    private java.util.Map<String, Object> paReq;
    private java.util.Map<String, Object> termUrl;

    private Builder() {}

    /**
     * Sets the value for {@code md}.
     *
     * @param md Value for the md field.
     * @return This builder instance.
     */
    public Builder md(java.util.Map<String, Object> md) {
      this.md = md;
      return this;
    }

    /**
     * Sets the value for {@code paReq}.
     *
     * @param paReq Value for the paReq field.
     * @return This builder instance.
     */
    public Builder paReq(java.util.Map<String, Object> paReq) {
      this.paReq = paReq;
      return this;
    }

    /**
     * Sets the value for {@code termUrl}.
     *
     * @param termUrl Value for the termUrl field.
     * @return This builder instance.
     */
    public Builder termUrl(java.util.Map<String, Object> termUrl) {
      this.termUrl = termUrl;
      return this;
    }

    /**
     * Builds an immutable CheckoutAcceptedNextStepPayload instance.
     *
     * @return Immutable CheckoutAcceptedNextStepPayload.
     */
    public CheckoutAcceptedNextStepPayload build() {
      return new CheckoutAcceptedNextStepPayload(md, paReq, termUrl);
    }
  }
}
