// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/**
 * Request body for updating an existing checkout. Include only the fields that should be changed.
 */
public record CheckoutUpdateRequest(
    /** Updated amount to be charged to the payer, expressed in major units. */
    Float amount,

    /** Updated merchant-defined reference for the checkout. */
    String checkoutReference,

    /**
     * Three-letter [ISO4217](https://en.wikipedia.org/wiki/ISO_4217) code of the currency for the
     * amount. Currently supported currency values are enumerated above.
     */
    com.sumup.sdk.models.Currency currency,

    /** Updated merchant-scoped customer identifier associated with the checkout. */
    String customerId,

    /** Updated short merchant-defined description shown in SumUp tools and reporting. */
    String description,

    /**
     * Updated expiration timestamp. The checkout must be processed before this moment, otherwise it
     * becomes unusable.
     */
    java.time.OffsetDateTime validUntil) {
  /**
   * Creates a builder for CheckoutUpdateRequest.
   *
   * @return Builder that constructs immutable CheckoutUpdateRequest instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for CheckoutUpdateRequest instances. */
  public static final class Builder {
    private Float amount;
    private String checkoutReference;
    private com.sumup.sdk.models.Currency currency;
    private String customerId;
    private String description;
    private java.time.OffsetDateTime validUntil;

    private Builder() {}

    /**
     * Sets the value for {@code amount}.
     *
     * @param amount Updated amount to be charged to the payer, expressed in major units.
     * @return This builder instance.
     */
    public Builder amount(Float amount) {
      this.amount = amount;
      return this;
    }

    /**
     * Sets the value for {@code checkoutReference}.
     *
     * @param checkoutReference Updated merchant-defined reference for the checkout.
     * @return This builder instance.
     */
    public Builder checkoutReference(String checkoutReference) {
      this.checkoutReference = checkoutReference;
      return this;
    }

    /**
     * Sets the value for {@code currency}.
     *
     * @param currency Three-letter [ISO4217](https://en.wikipedia.org/wiki/ISO_4217) code of the
     *     currency for the amount. Currently supported currency values are enumerated above.
     * @return This builder instance.
     */
    public Builder currency(com.sumup.sdk.models.Currency currency) {
      this.currency = currency;
      return this;
    }

    /**
     * Sets the value for {@code customerId}.
     *
     * @param customerId Updated merchant-scoped customer identifier associated with the checkout.
     * @return This builder instance.
     */
    public Builder customerId(String customerId) {
      this.customerId = customerId;
      return this;
    }

    /**
     * Sets the value for {@code description}.
     *
     * @param description Updated short merchant-defined description shown in SumUp tools and
     *     reporting.
     * @return This builder instance.
     */
    public Builder description(String description) {
      this.description = description;
      return this;
    }

    /**
     * Sets the value for {@code validUntil}.
     *
     * @param validUntil Updated expiration timestamp. The checkout must be processed before this
     *     moment, otherwise it becomes unusable.
     * @return This builder instance.
     */
    public Builder validUntil(java.time.OffsetDateTime validUntil) {
      this.validUntil = validUntil;
      return this;
    }

    /**
     * Builds an immutable CheckoutUpdateRequest instance.
     *
     * @return Immutable CheckoutUpdateRequest.
     */
    public CheckoutUpdateRequest build() {
      return new CheckoutUpdateRequest(
          amount, checkoutReference, currency, customerId, description, validUntil);
    }
  }
}
