// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** 3DS Response */
public record CheckoutAccepted(
    /** Required action processing 3D Secure payments. */
    com.sumup.sdk.models.CheckoutAcceptedNextStep nextStep) {
  /**
   * Creates a builder for CheckoutAccepted.
   *
   * @return Builder that constructs immutable CheckoutAccepted instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for CheckoutAccepted instances. */
  public static final class Builder {
    private com.sumup.sdk.models.CheckoutAcceptedNextStep nextStep;

    private Builder() {}

    /**
     * Sets the value for {@code nextStep}.
     *
     * @param nextStep Required action processing 3D Secure payments.
     * @return This builder instance.
     */
    public Builder nextStep(com.sumup.sdk.models.CheckoutAcceptedNextStep nextStep) {
      this.nextStep = nextStep;
      return this;
    }

    /**
     * Builds an immutable CheckoutAccepted instance.
     *
     * @return Immutable CheckoutAccepted.
     */
    public CheckoutAccepted build() {
      return new CheckoutAccepted(nextStep);
    }
  }
}
