// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

public final class CheckoutAcceptedNextStepMechanismItem {
  public static final CheckoutAcceptedNextStepMechanismItem IFRAME =
      new CheckoutAcceptedNextStepMechanismItem("iframe");
  public static final CheckoutAcceptedNextStepMechanismItem BROWSER =
      new CheckoutAcceptedNextStepMechanismItem("browser");

  private final String value;

  private CheckoutAcceptedNextStepMechanismItem(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a CheckoutAcceptedNextStepMechanismItem for a value not yet known to this SDK version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static CheckoutAcceptedNextStepMechanismItem of(String value) {
    return new CheckoutAcceptedNextStepMechanismItem(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static CheckoutAcceptedNextStepMechanismItem fromValue(String value) {
    return value == null ? null : new CheckoutAcceptedNextStepMechanismItem(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof CheckoutAcceptedNextStepMechanismItem that
            && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
