// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum CheckoutAcceptedNextStepMechanismItem {
  IFRAME("iframe"),
  BROWSER("browser");

  private final String value;

  CheckoutAcceptedNextStepMechanismItem(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static CheckoutAcceptedNextStepMechanismItem fromValue(String value) {
    if (value == null) {
      return null;
    }
    for (CheckoutAcceptedNextStepMechanismItem entry : values()) {
      if (entry.value.equals(value)) {
        return entry;
      }
    }
    throw new IllegalArgumentException(
        "Unknown CheckoutAcceptedNextStepMechanismItem value: " + value);
  }
}
