// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/**
 * Response returned when checkout processing requires an additional payer action, such as a 3DS
 * challenge or a redirect to an external payment method page.
 */
public record CheckoutAccepted(
    /** Instructions for the next action the payer or client must take. */
    com.sumup.sdk.models.CheckoutAcceptedNextStep nextStep) {
  /**
   * Creates a builder for CheckoutAccepted.
   *
   * @return Builder that constructs immutable CheckoutAccepted instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for CheckoutAccepted instances. */
  public static final class Builder {
    private com.sumup.sdk.models.CheckoutAcceptedNextStep nextStep;

    private Builder() {}

    /**
     * Sets the value for {@code nextStep}.
     *
     * @param nextStep Instructions for the next action the payer or client must take.
     * @return This builder instance.
     */
    public Builder nextStep(com.sumup.sdk.models.CheckoutAcceptedNextStep nextStep) {
      this.nextStep = nextStep;
      return this;
    }

    /**
     * Builds an immutable CheckoutAccepted instance.
     *
     * @return Immutable CheckoutAccepted.
     */
    public CheckoutAccepted build() {
      return new CheckoutAccepted(nextStep);
    }
  }
}
