// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

public record ClassicMerchantIdentifiers(
    /** Classic (serial) merchant ID. */
    Long id) {
  /**
   * Creates a builder for ClassicMerchantIdentifiers.
   *
   * @return Builder that constructs immutable ClassicMerchantIdentifiers instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for ClassicMerchantIdentifiers instances. */
  public static final class Builder {
    private Long id;

    private Builder() {}

    /**
     * Sets the value for {@code id}.
     *
     * @param id Classic (serial) merchant ID.
     * @return This builder instance.
     */
    public Builder id(Long id) {
      this.id = id;
      return this;
    }

    /**
     * Builds an immutable ClassicMerchantIdentifiers instance.
     *
     * @return Immutable ClassicMerchantIdentifiers.
     */
    public ClassicMerchantIdentifiers build() {
      return new ClassicMerchantIdentifiers(Objects.requireNonNull(id, "id"));
    }
  }
}
