// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** A list of country-specific company identifiers. */
public record CompanyIdentifiers(java.util.List<com.sumup.sdk.models.CompanyIdentifier> value) {}
