// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/**
 * An [ISO3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country code. This
 * definition users `oneOf` with a two-character string type to allow for support of future
 * countries in client code.
 */
public record CountryCode(String value) {}
