// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** Country Details */
public record CountryDetails(
    /** Currency ISO 4217 code */
    String currency,

    /** Country EN name */
    String enName,

    /** Country ISO code */
    String isoCode,

    /** Country native name */
    String nativeName) {
  /**
   * Creates a builder for CountryDetails.
   *
   * @return Builder that constructs immutable CountryDetails instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for CountryDetails instances. */
  public static final class Builder {
    private String currency;
    private String enName;
    private String isoCode;
    private String nativeName;

    private Builder() {}

    /**
     * Sets the value for {@code currency}.
     *
     * @param currency Currency ISO 4217 code
     * @return This builder instance.
     */
    public Builder currency(String currency) {
      this.currency = currency;
      return this;
    }

    /**
     * Sets the value for {@code enName}.
     *
     * @param enName Country EN name
     * @return This builder instance.
     */
    public Builder enName(String enName) {
      this.enName = enName;
      return this;
    }

    /**
     * Sets the value for {@code isoCode}.
     *
     * @param isoCode Country ISO code
     * @return This builder instance.
     */
    public Builder isoCode(String isoCode) {
      this.isoCode = isoCode;
      return this;
    }

    /**
     * Sets the value for {@code nativeName}.
     *
     * @param nativeName Country native name
     * @return This builder instance.
     */
    public Builder nativeName(String nativeName) {
      this.nativeName = nativeName;
      return this;
    }

    /**
     * Builds an immutable CountryDetails instance.
     *
     * @return Immutable CountryDetails.
     */
    public CountryDetails build() {
      return new CountryDetails(currency, enName, isoCode, nativeName);
    }
  }
}
