// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

public record CreateSubAccountRequest(
    String nickname,
    String password,
    com.sumup.sdk.models.CreateSubAccountRequestPermissions permissions,
    String username) {
  /**
   * Creates a builder for CreateSubAccountRequest.
   *
   * @return Builder that constructs immutable CreateSubAccountRequest instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for CreateSubAccountRequest instances. */
  public static final class Builder {
    private String nickname;
    private String password;
    private com.sumup.sdk.models.CreateSubAccountRequestPermissions permissions;
    private String username;

    private Builder() {}

    /**
     * Sets the value for {@code nickname}.
     *
     * @param nickname Value for the nickname field.
     * @return This builder instance.
     */
    public Builder nickname(String nickname) {
      this.nickname = nickname;
      return this;
    }

    /**
     * Sets the value for {@code password}.
     *
     * @param password Value for the password field.
     * @return This builder instance.
     */
    public Builder password(String password) {
      this.password = password;
      return this;
    }

    /**
     * Sets the value for {@code permissions}.
     *
     * @param permissions Value for the permissions field.
     * @return This builder instance.
     */
    public Builder permissions(
        com.sumup.sdk.models.CreateSubAccountRequestPermissions permissions) {
      this.permissions = permissions;
      return this;
    }

    /**
     * Sets the value for {@code username}.
     *
     * @param username Value for the username field.
     * @return This builder instance.
     */
    public Builder username(String username) {
      this.username = username;
      return this;
    }

    /**
     * Builds an immutable CreateSubAccountRequest instance.
     *
     * @return Immutable CreateSubAccountRequest.
     */
    public CreateSubAccountRequest build() {
      return new CreateSubAccountRequest(
          nickname,
          Objects.requireNonNull(password, "password"),
          permissions,
          Objects.requireNonNull(username, "username"));
    }
  }
}
