// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

public record CreateMerchantRoleRequest(
    /** User-defined description of the role. */
    String description,

    /**
     * Set of user-defined key-value pairs attached to the object. Partial updates are not
     * supported. When updating, always submit whole metadata. Maximum of 64 parameters are allowed
     * in the object.
     */
    com.sumup.sdk.models.Metadata metadata,

    /** User-defined name of the role. */
    String name,

    /** User's permissions. */
    java.util.List<String> permissions) {
  /**
   * Creates a builder for CreateMerchantRoleRequest.
   *
   * @return Builder that constructs immutable CreateMerchantRoleRequest instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for CreateMerchantRoleRequest instances. */
  public static final class Builder {
    private String description;
    private com.sumup.sdk.models.Metadata metadata;
    private String name;
    private java.util.List<String> permissions;

    private Builder() {}

    /**
     * Sets the value for {@code description}.
     *
     * @param description User-defined description of the role.
     * @return This builder instance.
     */
    public Builder description(String description) {
      this.description = description;
      return this;
    }

    /**
     * Sets the value for {@code metadata}.
     *
     * @param metadata Set of user-defined key-value pairs attached to the object. Partial updates
     *     are not supported. When updating, always submit whole metadata. Maximum of 64 parameters
     *     are allowed in the object.
     * @return This builder instance.
     */
    public Builder metadata(com.sumup.sdk.models.Metadata metadata) {
      this.metadata = metadata;
      return this;
    }

    /**
     * Sets the value for {@code name}.
     *
     * @param name User-defined name of the role.
     * @return This builder instance.
     */
    public Builder name(String name) {
      this.name = name;
      return this;
    }

    /**
     * Sets the value for {@code permissions}.
     *
     * @param permissions User's permissions.
     * @return This builder instance.
     */
    public Builder permissions(java.util.List<String> permissions) {
      this.permissions = permissions;
      return this;
    }

    /**
     * Builds an immutable CreateMerchantRoleRequest instance.
     *
     * @return Immutable CreateMerchantRoleRequest.
     */
    public CreateMerchantRoleRequest build() {
      return new CreateMerchantRoleRequest(
          description,
          metadata,
          Objects.requireNonNull(name, "name"),
          Objects.requireNonNull(permissions, "permissions"));
    }
  }
}
