// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

public record CreateReaderTerminateErrorErrors(
    /** Error message */
    String detail) {
  /**
   * Creates a builder for CreateReaderTerminateErrorErrors.
   *
   * @return Builder that constructs immutable CreateReaderTerminateErrorErrors instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for CreateReaderTerminateErrorErrors instances. */
  public static final class Builder {
    private String detail;

    private Builder() {}

    /**
     * Sets the value for {@code detail}.
     *
     * @param detail Error message
     * @return This builder instance.
     */
    public Builder detail(String detail) {
      this.detail = detail;
      return this;
    }

    /**
     * Builds an immutable CreateReaderTerminateErrorErrors instance.
     *
     * @return Immutable CreateReaderTerminateErrorErrors.
     */
    public CreateReaderTerminateErrorErrors build() {
      return new CreateReaderTerminateErrorErrors(detail);
    }
  }
}
