// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

public record CreateReaderRequest(
    /**
     * Set of user-defined key-value pairs attached to the object. Partial updates are not
     * supported. When updating, always submit whole metadata. Maximum of 64 parameters are allowed
     * in the object.
     */
    com.sumup.sdk.models.Metadata metadata,

    /** Custom human-readable, user-defined name for easier identification of the reader. */
    com.sumup.sdk.models.ReaderName name,

    /**
     * The pairing code is a 8 or 9 character alphanumeric string that is displayed on a SumUp
     * Device after initiating the pairing. It is used to link the physical device to the created
     * pairing.
     */
    com.sumup.sdk.models.ReaderPairingCode pairingCode) {
  /**
   * Creates a builder for CreateReaderRequest.
   *
   * @return Builder that constructs immutable CreateReaderRequest instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for CreateReaderRequest instances. */
  public static final class Builder {
    private com.sumup.sdk.models.Metadata metadata;
    private com.sumup.sdk.models.ReaderName name;
    private com.sumup.sdk.models.ReaderPairingCode pairingCode;

    private Builder() {}

    /**
     * Sets the value for {@code metadata}.
     *
     * @param metadata Set of user-defined key-value pairs attached to the object. Partial updates
     *     are not supported. When updating, always submit whole metadata. Maximum of 64 parameters
     *     are allowed in the object.
     * @return This builder instance.
     */
    public Builder metadata(com.sumup.sdk.models.Metadata metadata) {
      this.metadata = metadata;
      return this;
    }

    /**
     * Sets the value for {@code name}.
     *
     * @param name Custom human-readable, user-defined name for easier identification of the reader.
     * @return This builder instance.
     */
    public Builder name(com.sumup.sdk.models.ReaderName name) {
      this.name = name;
      return this;
    }

    /**
     * Sets the value for {@code pairingCode}.
     *
     * @param pairingCode The pairing code is a 8 or 9 character alphanumeric string that is
     *     displayed on a SumUp Device after initiating the pairing. It is used to link the physical
     *     device to the created pairing.
     * @return This builder instance.
     */
    public Builder pairingCode(com.sumup.sdk.models.ReaderPairingCode pairingCode) {
      this.pairingCode = pairingCode;
      return this;
    }

    /**
     * Builds an immutable CreateReaderRequest instance.
     *
     * @return Immutable CreateReaderRequest.
     */
    public CreateReaderRequest build() {
      return new CreateReaderRequest(
          metadata,
          Objects.requireNonNull(name, "name"),
          Objects.requireNonNull(pairingCode, "pairingCode"));
    }
  }
}
