// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

public record CreateReaderCheckoutErrorErrors(
    /** Error message */
    String detail,

    /** Error code */
    String type) {
  /**
   * Creates a builder for CreateReaderCheckoutErrorErrors.
   *
   * @return Builder that constructs immutable CreateReaderCheckoutErrorErrors instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for CreateReaderCheckoutErrorErrors instances. */
  public static final class Builder {
    private String detail;
    private String type;

    private Builder() {}

    /**
     * Sets the value for {@code detail}.
     *
     * @param detail Error message
     * @return This builder instance.
     */
    public Builder detail(String detail) {
      this.detail = detail;
      return this;
    }

    /**
     * Sets the value for {@code type}.
     *
     * @param type Error code
     * @return This builder instance.
     */
    public Builder type(String type) {
      this.type = type;
      return this;
    }

    /**
     * Builds an immutable CreateReaderCheckoutErrorErrors instance.
     *
     * @return Immutable CreateReaderCheckoutErrorErrors.
     */
    public CreateReaderCheckoutErrorErrors build() {
      return new CreateReaderCheckoutErrorErrors(detail, Objects.requireNonNull(type, "type"));
    }
  }
}
