// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

/** Unprocessable entity */
public record CreateReaderCheckoutUnprocessableEntity(java.util.Map<String, Object> errors) {
  /**
   * Creates a builder for CreateReaderCheckoutUnprocessableEntity.
   *
   * @return Builder that constructs immutable CreateReaderCheckoutUnprocessableEntity instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for CreateReaderCheckoutUnprocessableEntity instances. */
  public static final class Builder {
    private java.util.Map<String, Object> errors;

    private Builder() {}

    /**
     * Sets the value for {@code errors}.
     *
     * @param errors Value for the errors field.
     * @return This builder instance.
     */
    public Builder errors(java.util.Map<String, Object> errors) {
      this.errors = errors;
      return this;
    }

    /**
     * Builds an immutable CreateReaderCheckoutUnprocessableEntity instance.
     *
     * @return Immutable CreateReaderCheckoutUnprocessableEntity.
     */
    public CreateReaderCheckoutUnprocessableEntity build() {
      return new CreateReaderCheckoutUnprocessableEntity(Objects.requireNonNull(errors, "errors"));
    }
  }
}
