// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

/** Error description */
public record CreateReaderTerminateError(
    com.sumup.sdk.models.CreateReaderTerminateErrorErrors errors) {
  /**
   * Creates a builder for CreateReaderTerminateError.
   *
   * @return Builder that constructs immutable CreateReaderTerminateError instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for CreateReaderTerminateError instances. */
  public static final class Builder {
    private com.sumup.sdk.models.CreateReaderTerminateErrorErrors errors;

    private Builder() {}

    /**
     * Sets the value for {@code errors}.
     *
     * @param errors Value for the errors field.
     * @return This builder instance.
     */
    public Builder errors(com.sumup.sdk.models.CreateReaderTerminateErrorErrors errors) {
      this.errors = errors;
      return this;
    }

    /**
     * Builds an immutable CreateReaderTerminateError instance.
     *
     * @return Immutable CreateReaderTerminateError.
     */
    public CreateReaderTerminateError build() {
      return new CreateReaderTerminateError(Objects.requireNonNull(errors, "errors"));
    }
  }
}
