// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Three-letter [ISO4217](https://en.wikipedia.org/wiki/ISO_4217) code of the currency for the
 * amount. Currently supported currency values are enumerated above.
 */
public enum Currency {
  BGN("BGN"),
  BRL("BRL"),
  CHF("CHF"),
  CLP("CLP"),
  CZK("CZK"),
  DKK("DKK"),
  EUR("EUR"),
  GBP("GBP"),
  HRK("HRK"),
  HUF("HUF"),
  NOK("NOK"),
  PLN("PLN"),
  RON("RON"),
  SEK("SEK"),
  USD("USD");

  private final String value;

  Currency(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static Currency fromValue(String value) {
    if (value == null) {
      return null;
    }
    for (Currency entry : values()) {
      if (entry.value.equals(value)) {
        return entry;
      }
    }
    throw new IllegalArgumentException("Unknown Currency value: " + value);
  }
}
