// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/**
 * Three-letter [ISO4217](https://en.wikipedia.org/wiki/ISO_4217) code of the currency for the
 * amount. Currently supported currency values are enumerated above.
 */
public record Currency(String value) {
  /**
   * Creates a builder for Currency.
   *
   * @return Builder that constructs immutable Currency instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for Currency instances. */
  public static final class Builder {
    private String value;

    private Builder() {}

    /**
     * Sets the value for {@code value}.
     *
     * @param value Value for the value field.
     * @return This builder instance.
     */
    public Builder value(String value) {
      this.value = value;
      return this;
    }

    /**
     * Builds an immutable Currency instance.
     *
     * @return Immutable Currency.
     */
    public Currency build() {
      return new Currency(value);
    }
  }
}
