// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

/** Saved customer details. */
public record Customer(
    /** Unique identifier of the customer. */
    String customerId,

    /** Personal details for the customer. */
    com.sumup.sdk.models.PersonalDetails personalDetails) {
  /**
   * Creates a builder for Customer.
   *
   * @return Builder that constructs immutable Customer instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for Customer instances. */
  public static final class Builder {
    private String customerId;
    private com.sumup.sdk.models.PersonalDetails personalDetails;

    private Builder() {}

    /**
     * Sets the value for {@code customerId}.
     *
     * @param customerId Unique identifier of the customer.
     * @return This builder instance.
     */
    public Builder customerId(String customerId) {
      this.customerId = customerId;
      return this;
    }

    /**
     * Sets the value for {@code personalDetails}.
     *
     * @param personalDetails Personal details for the customer.
     * @return This builder instance.
     */
    public Builder personalDetails(com.sumup.sdk.models.PersonalDetails personalDetails) {
      this.personalDetails = personalDetails;
      return this;
    }

    /**
     * Builds an immutable Customer instance.
     *
     * @return Immutable Customer.
     */
    public Customer build() {
      return new Customer(Objects.requireNonNull(customerId, "customerId"), personalDetails);
    }
  }
}
