// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

public record DetailsErrorFailedConstraintsItem(String message, String reference) {

  /**
   * Creates a builder for DetailsErrorFailedConstraintsItem.
   *
   * @return Builder that constructs immutable DetailsErrorFailedConstraintsItem instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for DetailsErrorFailedConstraintsItem instances. */
  public static final class Builder {
    private String message;
    private String reference;

    private Builder() {}

    /**
     * Sets the value for {@code message}.
     *
     * @param message Value for the message field.
     * @return This builder instance.
     */
    public Builder message(String message) {
      this.message = message;
      return this;
    }

    /**
     * Sets the value for {@code reference}.
     *
     * @param reference Value for the reference field.
     * @return This builder instance.
     */
    public Builder reference(String reference) {
      this.reference = reference;
      return this;
    }

    /**
     * Builds an immutable DetailsErrorFailedConstraintsItem instance.
     *
     * @return Immutable DetailsErrorFailedConstraintsItem.
     */
    public DetailsErrorFailedConstraintsItem build() {
      return new DetailsErrorFailedConstraintsItem(message, reference);
    }
  }
}
