// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

public record DoingBusinessAsLegacyAddress(
    /** Address line 1 */
    String addressLine1,

    /** Address line 2 */
    String addressLine2,

    /** City */
    String city,

    /** Country ISO 3166-1 code */
    String country,

    /** Postal code */
    String postCode,

    /** Country region ID */
    Double regionId,

    /** Country region name */
    String regionName) {
  /**
   * Creates a builder for DoingBusinessAsLegacyAddress.
   *
   * @return Builder that constructs immutable DoingBusinessAsLegacyAddress instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for DoingBusinessAsLegacyAddress instances. */
  public static final class Builder {
    private String addressLine1;
    private String addressLine2;
    private String city;
    private String country;
    private String postCode;
    private Double regionId;
    private String regionName;

    private Builder() {}

    /**
     * Sets the value for {@code addressLine1}.
     *
     * @param addressLine1 Address line 1
     * @return This builder instance.
     */
    public Builder addressLine1(String addressLine1) {
      this.addressLine1 = addressLine1;
      return this;
    }

    /**
     * Sets the value for {@code addressLine2}.
     *
     * @param addressLine2 Address line 2
     * @return This builder instance.
     */
    public Builder addressLine2(String addressLine2) {
      this.addressLine2 = addressLine2;
      return this;
    }

    /**
     * Sets the value for {@code city}.
     *
     * @param city City
     * @return This builder instance.
     */
    public Builder city(String city) {
      this.city = city;
      return this;
    }

    /**
     * Sets the value for {@code country}.
     *
     * @param country Country ISO 3166-1 code
     * @return This builder instance.
     */
    public Builder country(String country) {
      this.country = country;
      return this;
    }

    /**
     * Sets the value for {@code postCode}.
     *
     * @param postCode Postal code
     * @return This builder instance.
     */
    public Builder postCode(String postCode) {
      this.postCode = postCode;
      return this;
    }

    /**
     * Sets the value for {@code regionId}.
     *
     * @param regionId Country region ID
     * @return This builder instance.
     */
    public Builder regionId(Double regionId) {
      this.regionId = regionId;
      return this;
    }

    /**
     * Sets the value for {@code regionName}.
     *
     * @param regionName Country region name
     * @return This builder instance.
     */
    public Builder regionName(String regionName) {
      this.regionName = regionName;
      return this;
    }

    /**
     * Builds an immutable DoingBusinessAsLegacyAddress instance.
     *
     * @return Immutable DoingBusinessAsLegacyAddress.
     */
    public DoingBusinessAsLegacyAddress build() {
      return new DoingBusinessAsLegacyAddress(
          addressLine1, addressLine2, city, country, postCode, regionId, regionName);
    }
  }
}
