// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

public record ElvCardAccount(
    /** ELV IBAN. */
    String iban,

    /** ELV card account number last 4 digits. */
    String last4Digits,

    /** ELV card sequence number. */
    Long sequenceNo,

    /** ELV card sort code. */
    String sortCode) {
  /**
   * Creates a builder for ElvCardAccount.
   *
   * @return Builder that constructs immutable ElvCardAccount instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for ElvCardAccount instances. */
  public static final class Builder {
    private String iban;
    private String last4Digits;
    private Long sequenceNo;
    private String sortCode;

    private Builder() {}

    /**
     * Sets the value for {@code iban}.
     *
     * @param iban ELV IBAN.
     * @return This builder instance.
     */
    public Builder iban(String iban) {
      this.iban = iban;
      return this;
    }

    /**
     * Sets the value for {@code last4Digits}.
     *
     * @param last4Digits ELV card account number last 4 digits.
     * @return This builder instance.
     */
    public Builder last4Digits(String last4Digits) {
      this.last4Digits = last4Digits;
      return this;
    }

    /**
     * Sets the value for {@code sequenceNo}.
     *
     * @param sequenceNo ELV card sequence number.
     * @return This builder instance.
     */
    public Builder sequenceNo(Long sequenceNo) {
      this.sequenceNo = sequenceNo;
      return this;
    }

    /**
     * Sets the value for {@code sortCode}.
     *
     * @param sortCode ELV card sort code.
     * @return This builder instance.
     */
    public Builder sortCode(String sortCode) {
      this.sortCode = sortCode;
      return this;
    }

    /**
     * Builds an immutable ElvCardAccount instance.
     *
     * @return Immutable ElvCardAccount.
     */
    public ElvCardAccount build() {
      return new ElvCardAccount(iban, last4Digits, sequenceNo, sortCode);
    }
  }
}
