// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** An error code specifying the exact error that occurred. */
public enum ErrorCodeNotFound {
  NOT_FOUND("not_found");

  private final String value;

  ErrorCodeNotFound(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static ErrorCodeNotFound fromValue(String value) {
    if (value == null) {
      return null;
    }
    for (ErrorCodeNotFound entry : values()) {
      if (entry.value.equals(value)) {
        return entry;
      }
    }
    throw new IllegalArgumentException("Unknown ErrorCodeNotFound value: " + value);
  }
}
