// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

public record Event(
    /** Amount of the event. */
    Float amount,

    /** Amount deducted for the event. */
    Float deductedAmount,

    /** Amount of the fee deducted for the event. */
    Float deductedFeeAmount,

    /** Amount of the fee related to the event. */
    Float feeAmount,

    /** Unique ID of the transaction event. */
    com.sumup.sdk.models.EventId id,

    /** Consecutive number of the installment. */
    Long installmentNumber,

    /** Status of the transaction event. */
    com.sumup.sdk.models.EventStatus status,

    /** Date and time of the transaction event. */
    java.time.OffsetDateTime timestamp,

    /** Unique ID of the transaction. */
    com.sumup.sdk.models.TransactionId transactionId,

    /** Type of the transaction event. */
    com.sumup.sdk.models.EventType type) {
  /**
   * Creates a builder for Event.
   *
   * @return Builder that constructs immutable Event instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for Event instances. */
  public static final class Builder {
    private Float amount;
    private Float deductedAmount;
    private Float deductedFeeAmount;
    private Float feeAmount;
    private com.sumup.sdk.models.EventId id;
    private Long installmentNumber;
    private com.sumup.sdk.models.EventStatus status;
    private java.time.OffsetDateTime timestamp;
    private com.sumup.sdk.models.TransactionId transactionId;
    private com.sumup.sdk.models.EventType type;

    private Builder() {}

    /**
     * Sets the value for {@code amount}.
     *
     * @param amount Amount of the event.
     * @return This builder instance.
     */
    public Builder amount(Float amount) {
      this.amount = amount;
      return this;
    }

    /**
     * Sets the value for {@code deductedAmount}.
     *
     * @param deductedAmount Amount deducted for the event.
     * @return This builder instance.
     */
    public Builder deductedAmount(Float deductedAmount) {
      this.deductedAmount = deductedAmount;
      return this;
    }

    /**
     * Sets the value for {@code deductedFeeAmount}.
     *
     * @param deductedFeeAmount Amount of the fee deducted for the event.
     * @return This builder instance.
     */
    public Builder deductedFeeAmount(Float deductedFeeAmount) {
      this.deductedFeeAmount = deductedFeeAmount;
      return this;
    }

    /**
     * Sets the value for {@code feeAmount}.
     *
     * @param feeAmount Amount of the fee related to the event.
     * @return This builder instance.
     */
    public Builder feeAmount(Float feeAmount) {
      this.feeAmount = feeAmount;
      return this;
    }

    /**
     * Sets the value for {@code id}.
     *
     * @param id Unique ID of the transaction event.
     * @return This builder instance.
     */
    public Builder id(com.sumup.sdk.models.EventId id) {
      this.id = id;
      return this;
    }

    /**
     * Sets the value for {@code installmentNumber}.
     *
     * @param installmentNumber Consecutive number of the installment.
     * @return This builder instance.
     */
    public Builder installmentNumber(Long installmentNumber) {
      this.installmentNumber = installmentNumber;
      return this;
    }

    /**
     * Sets the value for {@code status}.
     *
     * @param status Status of the transaction event.
     * @return This builder instance.
     */
    public Builder status(com.sumup.sdk.models.EventStatus status) {
      this.status = status;
      return this;
    }

    /**
     * Sets the value for {@code timestamp}.
     *
     * @param timestamp Date and time of the transaction event.
     * @return This builder instance.
     */
    public Builder timestamp(java.time.OffsetDateTime timestamp) {
      this.timestamp = timestamp;
      return this;
    }

    /**
     * Sets the value for {@code transactionId}.
     *
     * @param transactionId Unique ID of the transaction.
     * @return This builder instance.
     */
    public Builder transactionId(com.sumup.sdk.models.TransactionId transactionId) {
      this.transactionId = transactionId;
      return this;
    }

    /**
     * Sets the value for {@code type}.
     *
     * @param type Type of the transaction event.
     * @return This builder instance.
     */
    public Builder type(com.sumup.sdk.models.EventType type) {
      this.type = type;
      return this;
    }

    /**
     * Builds an immutable Event instance.
     *
     * @return Immutable Event.
     */
    public Event build() {
      return new Event(
          amount,
          deductedAmount,
          deductedFeeAmount,
          feeAmount,
          id,
          installmentNumber,
          status,
          timestamp,
          transactionId,
          type);
    }
  }
}
