// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Status of the transaction event. */
public enum EventStatus {
  PENDING("PENDING"),
  SCHEDULED("SCHEDULED"),
  FAILED("FAILED"),
  REFUNDED("REFUNDED"),
  SUCCESSFUL("SUCCESSFUL"),
  PAID_OUT("PAID_OUT");

  private final String value;

  EventStatus(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static EventStatus fromValue(String value) {
    if (value == null) {
      return null;
    }
    for (EventStatus entry : values()) {
      if (entry.value.equals(value)) {
        return entry;
      }
    }
    throw new IllegalArgumentException("Unknown EventStatus value: " + value);
  }
}
