// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

/** High-level payout record category. */
public final class FinancialPayoutType {
  public static final FinancialPayoutType PAYOUT = new FinancialPayoutType("PAYOUT");
  public static final FinancialPayoutType CHARGE_BACK_DEDUCTION =
      new FinancialPayoutType("CHARGE_BACK_DEDUCTION");
  public static final FinancialPayoutType REFUND_DEDUCTION =
      new FinancialPayoutType("REFUND_DEDUCTION");
  public static final FinancialPayoutType DD_RETURN_DEDUCTION =
      new FinancialPayoutType("DD_RETURN_DEDUCTION");
  public static final FinancialPayoutType BALANCE_DEDUCTION =
      new FinancialPayoutType("BALANCE_DEDUCTION");

  private final String value;

  private FinancialPayoutType(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a FinancialPayoutType for a value not yet known to this SDK version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static FinancialPayoutType of(String value) {
    return new FinancialPayoutType(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static FinancialPayoutType fromValue(String value) {
    return value == null ? null : new FinancialPayoutType(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof FinancialPayoutType that && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
