// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

public record FinancialPayoutsItem(
    Float amount,
    String currency,
    java.time.LocalDate date,
    Float fee,
    Long id,
    String reference,
    String status,
    String transactionCode,
    String type) {
  /**
   * Creates a builder for FinancialPayoutsItem.
   *
   * @return Builder that constructs immutable FinancialPayoutsItem instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for FinancialPayoutsItem instances. */
  public static final class Builder {
    private Float amount;
    private String currency;
    private java.time.LocalDate date;
    private Float fee;
    private Long id;
    private String reference;
    private String status;
    private String transactionCode;
    private String type;

    private Builder() {}

    /**
     * Sets the value for {@code amount}.
     *
     * @param amount Value for the amount field.
     * @return This builder instance.
     */
    public Builder amount(Float amount) {
      this.amount = amount;
      return this;
    }

    /**
     * Sets the value for {@code currency}.
     *
     * @param currency Value for the currency field.
     * @return This builder instance.
     */
    public Builder currency(String currency) {
      this.currency = currency;
      return this;
    }

    /**
     * Sets the value for {@code date}.
     *
     * @param date Value for the date field.
     * @return This builder instance.
     */
    public Builder date(java.time.LocalDate date) {
      this.date = date;
      return this;
    }

    /**
     * Sets the value for {@code fee}.
     *
     * @param fee Value for the fee field.
     * @return This builder instance.
     */
    public Builder fee(Float fee) {
      this.fee = fee;
      return this;
    }

    /**
     * Sets the value for {@code id}.
     *
     * @param id Value for the id field.
     * @return This builder instance.
     */
    public Builder id(Long id) {
      this.id = id;
      return this;
    }

    /**
     * Sets the value for {@code reference}.
     *
     * @param reference Value for the reference field.
     * @return This builder instance.
     */
    public Builder reference(String reference) {
      this.reference = reference;
      return this;
    }

    /**
     * Sets the value for {@code status}.
     *
     * @param status Value for the status field.
     * @return This builder instance.
     */
    public Builder status(String status) {
      this.status = status;
      return this;
    }

    /**
     * Sets the value for {@code transactionCode}.
     *
     * @param transactionCode Value for the transactionCode field.
     * @return This builder instance.
     */
    public Builder transactionCode(String transactionCode) {
      this.transactionCode = transactionCode;
      return this;
    }

    /**
     * Sets the value for {@code type}.
     *
     * @param type Value for the type field.
     * @return This builder instance.
     */
    public Builder type(String type) {
      this.type = type;
      return this;
    }

    /**
     * Builds an immutable FinancialPayoutsItem instance.
     *
     * @return Immutable FinancialPayoutsItem.
     */
    public FinancialPayoutsItem build() {
      return new FinancialPayoutsItem(
          amount, currency, date, fee, id, reference, status, transactionCode, type);
    }
  }
}
