// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum FinancialPayoutsItemType {
  PAYOUT("PAYOUT"),
  CHARGE_BACK_DEDUCTION("CHARGE_BACK_DEDUCTION"),
  REFUND_DEDUCTION("REFUND_DEDUCTION"),
  DD_RETURN_DEDUCTION("DD_RETURN_DEDUCTION"),
  BALANCE_DEDUCTION("BALANCE_DEDUCTION");

  private final String value;

  FinancialPayoutsItemType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static FinancialPayoutsItemType fromValue(String value) {
    if (value == null) {
      return null;
    }
    for (FinancialPayoutsItemType entry : values()) {
      if (entry.value.equals(value)) {
        return entry;
      }
    }
    throw new IllegalArgumentException("Unknown FinancialPayoutsItemType value: " + value);
  }
}
