// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

/** Merchant-facing outcome of the payout record. */
public final class FinancialPayoutStatus {
  public static final FinancialPayoutStatus SUCCESSFUL = new FinancialPayoutStatus("SUCCESSFUL");
  public static final FinancialPayoutStatus FAILED = new FinancialPayoutStatus("FAILED");

  private final String value;

  private FinancialPayoutStatus(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a FinancialPayoutStatus for a value not yet known to this SDK version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static FinancialPayoutStatus of(String value) {
    return new FinancialPayoutStatus(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static FinancialPayoutStatus fromValue(String value) {
    return value == null ? null : new FinancialPayoutStatus(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof FinancialPayoutStatus that && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
