// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

public record GatewayTimeoutErrors(
    /** Fuller message giving context to error */
    String detail) {
  /**
   * Creates a builder for GatewayTimeoutErrors.
   *
   * @return Builder that constructs immutable GatewayTimeoutErrors instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for GatewayTimeoutErrors instances. */
  public static final class Builder {
    private String detail;

    private Builder() {}

    /**
     * Sets the value for {@code detail}.
     *
     * @param detail Fuller message giving context to error
     * @return This builder instance.
     */
    public Builder detail(String detail) {
      this.detail = detail;
      return this;
    }

    /**
     * Builds an immutable GatewayTimeoutErrors instance.
     *
     * @return Immutable GatewayTimeoutErrors.
     */
    public GatewayTimeoutErrors build() {
      return new GatewayTimeoutErrors(Objects.requireNonNull(detail, "detail"));
    }
  }
}
