// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

/** 504 Gateway Timeout */
public record GatewayTimeout(com.sumup.sdk.models.GatewayTimeoutErrors errors) {
  /**
   * Creates a builder for GatewayTimeout.
   *
   * @return Builder that constructs immutable GatewayTimeout instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for GatewayTimeout instances. */
  public static final class Builder {
    private com.sumup.sdk.models.GatewayTimeoutErrors errors;

    private Builder() {}

    /**
     * Sets the value for {@code errors}.
     *
     * @param errors Value for the errors field.
     * @return This builder instance.
     */
    public Builder errors(com.sumup.sdk.models.GatewayTimeoutErrors errors) {
      this.errors = errors;
      return this;
    }

    /**
     * Builds an immutable GatewayTimeout instance.
     *
     * @return Immutable GatewayTimeout.
     */
    public GatewayTimeout build() {
      return new GatewayTimeout(Objects.requireNonNull(errors, "errors"));
    }
  }
}
