// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

public record GetPaymentMethodsResponseAvailablePaymentMethodsItem(
    /** Unique identifier of the payment method. */
    String id) {
  /**
   * Creates a builder for GetPaymentMethodsResponseAvailablePaymentMethodsItem.
   *
   * @return Builder that constructs immutable GetPaymentMethodsResponseAvailablePaymentMethodsItem
   *     instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for GetPaymentMethodsResponseAvailablePaymentMethodsItem instances. */
  public static final class Builder {
    private String id;

    private Builder() {}

    /**
     * Sets the value for {@code id}.
     *
     * @param id Unique identifier of the payment method.
     * @return This builder instance.
     */
    public Builder id(String id) {
      this.id = id;
      return this;
    }

    /**
     * Builds an immutable GetPaymentMethodsResponseAvailablePaymentMethodsItem instance.
     *
     * @return Immutable GetPaymentMethodsResponseAvailablePaymentMethodsItem.
     */
    public GetPaymentMethodsResponseAvailablePaymentMethodsItem build() {
      return new GetPaymentMethodsResponseAvailablePaymentMethodsItem(
          Objects.requireNonNull(id, "id"));
    }
  }
}
