// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

public record GetReaderCheckoutResponse(com.sumup.sdk.models.GetReaderCheckoutResponseData data) {
  /**
   * Creates a builder for GetReaderCheckoutResponse.
   *
   * @return Builder that constructs immutable GetReaderCheckoutResponse instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for GetReaderCheckoutResponse instances. */
  public static final class Builder {
    private com.sumup.sdk.models.GetReaderCheckoutResponseData data;

    private Builder() {}

    /**
     * Sets the value for {@code data}.
     *
     * @param data Value for the data field.
     * @return This builder instance.
     */
    public Builder data(com.sumup.sdk.models.GetReaderCheckoutResponseData data) {
      this.data = data;
      return this;
    }

    /**
     * Builds an immutable GetReaderCheckoutResponse instance.
     *
     * @return Immutable GetReaderCheckoutResponse.
     */
    public GetReaderCheckoutResponse build() {
      return new GetReaderCheckoutResponse(Objects.requireNonNull(data, "data"));
    }
  }
}
