// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

/** Type of the payment. Required for some countries */
public final class GetReaderCheckoutResponseDataPaymentType {
  public static final GetReaderCheckoutResponseDataPaymentType CARD =
      new GetReaderCheckoutResponseDataPaymentType("card");
  public static final GetReaderCheckoutResponseDataPaymentType PIX =
      new GetReaderCheckoutResponseDataPaymentType("pix");

  private final String value;

  private GetReaderCheckoutResponseDataPaymentType(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a GetReaderCheckoutResponseDataPaymentType for a value not yet known to this SDK
   * version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static GetReaderCheckoutResponseDataPaymentType of(String value) {
    return new GetReaderCheckoutResponseDataPaymentType(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static GetReaderCheckoutResponseDataPaymentType fromValue(String value) {
    return value == null ? null : new GetReaderCheckoutResponseDataPaymentType(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof GetReaderCheckoutResponseDataPaymentType that
            && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
