// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

/** Current status of the checkout */
public final class GetReaderCheckoutResponseDataStatus {
  public static final GetReaderCheckoutResponseDataStatus PENDING =
      new GetReaderCheckoutResponseDataStatus("pending");
  public static final GetReaderCheckoutResponseDataStatus SUCCESSFUL =
      new GetReaderCheckoutResponseDataStatus("successful");
  public static final GetReaderCheckoutResponseDataStatus FAILED =
      new GetReaderCheckoutResponseDataStatus("failed");
  public static final GetReaderCheckoutResponseDataStatus CANCELLED =
      new GetReaderCheckoutResponseDataStatus("cancelled");

  private final String value;

  private GetReaderCheckoutResponseDataStatus(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a GetReaderCheckoutResponseDataStatus for a value not yet known to this SDK version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static GetReaderCheckoutResponseDataStatus of(String value) {
    return new GetReaderCheckoutResponseDataStatus(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static GetReaderCheckoutResponseDataStatus fromValue(String value) {
    return value == null ? null : new GetReaderCheckoutResponseDataStatus(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof GetReaderCheckoutResponseDataStatus that
            && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
