// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum IncludeItem {
  SETTINGS("settings"),
  DOING_BUSINESS_AS("doing_business_as"),
  BANK_ACCOUNTS("bank_accounts"),
  APP_SETTINGS("app_settings"),
  COUNTRY_DETAILS("country_details");

  private final String value;

  IncludeItem(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static IncludeItem fromValue(String value) {
    if (value == null) {
      return null;
    }
    for (IncludeItem entry : values()) {
      if (entry.value.equals(value)) {
        return entry;
      }
    }
    throw new IllegalArgumentException("Unknown IncludeItem value: " + value);
  }
}
