// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

/** 500 Internal Server Error */
public record InternalServerError(com.sumup.sdk.models.InternalServerErrorErrors errors) {
  /**
   * Creates a builder for InternalServerError.
   *
   * @return Builder that constructs immutable InternalServerError instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for InternalServerError instances. */
  public static final class Builder {
    private com.sumup.sdk.models.InternalServerErrorErrors errors;

    private Builder() {}

    /**
     * Sets the value for {@code errors}.
     *
     * @param errors Value for the errors field.
     * @return This builder instance.
     */
    public Builder errors(com.sumup.sdk.models.InternalServerErrorErrors errors) {
      this.errors = errors;
      return this;
    }

    /**
     * Builds an immutable InternalServerError instance.
     *
     * @return Immutable InternalServerError.
     */
    public InternalServerError build() {
      return new InternalServerError(Objects.requireNonNull(errors, "errors"));
    }
  }
}
