// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

/** Pending invitation for membership. */
public record Invite(
    /** Email address of the invited user. */
    String email, java.time.OffsetDateTime expiresAt) {

  /**
   * Creates a builder for Invite.
   *
   * @return Builder that constructs immutable Invite instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for Invite instances. */
  public static final class Builder {
    private String email;
    private java.time.OffsetDateTime expiresAt;

    private Builder() {}

    /**
     * Sets the value for {@code email}.
     *
     * @param email Email address of the invited user.
     * @return This builder instance.
     */
    public Builder email(String email) {
      this.email = email;
      return this;
    }

    /**
     * Sets the value for {@code expiresAt}.
     *
     * @param expiresAt Value for the expiresAt field.
     * @return This builder instance.
     */
    public Builder expiresAt(java.time.OffsetDateTime expiresAt) {
      this.expiresAt = expiresAt;
      return this;
    }

    /**
     * Builds an immutable Invite instance.
     *
     * @return Immutable Invite.
     */
    public Invite build() {
      return new Invite(
          Objects.requireNonNull(email, "email"), Objects.requireNonNull(expiresAt, "expiresAt"));
    }
  }
}
