// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/**
 * Latitude value from the coordinates of the payment location (as received from the payment
 * terminal reader).
 */
public record Lat(Float value) {}
