// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/**
 * The unique legal type reference as defined in the country SDK. We do not rely on IDs as used by
 * other services. Consumers of this API are expected to use the country SDK to map to any other
 * IDs, translation keys, or descriptions.
 */
public record LegalType(String value) {}
