// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

public record LinkRefund(com.sumup.sdk.models.Link value) {
  /**
   * Creates a builder for LinkRefund.
   *
   * @return Builder that constructs immutable LinkRefund instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for LinkRefund instances. */
  public static final class Builder {
    private com.sumup.sdk.models.Link value;

    private Builder() {}

    /**
     * Sets the value for {@code value}.
     *
     * @param value Value for the value field.
     * @return This builder instance.
     */
    public Builder value(com.sumup.sdk.models.Link value) {
      this.value = value;
      return this;
    }

    /**
     * Builds an immutable LinkRefund instance.
     *
     * @return Immutable LinkRefund.
     */
    public LinkRefund build() {
      return new LinkRefund(value);
    }
  }
}
