// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

public record ListMerchantMembersResponse(
    java.util.List<com.sumup.sdk.models.Member> items, Long totalCount) {

  /**
   * Creates a builder for ListMerchantMembersResponse.
   *
   * @return Builder that constructs immutable ListMerchantMembersResponse instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for ListMerchantMembersResponse instances. */
  public static final class Builder {
    private java.util.List<com.sumup.sdk.models.Member> items;
    private Long totalCount;

    private Builder() {}

    /**
     * Sets the value for {@code items}.
     *
     * @param items Value for the items field.
     * @return This builder instance.
     */
    public Builder items(java.util.List<com.sumup.sdk.models.Member> items) {
      this.items = items;
      return this;
    }

    /**
     * Sets the value for {@code totalCount}.
     *
     * @param totalCount Value for the totalCount field.
     * @return This builder instance.
     */
    public Builder totalCount(Long totalCount) {
      this.totalCount = totalCount;
      return this;
    }

    /**
     * Builds an immutable ListMerchantMembersResponse instance.
     *
     * @return Immutable ListMerchantMembersResponse.
     */
    public ListMerchantMembersResponse build() {
      return new ListMerchantMembersResponse(Objects.requireNonNull(items, "items"), totalCount);
    }
  }
}
