// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

public record ListTransactionsV21Response(
    /** Transactions in the current result page. */
    java.util.List<com.sumup.sdk.models.TransactionHistory> items,

    /** Pagination links for navigating the transaction history. */
    java.util.List<com.sumup.sdk.models.TransactionsHistoryLink> links) {
  /**
   * Creates a builder for ListTransactionsV21Response.
   *
   * @return Builder that constructs immutable ListTransactionsV21Response instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for ListTransactionsV21Response instances. */
  public static final class Builder {
    private java.util.List<com.sumup.sdk.models.TransactionHistory> items;
    private java.util.List<com.sumup.sdk.models.TransactionsHistoryLink> links;

    private Builder() {}

    /**
     * Sets the value for {@code items}.
     *
     * @param items Transactions in the current result page.
     * @return This builder instance.
     */
    public Builder items(java.util.List<com.sumup.sdk.models.TransactionHistory> items) {
      this.items = items;
      return this;
    }

    /**
     * Sets the value for {@code links}.
     *
     * @param links Pagination links for navigating the transaction history.
     * @return This builder instance.
     */
    public Builder links(java.util.List<com.sumup.sdk.models.TransactionsHistoryLink> links) {
      this.links = links;
      return this;
    }

    /**
     * Builds an immutable ListTransactionsV21Response instance.
     *
     * @return Immutable ListTransactionsV21Response.
     */
    public ListTransactionsV21Response build() {
      return new ListTransactionsV21Response(items, links);
    }
  }
}
