// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

public final class ListTransactionsV21Order {
  public static final ListTransactionsV21Order ASCENDING =
      new ListTransactionsV21Order("ascending");
  public static final ListTransactionsV21Order DESCENDING =
      new ListTransactionsV21Order("descending");

  private final String value;

  private ListTransactionsV21Order(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a ListTransactionsV21Order for a value not yet known to this SDK version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static ListTransactionsV21Order of(String value) {
    return new ListTransactionsV21Order(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static ListTransactionsV21Order fromValue(String value) {
    return value == null ? null : new ListTransactionsV21Order(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof ListTransactionsV21Order that && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
