// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

public final class ListPayoutsFormat {
  public static final ListPayoutsFormat JSON = new ListPayoutsFormat("json");
  public static final ListPayoutsFormat CSV = new ListPayoutsFormat("csv");

  private final String value;

  private ListPayoutsFormat(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a ListPayoutsFormat for a value not yet known to this SDK version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static ListPayoutsFormat of(String value) {
    return new ListPayoutsFormat(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static ListPayoutsFormat fromValue(String value) {
    return value == null ? null : new ListPayoutsFormat(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof ListPayoutsFormat that && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
