// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

public final class ListTransactionsStatusesItem {
  public static final ListTransactionsStatusesItem SUCCESSFUL =
      new ListTransactionsStatusesItem("SUCCESSFUL");
  public static final ListTransactionsStatusesItem CANCELLED =
      new ListTransactionsStatusesItem("CANCELLED");
  public static final ListTransactionsStatusesItem FAILED =
      new ListTransactionsStatusesItem("FAILED");
  public static final ListTransactionsStatusesItem REFUNDED =
      new ListTransactionsStatusesItem("REFUNDED");
  public static final ListTransactionsStatusesItem CHARGE_BACK =
      new ListTransactionsStatusesItem("CHARGE_BACK");

  private final String value;

  private ListTransactionsStatusesItem(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a ListTransactionsStatusesItem for a value not yet known to this SDK version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static ListTransactionsStatusesItem of(String value) {
    return new ListTransactionsStatusesItem(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static ListTransactionsStatusesItem fromValue(String value) {
    return value == null ? null : new ListTransactionsStatusesItem(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof ListTransactionsStatusesItem that && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
