// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

public final class ListTransactionsOrder {
  public static final ListTransactionsOrder ASCENDING = new ListTransactionsOrder("ascending");
  public static final ListTransactionsOrder DESCENDING = new ListTransactionsOrder("descending");

  private final String value;

  private ListTransactionsOrder(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a ListTransactionsOrder for a value not yet known to this SDK version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static ListTransactionsOrder of(String value) {
    return new ListTransactionsOrder(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static ListTransactionsOrder fromValue(String value) {
    return value == null ? null : new ListTransactionsOrder(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof ListTransactionsOrder that && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
