// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

public final class ListTransactionsTypesItem {
  public static final ListTransactionsTypesItem PAYMENT = new ListTransactionsTypesItem("PAYMENT");
  public static final ListTransactionsTypesItem REFUND = new ListTransactionsTypesItem("REFUND");
  public static final ListTransactionsTypesItem CHARGE_BACK =
      new ListTransactionsTypesItem("CHARGE_BACK");

  private final String value;

  private ListTransactionsTypesItem(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a ListTransactionsTypesItem for a value not yet known to this SDK version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static ListTransactionsTypesItem of(String value) {
    return new ListTransactionsTypesItem(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static ListTransactionsTypesItem fromValue(String value) {
    return value == null ? null : new ListTransactionsTypesItem(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof ListTransactionsTypesItem that && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
