// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

public final class ListTransactionsV21StatusesItem {
  public static final ListTransactionsV21StatusesItem SUCCESSFUL =
      new ListTransactionsV21StatusesItem("SUCCESSFUL");
  public static final ListTransactionsV21StatusesItem CANCELLED =
      new ListTransactionsV21StatusesItem("CANCELLED");
  public static final ListTransactionsV21StatusesItem FAILED =
      new ListTransactionsV21StatusesItem("FAILED");
  public static final ListTransactionsV21StatusesItem REFUNDED =
      new ListTransactionsV21StatusesItem("REFUNDED");
  public static final ListTransactionsV21StatusesItem CHARGE_BACK =
      new ListTransactionsV21StatusesItem("CHARGE_BACK");

  private final String value;

  private ListTransactionsV21StatusesItem(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a ListTransactionsV21StatusesItem for a value not yet known to this SDK version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static ListTransactionsV21StatusesItem of(String value) {
    return new ListTransactionsV21StatusesItem(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static ListTransactionsV21StatusesItem fromValue(String value) {
    return value == null ? null : new ListTransactionsV21StatusesItem(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof ListTransactionsV21StatusesItem that && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
