// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

public final class ListPayoutsV1Order {
  public static final ListPayoutsV1Order ASC = new ListPayoutsV1Order("asc");
  public static final ListPayoutsV1Order DESC = new ListPayoutsV1Order("desc");

  private final String value;

  private ListPayoutsV1Order(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a ListPayoutsV1Order for a value not yet known to this SDK version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static ListPayoutsV1Order of(String value) {
    return new ListPayoutsV1Order(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static ListPayoutsV1Order fromValue(String value) {
    return value == null ? null : new ListPayoutsV1Order(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof ListPayoutsV1Order that && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
