// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

public record ListTransactionsResponse(
    java.util.List<com.sumup.sdk.models.TransactionHistory> items,
    java.util.List<com.sumup.sdk.models.TransactionsHistoryLink> links) {
  /**
   * Creates a builder for ListTransactionsResponse.
   *
   * @return Builder that constructs immutable ListTransactionsResponse instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for ListTransactionsResponse instances. */
  public static final class Builder {
    private java.util.List<com.sumup.sdk.models.TransactionHistory> items;
    private java.util.List<com.sumup.sdk.models.TransactionsHistoryLink> links;

    private Builder() {}

    /**
     * Sets the value for {@code items}.
     *
     * @param items Value for the items field.
     * @return This builder instance.
     */
    public Builder items(java.util.List<com.sumup.sdk.models.TransactionHistory> items) {
      this.items = items;
      return this;
    }

    /**
     * Sets the value for {@code links}.
     *
     * @param links Value for the links field.
     * @return This builder instance.
     */
    public Builder links(java.util.List<com.sumup.sdk.models.TransactionsHistoryLink> links) {
      this.links = links;
      return this;
    }

    /**
     * Builds an immutable ListTransactionsResponse instance.
     *
     * @return Immutable ListTransactionsResponse.
     */
    public ListTransactionsResponse build() {
      return new ListTransactionsResponse(items, links);
    }
  }
}
