// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Indicates the mandate type */
public enum MandatePayloadType {
  RECURRENT("recurrent");

  private final String value;

  MandatePayloadType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static MandatePayloadType fromValue(String value) {
    if (value == null) {
      return null;
    }
    for (MandatePayloadType entry : values()) {
      if (entry.value.equals(value)) {
        return entry;
      }
    }
    throw new IllegalArgumentException("Unknown MandatePayloadType value: " + value);
  }
}
