// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Current lifecycle status of the mandate. */
public enum MandateResponseStatus {
  ACTIVE("active"),
  INACTIVE("inactive");

  private final String value;

  MandateResponseStatus(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static MandateResponseStatus fromValue(String value) {
    if (value == null) {
      return null;
    }
    for (MandateResponseStatus entry : values()) {
      if (entry.value.equals(value)) {
        return entry;
      }
    }
    throw new IllegalArgumentException("Unknown MandateResponseStatus value: " + value);
  }
}
