// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

/**
 * Mandate details used when a checkout should create a reusable card token for future recurring or
 * merchant-initiated payments.
 */
public record MandatePayload(
    /** Type of mandate to create for the saved payment instrument. */
    com.sumup.sdk.models.MandatePayloadType type,

    /** Browser or client user agent observed when consent was collected. */
    String userAgent,

    /** IP address of the payer when the mandate was accepted. */
    String userIp) {
  /**
   * Creates a builder for MandatePayload.
   *
   * @return Builder that constructs immutable MandatePayload instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for MandatePayload instances. */
  public static final class Builder {
    private com.sumup.sdk.models.MandatePayloadType type;
    private String userAgent;
    private String userIp;

    private Builder() {}

    /**
     * Sets the value for {@code type}.
     *
     * @param type Type of mandate to create for the saved payment instrument.
     * @return This builder instance.
     */
    public Builder type(com.sumup.sdk.models.MandatePayloadType type) {
      this.type = type;
      return this;
    }

    /**
     * Sets the value for {@code userAgent}.
     *
     * @param userAgent Browser or client user agent observed when consent was collected.
     * @return This builder instance.
     */
    public Builder userAgent(String userAgent) {
      this.userAgent = userAgent;
      return this;
    }

    /**
     * Sets the value for {@code userIp}.
     *
     * @param userIp IP address of the payer when the mandate was accepted.
     * @return This builder instance.
     */
    public Builder userIp(String userIp) {
      this.userIp = userIp;
      return this;
    }

    /**
     * Builds an immutable MandatePayload instance.
     *
     * @return Immutable MandatePayload.
     */
    public MandatePayload build() {
      return new MandatePayload(
          Objects.requireNonNull(type, "type"),
          Objects.requireNonNull(userAgent, "userAgent"),
          userIp);
    }
  }
}
