// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** Created mandate */
public record MandateResponse(
    /** Merchant code which has the mandate */
    String merchantCode,

    /** Mandate status */
    String status,

    /** Indicates the mandate type */
    String type) {
  /**
   * Creates a builder for MandateResponse.
   *
   * @return Builder that constructs immutable MandateResponse instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for MandateResponse instances. */
  public static final class Builder {
    private String merchantCode;
    private String status;
    private String type;

    private Builder() {}

    /**
     * Sets the value for {@code merchantCode}.
     *
     * @param merchantCode Merchant code which has the mandate
     * @return This builder instance.
     */
    public Builder merchantCode(String merchantCode) {
      this.merchantCode = merchantCode;
      return this;
    }

    /**
     * Sets the value for {@code status}.
     *
     * @param status Mandate status
     * @return This builder instance.
     */
    public Builder status(String status) {
      this.status = status;
      return this;
    }

    /**
     * Sets the value for {@code type}.
     *
     * @param type Indicates the mandate type
     * @return This builder instance.
     */
    public Builder type(String type) {
      this.type = type;
      return this;
    }

    /**
     * Builds an immutable MandateResponse instance.
     *
     * @return Immutable MandateResponse.
     */
    public MandateResponse build() {
      return new MandateResponse(merchantCode, status, type);
    }
  }
}
