// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

/**
 * A member is user within specific resource identified by resource id, resource type, and
 * associated roles.
 */
public record Member(
    /** Object attributes that are modifiable only by SumUp applications. */
    com.sumup.sdk.models.Attributes attributes,

    /** The timestamp of when the member was created. */
    java.time.OffsetDateTime createdAt,

    /** ID of the member. */
    String id,

    /** Pending invitation for membership. */
    com.sumup.sdk.models.Invite invite,

    /**
     * Set of user-defined key-value pairs attached to the object. Partial updates are not
     * supported. When updating, always submit whole metadata. Maximum of 64 parameters are allowed
     * in the object.
     */
    com.sumup.sdk.models.Metadata metadata,

    /** User's permissions. */
    java.util.List<String> permissions,

    /** User's roles. */
    java.util.List<String> roles,

    /** The status of the membership. */
    com.sumup.sdk.models.MembershipStatus status,

    /** The timestamp of when the member was last updated. */
    java.time.OffsetDateTime updatedAt,

    /** Information about the user associated with the membership. */
    com.sumup.sdk.models.MembershipUser user) {
  /**
   * Creates a builder for Member.
   *
   * @return Builder that constructs immutable Member instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for Member instances. */
  public static final class Builder {
    private com.sumup.sdk.models.Attributes attributes;
    private java.time.OffsetDateTime createdAt;
    private String id;
    private com.sumup.sdk.models.Invite invite;
    private com.sumup.sdk.models.Metadata metadata;
    private java.util.List<String> permissions;
    private java.util.List<String> roles;
    private com.sumup.sdk.models.MembershipStatus status;
    private java.time.OffsetDateTime updatedAt;
    private com.sumup.sdk.models.MembershipUser user;

    private Builder() {}

    /**
     * Sets the value for {@code attributes}.
     *
     * @param attributes Object attributes that are modifiable only by SumUp applications.
     * @return This builder instance.
     */
    public Builder attributes(com.sumup.sdk.models.Attributes attributes) {
      this.attributes = attributes;
      return this;
    }

    /**
     * Sets the value for {@code createdAt}.
     *
     * @param createdAt The timestamp of when the member was created.
     * @return This builder instance.
     */
    public Builder createdAt(java.time.OffsetDateTime createdAt) {
      this.createdAt = createdAt;
      return this;
    }

    /**
     * Sets the value for {@code id}.
     *
     * @param id ID of the member.
     * @return This builder instance.
     */
    public Builder id(String id) {
      this.id = id;
      return this;
    }

    /**
     * Sets the value for {@code invite}.
     *
     * @param invite Pending invitation for membership.
     * @return This builder instance.
     */
    public Builder invite(com.sumup.sdk.models.Invite invite) {
      this.invite = invite;
      return this;
    }

    /**
     * Sets the value for {@code metadata}.
     *
     * @param metadata Set of user-defined key-value pairs attached to the object. Partial updates
     *     are not supported. When updating, always submit whole metadata. Maximum of 64 parameters
     *     are allowed in the object.
     * @return This builder instance.
     */
    public Builder metadata(com.sumup.sdk.models.Metadata metadata) {
      this.metadata = metadata;
      return this;
    }

    /**
     * Sets the value for {@code permissions}.
     *
     * @param permissions User's permissions.
     * @return This builder instance.
     */
    public Builder permissions(java.util.List<String> permissions) {
      this.permissions = permissions;
      return this;
    }

    /**
     * Sets the value for {@code roles}.
     *
     * @param roles User's roles.
     * @return This builder instance.
     */
    public Builder roles(java.util.List<String> roles) {
      this.roles = roles;
      return this;
    }

    /**
     * Sets the value for {@code status}.
     *
     * @param status The status of the membership.
     * @return This builder instance.
     */
    public Builder status(com.sumup.sdk.models.MembershipStatus status) {
      this.status = status;
      return this;
    }

    /**
     * Sets the value for {@code updatedAt}.
     *
     * @param updatedAt The timestamp of when the member was last updated.
     * @return This builder instance.
     */
    public Builder updatedAt(java.time.OffsetDateTime updatedAt) {
      this.updatedAt = updatedAt;
      return this;
    }

    /**
     * Sets the value for {@code user}.
     *
     * @param user Information about the user associated with the membership.
     * @return This builder instance.
     */
    public Builder user(com.sumup.sdk.models.MembershipUser user) {
      this.user = user;
      return this;
    }

    /**
     * Builds an immutable Member instance.
     *
     * @return Immutable Member.
     */
    public Member build() {
      return new Member(
          attributes,
          Objects.requireNonNull(createdAt, "createdAt"),
          Objects.requireNonNull(id, "id"),
          invite,
          metadata,
          Objects.requireNonNull(permissions, "permissions"),
          Objects.requireNonNull(roles, "roles"),
          Objects.requireNonNull(status, "status"),
          Objects.requireNonNull(updatedAt, "updatedAt"),
          user);
    }
  }
}
