// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** Account's merchant profile */
public record MerchantProfileLegacy(
    /** Details of the registered address. */
    com.sumup.sdk.models.AddressWithDetails address,
    java.util.List<com.sumup.sdk.models.BankAccount> bankAccounts,

    /** Business owners information. */
    com.sumup.sdk.models.BusinessOwners businessOwners,

    /** Company name */
    String companyName,

    /** Company registration number */
    String companyRegistrationNumber,

    /**
     * Merchant country code formatted according to [ISO3166-1
     * alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) &#40;for internal usage only&#41;
     */
    String country,

    /** Doing Business As information */
    com.sumup.sdk.models.DoingBusinessAsLegacy doingBusinessAs,

    /** True if the merchant is extdev */
    Boolean extdev,

    /** Id of the legal type of the merchant profile */
    com.sumup.sdk.models.LegalTypeLegacy legalType,

    /** Merchant locale &#40;for internal usage only&#41; */
    String locale,

    /** Merchant category code */
    String merchantCategoryCode,

    /** Unique identifying code of the merchant profile */
    String merchantCode,

    /** Mobile phone number */
    String mobilePhone,

    /** Nature and purpose of the business */
    String natureAndPurpose,

    /** True if the payout zone of this merchant is migrated */
    Boolean payoutZoneMigrated,

    /** Permanent certificate access code &#40;Portugal&#41; */
    String permanentCertificateAccessCode,

    /** Merchant settings &#40;like \"payout_type\", \"payout_period\"&#41; */
    com.sumup.sdk.models.MerchantSettings settings,

    /** Vat ID */
    String vatId,

    /** Merchant VAT rates */
    com.sumup.sdk.models.VatRates vatRates,

    /** Website */
    String website) {
  /**
   * Creates a builder for MerchantProfileLegacy.
   *
   * @return Builder that constructs immutable MerchantProfileLegacy instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for MerchantProfileLegacy instances. */
  public static final class Builder {
    private com.sumup.sdk.models.AddressWithDetails address;
    private java.util.List<com.sumup.sdk.models.BankAccount> bankAccounts;
    private com.sumup.sdk.models.BusinessOwners businessOwners;
    private String companyName;
    private String companyRegistrationNumber;
    private String country;
    private com.sumup.sdk.models.DoingBusinessAsLegacy doingBusinessAs;
    private Boolean extdev;
    private com.sumup.sdk.models.LegalTypeLegacy legalType;
    private String locale;
    private String merchantCategoryCode;
    private String merchantCode;
    private String mobilePhone;
    private String natureAndPurpose;
    private Boolean payoutZoneMigrated;
    private String permanentCertificateAccessCode;
    private com.sumup.sdk.models.MerchantSettings settings;
    private String vatId;
    private com.sumup.sdk.models.VatRates vatRates;
    private String website;

    private Builder() {}

    /**
     * Sets the value for {@code address}.
     *
     * @param address Details of the registered address.
     * @return This builder instance.
     */
    public Builder address(com.sumup.sdk.models.AddressWithDetails address) {
      this.address = address;
      return this;
    }

    /**
     * Sets the value for {@code bankAccounts}.
     *
     * @param bankAccounts Value for the bankAccounts field.
     * @return This builder instance.
     */
    public Builder bankAccounts(java.util.List<com.sumup.sdk.models.BankAccount> bankAccounts) {
      this.bankAccounts = bankAccounts;
      return this;
    }

    /**
     * Sets the value for {@code businessOwners}.
     *
     * @param businessOwners Business owners information.
     * @return This builder instance.
     */
    public Builder businessOwners(com.sumup.sdk.models.BusinessOwners businessOwners) {
      this.businessOwners = businessOwners;
      return this;
    }

    /**
     * Sets the value for {@code companyName}.
     *
     * @param companyName Company name
     * @return This builder instance.
     */
    public Builder companyName(String companyName) {
      this.companyName = companyName;
      return this;
    }

    /**
     * Sets the value for {@code companyRegistrationNumber}.
     *
     * @param companyRegistrationNumber Company registration number
     * @return This builder instance.
     */
    public Builder companyRegistrationNumber(String companyRegistrationNumber) {
      this.companyRegistrationNumber = companyRegistrationNumber;
      return this;
    }

    /**
     * Sets the value for {@code country}.
     *
     * @param country Merchant country code formatted according to [ISO3166-1
     *     alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) &#40;for internal usage
     *     only&#41;
     * @return This builder instance.
     */
    public Builder country(String country) {
      this.country = country;
      return this;
    }

    /**
     * Sets the value for {@code doingBusinessAs}.
     *
     * @param doingBusinessAs Doing Business As information
     * @return This builder instance.
     */
    public Builder doingBusinessAs(com.sumup.sdk.models.DoingBusinessAsLegacy doingBusinessAs) {
      this.doingBusinessAs = doingBusinessAs;
      return this;
    }

    /**
     * Sets the value for {@code extdev}.
     *
     * @param extdev True if the merchant is extdev
     * @return This builder instance.
     */
    public Builder extdev(Boolean extdev) {
      this.extdev = extdev;
      return this;
    }

    /**
     * Sets the value for {@code legalType}.
     *
     * @param legalType Id of the legal type of the merchant profile
     * @return This builder instance.
     */
    public Builder legalType(com.sumup.sdk.models.LegalTypeLegacy legalType) {
      this.legalType = legalType;
      return this;
    }

    /**
     * Sets the value for {@code locale}.
     *
     * @param locale Merchant locale &#40;for internal usage only&#41;
     * @return This builder instance.
     */
    public Builder locale(String locale) {
      this.locale = locale;
      return this;
    }

    /**
     * Sets the value for {@code merchantCategoryCode}.
     *
     * @param merchantCategoryCode Merchant category code
     * @return This builder instance.
     */
    public Builder merchantCategoryCode(String merchantCategoryCode) {
      this.merchantCategoryCode = merchantCategoryCode;
      return this;
    }

    /**
     * Sets the value for {@code merchantCode}.
     *
     * @param merchantCode Unique identifying code of the merchant profile
     * @return This builder instance.
     */
    public Builder merchantCode(String merchantCode) {
      this.merchantCode = merchantCode;
      return this;
    }

    /**
     * Sets the value for {@code mobilePhone}.
     *
     * @param mobilePhone Mobile phone number
     * @return This builder instance.
     */
    public Builder mobilePhone(String mobilePhone) {
      this.mobilePhone = mobilePhone;
      return this;
    }

    /**
     * Sets the value for {@code natureAndPurpose}.
     *
     * @param natureAndPurpose Nature and purpose of the business
     * @return This builder instance.
     */
    public Builder natureAndPurpose(String natureAndPurpose) {
      this.natureAndPurpose = natureAndPurpose;
      return this;
    }

    /**
     * Sets the value for {@code payoutZoneMigrated}.
     *
     * @param payoutZoneMigrated True if the payout zone of this merchant is migrated
     * @return This builder instance.
     */
    public Builder payoutZoneMigrated(Boolean payoutZoneMigrated) {
      this.payoutZoneMigrated = payoutZoneMigrated;
      return this;
    }

    /**
     * Sets the value for {@code permanentCertificateAccessCode}.
     *
     * @param permanentCertificateAccessCode Permanent certificate access code &#40;Portugal&#41;
     * @return This builder instance.
     */
    public Builder permanentCertificateAccessCode(String permanentCertificateAccessCode) {
      this.permanentCertificateAccessCode = permanentCertificateAccessCode;
      return this;
    }

    /**
     * Sets the value for {@code settings}.
     *
     * @param settings Merchant settings &#40;like \"payout_type\", \"payout_period\"&#41;
     * @return This builder instance.
     */
    public Builder settings(com.sumup.sdk.models.MerchantSettings settings) {
      this.settings = settings;
      return this;
    }

    /**
     * Sets the value for {@code vatId}.
     *
     * @param vatId Vat ID
     * @return This builder instance.
     */
    public Builder vatId(String vatId) {
      this.vatId = vatId;
      return this;
    }

    /**
     * Sets the value for {@code vatRates}.
     *
     * @param vatRates Merchant VAT rates
     * @return This builder instance.
     */
    public Builder vatRates(com.sumup.sdk.models.VatRates vatRates) {
      this.vatRates = vatRates;
      return this;
    }

    /**
     * Sets the value for {@code website}.
     *
     * @param website Website
     * @return This builder instance.
     */
    public Builder website(String website) {
      this.website = website;
      return this;
    }

    /**
     * Builds an immutable MerchantProfileLegacy instance.
     *
     * @return Immutable MerchantProfileLegacy.
     */
    public MerchantProfileLegacy build() {
      return new MerchantProfileLegacy(
          address,
          bankAccounts,
          businessOwners,
          companyName,
          companyRegistrationNumber,
          country,
          doingBusinessAs,
          extdev,
          legalType,
          locale,
          merchantCategoryCode,
          merchantCode,
          mobilePhone,
          natureAndPurpose,
          payoutZoneMigrated,
          permanentCertificateAccessCode,
          settings,
          vatId,
          vatRates,
          website);
    }
  }
}
