// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Payout period. */
public enum MerchantSettingsPayloadPayoutPeriod {
  DAILY("daily"),
  WEEKLY("weekly"),
  MONTHLY("monthly");

  private final String value;

  MerchantSettingsPayloadPayoutPeriod(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static MerchantSettingsPayloadPayoutPeriod fromValue(String value) {
    if (value == null) {
      return null;
    }
    for (MerchantSettingsPayloadPayoutPeriod entry : values()) {
      if (entry.value.equals(value)) {
        return entry;
      }
    }
    throw new IllegalArgumentException(
        "Unknown MerchantSettingsPayloadPayoutPeriod value: " + value);
  }
}
