// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

public record MerchantProfilePayloadDoingBusinessAs(
    /** Personal address */
    com.sumup.sdk.models.AddressPayloadLegacy address,

    /** Doing business as name */
    String businessName,

    /** Doing business as email */
    String email,

    /** Doing business as Tax ID */
    String taxId,

    /** Doing business as Vat ID */
    String vatId,

    /** Doing business as website */
    String website) {
  /**
   * Creates a builder for MerchantProfilePayloadDoingBusinessAs.
   *
   * @return Builder that constructs immutable MerchantProfilePayloadDoingBusinessAs instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for MerchantProfilePayloadDoingBusinessAs instances. */
  public static final class Builder {
    private com.sumup.sdk.models.AddressPayloadLegacy address;
    private String businessName;
    private String email;
    private String taxId;
    private String vatId;
    private String website;

    private Builder() {}

    /**
     * Sets the value for {@code address}.
     *
     * @param address Personal address
     * @return This builder instance.
     */
    public Builder address(com.sumup.sdk.models.AddressPayloadLegacy address) {
      this.address = address;
      return this;
    }

    /**
     * Sets the value for {@code businessName}.
     *
     * @param businessName Doing business as name
     * @return This builder instance.
     */
    public Builder businessName(String businessName) {
      this.businessName = businessName;
      return this;
    }

    /**
     * Sets the value for {@code email}.
     *
     * @param email Doing business as email
     * @return This builder instance.
     */
    public Builder email(String email) {
      this.email = email;
      return this;
    }

    /**
     * Sets the value for {@code taxId}.
     *
     * @param taxId Doing business as Tax ID
     * @return This builder instance.
     */
    public Builder taxId(String taxId) {
      this.taxId = taxId;
      return this;
    }

    /**
     * Sets the value for {@code vatId}.
     *
     * @param vatId Doing business as Vat ID
     * @return This builder instance.
     */
    public Builder vatId(String vatId) {
      this.vatId = vatId;
      return this;
    }

    /**
     * Sets the value for {@code website}.
     *
     * @param website Doing business as website
     * @return This builder instance.
     */
    public Builder website(String website) {
      this.website = website;
      return this;
    }

    /**
     * Builds an immutable MerchantProfilePayloadDoingBusinessAs instance.
     *
     * @return Immutable MerchantProfilePayloadDoingBusinessAs.
     */
    public MerchantProfilePayloadDoingBusinessAs build() {
      return new MerchantProfilePayloadDoingBusinessAs(
          address, businessName, email, taxId, vatId, website);
    }
  }
}
