// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

/** Account's merchant profile */
public record MerchantProfilePayload(
    /** Personal address */
    com.sumup.sdk.models.AddressPayloadLegacy address,

    /** Business owners information. */
    com.sumup.sdk.models.BusinessOwners businessOwners,

    /** Company name */
    String companyName,

    /** Company registration number */
    String companyRegistrationNumber,
    com.sumup.sdk.models.MerchantProfilePayloadDoingBusinessAs doingBusinessAs,

    /** Defines if the profile nature is for testing */
    Boolean isTestAccount,

    /** Id of the legal type of the merchant */
    Double legalTypeId,

    /** Merchant category code */
    String merchantCategoryCode,

    /** Mobile number */
    String mobilePhone,

    /**
     * Nature and purpose of the business. Required for the following merchant category codes: 5999,
     * 7392, 8999, 5694, 5969, 7299, 7399
     */
    String natureAndPurpose,

    /** Payment certificate access code */
    String permanentCertificateAccessCode,

    /** Vat ID */
    String vatId,

    /** Company website */
    String website) {
  /**
   * Creates a builder for MerchantProfilePayload.
   *
   * @return Builder that constructs immutable MerchantProfilePayload instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for MerchantProfilePayload instances. */
  public static final class Builder {
    private com.sumup.sdk.models.AddressPayloadLegacy address;
    private com.sumup.sdk.models.BusinessOwners businessOwners;
    private String companyName;
    private String companyRegistrationNumber;
    private com.sumup.sdk.models.MerchantProfilePayloadDoingBusinessAs doingBusinessAs;
    private Boolean isTestAccount;
    private Double legalTypeId;
    private String merchantCategoryCode;
    private String mobilePhone;
    private String natureAndPurpose;
    private String permanentCertificateAccessCode;
    private String vatId;
    private String website;

    private Builder() {}

    /**
     * Sets the value for {@code address}.
     *
     * @param address Personal address
     * @return This builder instance.
     */
    public Builder address(com.sumup.sdk.models.AddressPayloadLegacy address) {
      this.address = address;
      return this;
    }

    /**
     * Sets the value for {@code businessOwners}.
     *
     * @param businessOwners Business owners information.
     * @return This builder instance.
     */
    public Builder businessOwners(com.sumup.sdk.models.BusinessOwners businessOwners) {
      this.businessOwners = businessOwners;
      return this;
    }

    /**
     * Sets the value for {@code companyName}.
     *
     * @param companyName Company name
     * @return This builder instance.
     */
    public Builder companyName(String companyName) {
      this.companyName = companyName;
      return this;
    }

    /**
     * Sets the value for {@code companyRegistrationNumber}.
     *
     * @param companyRegistrationNumber Company registration number
     * @return This builder instance.
     */
    public Builder companyRegistrationNumber(String companyRegistrationNumber) {
      this.companyRegistrationNumber = companyRegistrationNumber;
      return this;
    }

    /**
     * Sets the value for {@code doingBusinessAs}.
     *
     * @param doingBusinessAs Value for the doingBusinessAs field.
     * @return This builder instance.
     */
    public Builder doingBusinessAs(
        com.sumup.sdk.models.MerchantProfilePayloadDoingBusinessAs doingBusinessAs) {
      this.doingBusinessAs = doingBusinessAs;
      return this;
    }

    /**
     * Sets the value for {@code isTestAccount}.
     *
     * @param isTestAccount Defines if the profile nature is for testing
     * @return This builder instance.
     */
    public Builder isTestAccount(Boolean isTestAccount) {
      this.isTestAccount = isTestAccount;
      return this;
    }

    /**
     * Sets the value for {@code legalTypeId}.
     *
     * @param legalTypeId Id of the legal type of the merchant
     * @return This builder instance.
     */
    public Builder legalTypeId(Double legalTypeId) {
      this.legalTypeId = legalTypeId;
      return this;
    }

    /**
     * Sets the value for {@code merchantCategoryCode}.
     *
     * @param merchantCategoryCode Merchant category code
     * @return This builder instance.
     */
    public Builder merchantCategoryCode(String merchantCategoryCode) {
      this.merchantCategoryCode = merchantCategoryCode;
      return this;
    }

    /**
     * Sets the value for {@code mobilePhone}.
     *
     * @param mobilePhone Mobile number
     * @return This builder instance.
     */
    public Builder mobilePhone(String mobilePhone) {
      this.mobilePhone = mobilePhone;
      return this;
    }

    /**
     * Sets the value for {@code natureAndPurpose}.
     *
     * @param natureAndPurpose Nature and purpose of the business. Required for the following
     *     merchant category codes: 5999, 7392, 8999, 5694, 5969, 7299, 7399
     * @return This builder instance.
     */
    public Builder natureAndPurpose(String natureAndPurpose) {
      this.natureAndPurpose = natureAndPurpose;
      return this;
    }

    /**
     * Sets the value for {@code permanentCertificateAccessCode}.
     *
     * @param permanentCertificateAccessCode Payment certificate access code
     * @return This builder instance.
     */
    public Builder permanentCertificateAccessCode(String permanentCertificateAccessCode) {
      this.permanentCertificateAccessCode = permanentCertificateAccessCode;
      return this;
    }

    /**
     * Sets the value for {@code vatId}.
     *
     * @param vatId Vat ID
     * @return This builder instance.
     */
    public Builder vatId(String vatId) {
      this.vatId = vatId;
      return this;
    }

    /**
     * Sets the value for {@code website}.
     *
     * @param website Company website
     * @return This builder instance.
     */
    public Builder website(String website) {
      this.website = website;
      return this;
    }

    /**
     * Builds an immutable MerchantProfilePayload instance.
     *
     * @return Immutable MerchantProfilePayload.
     */
    public MerchantProfilePayload build() {
      return new MerchantProfilePayload(
          Objects.requireNonNull(address, "address"),
          businessOwners,
          Objects.requireNonNull(companyName, "companyName"),
          Objects.requireNonNull(companyRegistrationNumber, "companyRegistrationNumber"),
          doingBusinessAs,
          isTestAccount,
          Objects.requireNonNull(legalTypeId, "legalTypeId"),
          Objects.requireNonNull(merchantCategoryCode, "merchantCategoryCode"),
          mobilePhone,
          natureAndPurpose,
          permanentCertificateAccessCode,
          vatId,
          website);
    }
  }
}
