// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

public record MerchantSettingsPayload(
    /** Expected maximum amount of a single purchase */
    Double expectedMaxTransactionAmount,

    /** Gross settlement */
    Boolean grossSettlement,

    /** If true, the merchant will not receive automatic payouts. */
    Boolean payoutOnDemand,

    /** If true, the merchant will be able to manage payout_on_demand settings */
    String payoutOnDemandAvailable,

    /** Payout period. */
    com.sumup.sdk.models.MerchantSettingsPayloadPayoutPeriod payoutPeriod,

    /** Payout type. */
    com.sumup.sdk.models.MerchantSettingsPayloadPayoutType payoutType,

    /** Printers enabled. */
    Boolean printersEnabled) {
  /**
   * Creates a builder for MerchantSettingsPayload.
   *
   * @return Builder that constructs immutable MerchantSettingsPayload instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for MerchantSettingsPayload instances. */
  public static final class Builder {
    private Double expectedMaxTransactionAmount;
    private Boolean grossSettlement;
    private Boolean payoutOnDemand;
    private String payoutOnDemandAvailable;
    private com.sumup.sdk.models.MerchantSettingsPayloadPayoutPeriod payoutPeriod;
    private com.sumup.sdk.models.MerchantSettingsPayloadPayoutType payoutType;
    private Boolean printersEnabled;

    private Builder() {}

    /**
     * Sets the value for {@code expectedMaxTransactionAmount}.
     *
     * @param expectedMaxTransactionAmount Expected maximum amount of a single purchase
     * @return This builder instance.
     */
    public Builder expectedMaxTransactionAmount(Double expectedMaxTransactionAmount) {
      this.expectedMaxTransactionAmount = expectedMaxTransactionAmount;
      return this;
    }

    /**
     * Sets the value for {@code grossSettlement}.
     *
     * @param grossSettlement Gross settlement
     * @return This builder instance.
     */
    public Builder grossSettlement(Boolean grossSettlement) {
      this.grossSettlement = grossSettlement;
      return this;
    }

    /**
     * Sets the value for {@code payoutOnDemand}.
     *
     * @param payoutOnDemand If true, the merchant will not receive automatic payouts.
     * @return This builder instance.
     */
    public Builder payoutOnDemand(Boolean payoutOnDemand) {
      this.payoutOnDemand = payoutOnDemand;
      return this;
    }

    /**
     * Sets the value for {@code payoutOnDemandAvailable}.
     *
     * @param payoutOnDemandAvailable If true, the merchant will be able to manage payout_on_demand
     *     settings
     * @return This builder instance.
     */
    public Builder payoutOnDemandAvailable(String payoutOnDemandAvailable) {
      this.payoutOnDemandAvailable = payoutOnDemandAvailable;
      return this;
    }

    /**
     * Sets the value for {@code payoutPeriod}.
     *
     * @param payoutPeriod Payout period.
     * @return This builder instance.
     */
    public Builder payoutPeriod(
        com.sumup.sdk.models.MerchantSettingsPayloadPayoutPeriod payoutPeriod) {
      this.payoutPeriod = payoutPeriod;
      return this;
    }

    /**
     * Sets the value for {@code payoutType}.
     *
     * @param payoutType Payout type.
     * @return This builder instance.
     */
    public Builder payoutType(com.sumup.sdk.models.MerchantSettingsPayloadPayoutType payoutType) {
      this.payoutType = payoutType;
      return this;
    }

    /**
     * Sets the value for {@code printersEnabled}.
     *
     * @param printersEnabled Printers enabled.
     * @return This builder instance.
     */
    public Builder printersEnabled(Boolean printersEnabled) {
      this.printersEnabled = printersEnabled;
      return this;
    }

    /**
     * Builds an immutable MerchantSettingsPayload instance.
     *
     * @return Immutable MerchantSettingsPayload.
     */
    public MerchantSettingsPayload build() {
      return new MerchantSettingsPayload(
          expectedMaxTransactionAmount,
          grossSettlement,
          payoutOnDemand,
          payoutOnDemandAvailable,
          payoutPeriod,
          payoutType,
          printersEnabled);
    }
  }
}
