// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

/**
 * Amount structure. * The amount is represented as an integer value altogether with the currency
 * and the minor unit. * For example, EUR 1.00 is represented as value 100 with minor unit of 2.
 */
public record Money(
    /** Currency ISO 4217 code */
    String currency,

    /**
     * The minor units of the currency. It represents the number of decimals of the currency. For
     * the currencies CLP, COP and HUF, the minor unit is 0.
     */
    Long minorUnit,

    /** Integer value of the amount. */
    Long value) {
  /**
   * Creates a builder for Money.
   *
   * @return Builder that constructs immutable Money instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for Money instances. */
  public static final class Builder {
    private String currency;
    private Long minorUnit;
    private Long value;

    private Builder() {}

    /**
     * Sets the value for {@code currency}.
     *
     * @param currency Currency ISO 4217 code
     * @return This builder instance.
     */
    public Builder currency(String currency) {
      this.currency = currency;
      return this;
    }

    /**
     * Sets the value for {@code minorUnit}.
     *
     * @param minorUnit The minor units of the currency. It represents the number of decimals of the
     *     currency. For the currencies CLP, COP and HUF, the minor unit is 0.
     * @return This builder instance.
     */
    public Builder minorUnit(Long minorUnit) {
      this.minorUnit = minorUnit;
      return this;
    }

    /**
     * Sets the value for {@code value}.
     *
     * @param value Integer value of the amount.
     * @return This builder instance.
     */
    public Builder value(Long value) {
      this.value = value;
      return this;
    }

    /**
     * Builds an immutable Money instance.
     *
     * @return Immutable Money.
     */
    public Money build() {
      return new Money(
          Objects.requireNonNull(currency, "currency"),
          Objects.requireNonNull(minorUnit, "minorUnit"),
          Objects.requireNonNull(value, "value"));
    }
  }
}
