// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

/** 404 Not Found */
public record NotFound(com.sumup.sdk.models.NotFoundErrors errors) {
  /**
   * Creates a builder for NotFound.
   *
   * @return Builder that constructs immutable NotFound instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for NotFound instances. */
  public static final class Builder {
    private com.sumup.sdk.models.NotFoundErrors errors;

    private Builder() {}

    /**
     * Sets the value for {@code errors}.
     *
     * @param errors Value for the errors field.
     * @return This builder instance.
     */
    public Builder errors(com.sumup.sdk.models.NotFoundErrors errors) {
      this.errors = errors;
      return this;
    }

    /**
     * Builds an immutable NotFound instance.
     *
     * @return Immutable NotFound.
     */
    public NotFound build() {
      return new NotFound(Objects.requireNonNull(errors, "errors"));
    }
  }
}
