// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

public final class OperatorAccountType {
  public static final OperatorAccountType OPERATOR = new OperatorAccountType("operator");
  public static final OperatorAccountType NORMAL = new OperatorAccountType("normal");

  private final String value;

  private OperatorAccountType(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a OperatorAccountType for a value not yet known to this SDK version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static OperatorAccountType of(String value) {
    return new OperatorAccountType(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static OperatorAccountType fromValue(String value) {
    return value == null ? null : new OperatorAccountType(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof OperatorAccountType that && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
