// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** Details of a saved payment instrument. */
public record PaymentInstrumentResponse(
    /**
     * Indicates whether the payment instrument is active and can be used for payments. To
     * deactivate it, send a `DELETE` request to the resource endpoint.
     */
    Boolean active,

    /** Details of the payment card. */
    com.sumup.sdk.models.PaymentInstrumentResponseCard card,

    /** The timestamp of when the payment instrument was created. */
    java.time.OffsetDateTime createdAt,

    /** Details of the mandate linked to the saved payment instrument. */
    com.sumup.sdk.models.MandateResponse mandate,

    /** Unique token identifying the saved payment card for a customer. */
    String token,

    /** Type of the payment instrument. */
    com.sumup.sdk.models.PaymentInstrumentResponseType type) {
  /**
   * Creates a builder for PaymentInstrumentResponse.
   *
   * @return Builder that constructs immutable PaymentInstrumentResponse instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for PaymentInstrumentResponse instances. */
  public static final class Builder {
    private com.sumup.sdk.models.PaymentInstrumentResponseCard card;
    private java.time.OffsetDateTime createdAt;
    private com.sumup.sdk.models.MandateResponse mandate;
    private com.sumup.sdk.models.PaymentInstrumentResponseType type;

    private Builder() {}

    /**
     * Sets the value for {@code card}.
     *
     * @param card Details of the payment card.
     * @return This builder instance.
     */
    public Builder card(com.sumup.sdk.models.PaymentInstrumentResponseCard card) {
      this.card = card;
      return this;
    }

    /**
     * Sets the value for {@code createdAt}.
     *
     * @param createdAt The timestamp of when the payment instrument was created.
     * @return This builder instance.
     */
    public Builder createdAt(java.time.OffsetDateTime createdAt) {
      this.createdAt = createdAt;
      return this;
    }

    /**
     * Sets the value for {@code mandate}.
     *
     * @param mandate Details of the mandate linked to the saved payment instrument.
     * @return This builder instance.
     */
    public Builder mandate(com.sumup.sdk.models.MandateResponse mandate) {
      this.mandate = mandate;
      return this;
    }

    /**
     * Sets the value for {@code type}.
     *
     * @param type Type of the payment instrument.
     * @return This builder instance.
     */
    public Builder type(com.sumup.sdk.models.PaymentInstrumentResponseType type) {
      this.type = type;
      return this;
    }

    /**
     * Builds an immutable PaymentInstrumentResponse instance.
     *
     * @return Immutable PaymentInstrumentResponse.
     */
    public PaymentInstrumentResponse build() {
      return new PaymentInstrumentResponse(null, card, createdAt, mandate, null, type);
    }
  }
}
