// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** Details of the payment card. */
public record PaymentInstrumentResponseCard(
    /** Last 4 digits of the payment card number. */
    String last4Digits,

    /** Issuing card network of the payment card used for the transaction. */
    com.sumup.sdk.models.CardType type) {
  /**
   * Creates a builder for PaymentInstrumentResponseCard.
   *
   * @return Builder that constructs immutable PaymentInstrumentResponseCard instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for PaymentInstrumentResponseCard instances. */
  public static final class Builder {
    private com.sumup.sdk.models.CardType type;

    private Builder() {}

    /**
     * Sets the value for {@code type}.
     *
     * @param type Issuing card network of the payment card used for the transaction.
     * @return This builder instance.
     */
    public Builder type(com.sumup.sdk.models.CardType type) {
      this.type = type;
      return this;
    }

    /**
     * Builds an immutable PaymentInstrumentResponseCard instance.
     *
     * @return Immutable PaymentInstrumentResponseCard.
     */
    public PaymentInstrumentResponseCard build() {
      return new PaymentInstrumentResponseCard(null, type);
    }
  }
}
