// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

/** Details of the payment card that is saved as a payment instrument. */
public record PaymentInstrumentCard(
    /** __Required when payment type is `card`.__ Details of the payment card. */
    com.sumup.sdk.models.Card card,

    /** Type of the payment instrument. */
    com.sumup.sdk.models.PaymentInstrumentCardType type) {
  /**
   * Creates a builder for PaymentInstrumentCard.
   *
   * @return Builder that constructs immutable PaymentInstrumentCard instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for PaymentInstrumentCard instances. */
  public static final class Builder {
    private com.sumup.sdk.models.Card card;
    private com.sumup.sdk.models.PaymentInstrumentCardType type;

    private Builder() {}

    /**
     * Sets the value for {@code card}.
     *
     * @param card __Required when payment type is `card`.__ Details of the payment card.
     * @return This builder instance.
     */
    public Builder card(com.sumup.sdk.models.Card card) {
      this.card = card;
      return this;
    }

    /**
     * Sets the value for {@code type}.
     *
     * @param type Type of the payment instrument.
     * @return This builder instance.
     */
    public Builder type(com.sumup.sdk.models.PaymentInstrumentCardType type) {
      this.type = type;
      return this;
    }

    /**
     * Builds an immutable PaymentInstrumentCard instance.
     *
     * @return Immutable PaymentInstrumentCard.
     */
    public PaymentInstrumentCard build() {
      return new PaymentInstrumentCard(
          Objects.requireNonNull(card, "card"), Objects.requireNonNull(type, "type"));
    }
  }
}
