// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Type of the payment instrument. */
public enum PaymentInstrumentCardType {
  CARD("card");

  private final String value;

  PaymentInstrumentCardType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static PaymentInstrumentCardType fromValue(String value) {
    if (value == null) {
      return null;
    }
    for (PaymentInstrumentCardType entry : values()) {
      if (entry.value.equals(value)) {
        return entry;
      }
    }
    throw new IllegalArgumentException("Unknown PaymentInstrumentCardType value: " + value);
  }
}
