// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

/** Type of the payment instrument. */
public final class PaymentInstrumentResponseType {
  public static final PaymentInstrumentResponseType CARD =
      new PaymentInstrumentResponseType("card");

  private final String value;

  private PaymentInstrumentResponseType(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a PaymentInstrumentResponseType for a value not yet known to this SDK version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static PaymentInstrumentResponseType of(String value) {
    return new PaymentInstrumentResponseType(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static PaymentInstrumentResponseType fromValue(String value) {
    return value == null ? null : new PaymentInstrumentResponseType(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof PaymentInstrumentResponseType that && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
