// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

/** Permissions assigned to an operator or user. */
public record Permissions(
    Boolean admin,
    Boolean createMotoPayments,
    Boolean createReferral,
    Boolean fullTransactionHistoryView,
    Boolean refundTransactions) {
  /**
   * Creates a builder for Permissions.
   *
   * @return Builder that constructs immutable Permissions instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for Permissions instances. */
  public static final class Builder {
    private Boolean admin;
    private Boolean createMotoPayments;
    private Boolean createReferral;
    private Boolean fullTransactionHistoryView;
    private Boolean refundTransactions;

    private Builder() {}

    /**
     * Sets the value for {@code admin}.
     *
     * @param admin Value for the admin field.
     * @return This builder instance.
     */
    public Builder admin(Boolean admin) {
      this.admin = admin;
      return this;
    }

    /**
     * Sets the value for {@code createMotoPayments}.
     *
     * @param createMotoPayments Value for the createMotoPayments field.
     * @return This builder instance.
     */
    public Builder createMotoPayments(Boolean createMotoPayments) {
      this.createMotoPayments = createMotoPayments;
      return this;
    }

    /**
     * Sets the value for {@code createReferral}.
     *
     * @param createReferral Value for the createReferral field.
     * @return This builder instance.
     */
    public Builder createReferral(Boolean createReferral) {
      this.createReferral = createReferral;
      return this;
    }

    /**
     * Sets the value for {@code fullTransactionHistoryView}.
     *
     * @param fullTransactionHistoryView Value for the fullTransactionHistoryView field.
     * @return This builder instance.
     */
    public Builder fullTransactionHistoryView(Boolean fullTransactionHistoryView) {
      this.fullTransactionHistoryView = fullTransactionHistoryView;
      return this;
    }

    /**
     * Sets the value for {@code refundTransactions}.
     *
     * @param refundTransactions Value for the refundTransactions field.
     * @return This builder instance.
     */
    public Builder refundTransactions(Boolean refundTransactions) {
      this.refundTransactions = refundTransactions;
      return this;
    }

    /**
     * Builds an immutable Permissions instance.
     *
     * @return Immutable Permissions.
     */
    public Permissions build() {
      return new Permissions(
          Objects.requireNonNull(admin, "admin"),
          Objects.requireNonNull(createMotoPayments, "createMotoPayments"),
          Objects.requireNonNull(createReferral, "createReferral"),
          Objects.requireNonNull(fullTransactionHistoryView, "fullTransactionHistoryView"),
          Objects.requireNonNull(refundTransactions, "refundTransactions"));
    }
  }
}
