// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** User permissions */
public record PermissionsLegacy(
    /** Create MOTO payments */
    Boolean createMotoPayments,

    /** Create referral */
    Boolean createReferral,

    /** Can view full merchant transaction history */
    Boolean fullTransactionHistoryView,

    /** Refund transactions */
    Boolean refundTransactions) {
  /**
   * Creates a builder for PermissionsLegacy.
   *
   * @return Builder that constructs immutable PermissionsLegacy instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for PermissionsLegacy instances. */
  public static final class Builder {
    private Boolean createMotoPayments;
    private Boolean createReferral;
    private Boolean fullTransactionHistoryView;
    private Boolean refundTransactions;

    private Builder() {}

    /**
     * Sets the value for {@code createMotoPayments}.
     *
     * @param createMotoPayments Create MOTO payments
     * @return This builder instance.
     */
    public Builder createMotoPayments(Boolean createMotoPayments) {
      this.createMotoPayments = createMotoPayments;
      return this;
    }

    /**
     * Sets the value for {@code createReferral}.
     *
     * @param createReferral Create referral
     * @return This builder instance.
     */
    public Builder createReferral(Boolean createReferral) {
      this.createReferral = createReferral;
      return this;
    }

    /**
     * Sets the value for {@code fullTransactionHistoryView}.
     *
     * @param fullTransactionHistoryView Can view full merchant transaction history
     * @return This builder instance.
     */
    public Builder fullTransactionHistoryView(Boolean fullTransactionHistoryView) {
      this.fullTransactionHistoryView = fullTransactionHistoryView;
      return this;
    }

    /**
     * Sets the value for {@code refundTransactions}.
     *
     * @param refundTransactions Refund transactions
     * @return This builder instance.
     */
    public Builder refundTransactions(Boolean refundTransactions) {
      this.refundTransactions = refundTransactions;
      return this;
    }

    /**
     * Builds an immutable PermissionsLegacy instance.
     *
     * @return Immutable PermissionsLegacy.
     */
    public PermissionsLegacy build() {
      return new PermissionsLegacy(
          createMotoPayments, createReferral, fullTransactionHistoryView, refundTransactions);
    }
  }
}
