// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** A list of country-specific personal identifiers. */
public record PersonalIdentifiers(java.util.List<com.sumup.sdk.models.PersonalIdentifier> value) {}
