// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import java.util.Objects;

/**
 * A RFC 9457 problem details object. Additional properties specific to the problem type may be
 * present.
 */
@JsonDeserialize(builder = Problem.Builder.class)
public record Problem(
    /** A human-readable explanation specific to this occurrence of the problem. */
    String detail,

    /** A URI reference that identifies the specific occurrence of the problem. */
    String instance,

    /** The HTTP status code generated by the origin server for this occurrence of the problem. */
    Long status,

    /** A short, human-readable summary of the problem type. */
    String title,

    /** A URI reference that identifies the problem type. */
    String type,

    /** Additional fields not described by the fixed schema properties. */
    java.util.Map<String, Object> additionalProperties) {
  public Problem {
    additionalProperties =
        additionalProperties == null
            ? java.util.Map.of()
            : java.util.Map.copyOf(additionalProperties);
  }

  @JsonAnyGetter
  public java.util.Map<String, Object> additionalProperties() {
    return additionalProperties;
  }

  /**
   * Creates a builder for Problem.
   *
   * @return Builder that constructs immutable Problem instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for Problem instances. */
  @JsonPOJOBuilder(withPrefix = "")
  public static final class Builder {
    private String detail;
    private String instance;
    private Long status;
    private String title;
    private String type;
    private java.util.Map<String, Object> additionalProperties = new java.util.LinkedHashMap<>();

    private Builder() {}

    /**
     * Sets the value for {@code detail}.
     *
     * @param detail A human-readable explanation specific to this occurrence of the problem.
     * @return This builder instance.
     */
    public Builder detail(String detail) {
      this.detail = detail;
      return this;
    }

    /**
     * Sets the value for {@code instance}.
     *
     * @param instance A URI reference that identifies the specific occurrence of the problem.
     * @return This builder instance.
     */
    public Builder instance(String instance) {
      this.instance = instance;
      return this;
    }

    /**
     * Sets the value for {@code status}.
     *
     * @param status The HTTP status code generated by the origin server for this occurrence of the
     *     problem.
     * @return This builder instance.
     */
    public Builder status(Long status) {
      this.status = status;
      return this;
    }

    /**
     * Sets the value for {@code title}.
     *
     * @param title A short, human-readable summary of the problem type.
     * @return This builder instance.
     */
    public Builder title(String title) {
      this.title = title;
      return this;
    }

    /**
     * Sets the value for {@code type}.
     *
     * @param type A URI reference that identifies the problem type.
     * @return This builder instance.
     */
    public Builder type(String type) {
      this.type = type;
      return this;
    }

    /**
     * Sets the value for {@code additionalProperties}.
     *
     * @param additionalProperties Additional fields not described by the fixed schema properties.
     * @return This builder instance.
     */
    public Builder additionalProperties(java.util.Map<String, Object> additionalProperties) {
      this.additionalProperties = additionalProperties;
      return this;
    }

    @JsonAnySetter
    public Builder additionalProperty(String name, Object value) {
      this.additionalProperties.put(name, value);
      return this;
    }

    /**
     * Builds an immutable Problem instance.
     *
     * @return Immutable Problem.
     */
    public Problem build() {
      return new Problem(
          detail,
          instance,
          status,
          title,
          Objects.requireNonNull(type, "type"),
          additionalProperties);
    }
  }
}
