// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

/**
 * Request body for attempting payment on an existing checkout. The required companion fields depend
 * on the selected `payment_type`, for example card details, saved-card data, or payer information
 * required by a specific payment method.
 */
public record ProcessCheckout(
    /**
     * Raw payment token object received from Apple Pay. Send the Apple Pay response payload as-is.
     */
    java.util.Map<String, Object> applePay,

    /** __Required when payment type is `card`.__ Details of the payment card. */
    com.sumup.sdk.models.Card card,

    /**
     * Customer identifier associated with the saved payment instrument. Required when `token` is
     * provided.
     */
    String customerId,

    /**
     * Raw `PaymentData` object received from Google Pay. Send the Google Pay response payload
     * as-is.
     */
    java.util.Map<String, Object> googlePay,

    /** Number of installments for deferred payments. Available only to merchant users in Brazil. */
    Long installments,

    /**
     * Mandate details used when a checkout should create a reusable card token for future recurring
     * or merchant-initiated payments.
     */
    com.sumup.sdk.models.MandatePayload mandate,

    /**
     * Payment method used for this processing attempt. It determines which additional request
     * fields are required.
     */
    com.sumup.sdk.models.ProcessCheckoutPaymentType paymentType,

    /** Personal details for the customer. */
    com.sumup.sdk.models.PersonalDetails personalDetails,

    /**
     * Saved-card token to use instead of raw card details when processing with a previously stored
     * payment instrument.
     */
    String token) {
  /**
   * Creates a builder for ProcessCheckout.
   *
   * @return Builder that constructs immutable ProcessCheckout instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for ProcessCheckout instances. */
  public static final class Builder {
    private java.util.Map<String, Object> applePay;
    private com.sumup.sdk.models.Card card;
    private String customerId;
    private java.util.Map<String, Object> googlePay;
    private Long installments;
    private com.sumup.sdk.models.MandatePayload mandate;
    private com.sumup.sdk.models.ProcessCheckoutPaymentType paymentType;
    private com.sumup.sdk.models.PersonalDetails personalDetails;
    private String token;

    private Builder() {}

    /**
     * Sets the value for {@code applePay}.
     *
     * @param applePay Raw payment token object received from Apple Pay. Send the Apple Pay response
     *     payload as-is.
     * @return This builder instance.
     */
    public Builder applePay(java.util.Map<String, Object> applePay) {
      this.applePay = applePay;
      return this;
    }

    /**
     * Sets the value for {@code card}.
     *
     * @param card __Required when payment type is `card`.__ Details of the payment card.
     * @return This builder instance.
     */
    public Builder card(com.sumup.sdk.models.Card card) {
      this.card = card;
      return this;
    }

    /**
     * Sets the value for {@code customerId}.
     *
     * @param customerId Customer identifier associated with the saved payment instrument. Required
     *     when `token` is provided.
     * @return This builder instance.
     */
    public Builder customerId(String customerId) {
      this.customerId = customerId;
      return this;
    }

    /**
     * Sets the value for {@code googlePay}.
     *
     * @param googlePay Raw `PaymentData` object received from Google Pay. Send the Google Pay
     *     response payload as-is.
     * @return This builder instance.
     */
    public Builder googlePay(java.util.Map<String, Object> googlePay) {
      this.googlePay = googlePay;
      return this;
    }

    /**
     * Sets the value for {@code installments}.
     *
     * @param installments Number of installments for deferred payments. Available only to merchant
     *     users in Brazil.
     * @return This builder instance.
     */
    public Builder installments(Long installments) {
      this.installments = installments;
      return this;
    }

    /**
     * Sets the value for {@code mandate}.
     *
     * @param mandate Mandate details used when a checkout should create a reusable card token for
     *     future recurring or merchant-initiated payments.
     * @return This builder instance.
     */
    public Builder mandate(com.sumup.sdk.models.MandatePayload mandate) {
      this.mandate = mandate;
      return this;
    }

    /**
     * Sets the value for {@code paymentType}.
     *
     * @param paymentType Payment method used for this processing attempt. It determines which
     *     additional request fields are required.
     * @return This builder instance.
     */
    public Builder paymentType(com.sumup.sdk.models.ProcessCheckoutPaymentType paymentType) {
      this.paymentType = paymentType;
      return this;
    }

    /**
     * Sets the value for {@code personalDetails}.
     *
     * @param personalDetails Personal details for the customer.
     * @return This builder instance.
     */
    public Builder personalDetails(com.sumup.sdk.models.PersonalDetails personalDetails) {
      this.personalDetails = personalDetails;
      return this;
    }

    /**
     * Sets the value for {@code token}.
     *
     * @param token Saved-card token to use instead of raw card details when processing with a
     *     previously stored payment instrument.
     * @return This builder instance.
     */
    public Builder token(String token) {
      this.token = token;
      return this;
    }

    /**
     * Builds an immutable ProcessCheckout instance.
     *
     * @return Immutable ProcessCheckout.
     */
    public ProcessCheckout build() {
      return new ProcessCheckout(
          applePay,
          card,
          customerId,
          googlePay,
          installments,
          mandate,
          Objects.requireNonNull(paymentType, "paymentType"),
          personalDetails,
          token);
    }
  }
}
