// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Payment method used for this processing attempt. It determines which additional request fields
 * are required.
 */
public enum ProcessCheckoutPaymentType {
  CARD("card"),
  BOLETO("boleto"),
  IDEAL("ideal"),
  BLIK("blik"),
  BANCONTACT("bancontact"),
  GOOGLE_PAY("google_pay"),
  APPLE_PAY("apple_pay");

  private final String value;

  ProcessCheckoutPaymentType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static ProcessCheckoutPaymentType fromValue(String value) {
    if (value == null) {
      return null;
    }
    for (ProcessCheckoutPaymentType entry : values()) {
      if (entry.value.equals(value)) {
        return entry;
      }
    }
    throw new IllegalArgumentException("Unknown ProcessCheckoutPaymentType value: " + value);
  }
}
