// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** Product details associated with a transaction. */
public record Product(
    /** Product name. */
    String name,

    /** Product price. */
    Double price,

    /** Human-readable label for the product price. */
    String priceLabel,

    /** Product price including VAT. */
    Double priceWithVat,

    /** Product quantity. */
    Long quantity,

    /** VAT amount for a single product. */
    Double singleVatAmount,

    /** Total price calculated as the product price multiplied by the quantity. */
    Double totalPrice,

    /** Total product price including VAT. */
    Double totalWithVat,

    /** Total VAT amount for the product quantity. */
    Double vatAmount,

    /** VAT rate applied to the product price. */
    Double vatRate) {
  /**
   * Creates a builder for Product.
   *
   * @return Builder that constructs immutable Product instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for Product instances. */
  public static final class Builder {
    private String name;
    private Double price;
    private String priceLabel;
    private Double priceWithVat;
    private Long quantity;
    private Double singleVatAmount;
    private Double totalPrice;
    private Double totalWithVat;
    private Double vatAmount;
    private Double vatRate;

    private Builder() {}

    /**
     * Sets the value for {@code name}.
     *
     * @param name Product name.
     * @return This builder instance.
     */
    public Builder name(String name) {
      this.name = name;
      return this;
    }

    /**
     * Sets the value for {@code price}.
     *
     * @param price Product price.
     * @return This builder instance.
     */
    public Builder price(Double price) {
      this.price = price;
      return this;
    }

    /**
     * Sets the value for {@code priceLabel}.
     *
     * @param priceLabel Human-readable label for the product price.
     * @return This builder instance.
     */
    public Builder priceLabel(String priceLabel) {
      this.priceLabel = priceLabel;
      return this;
    }

    /**
     * Sets the value for {@code priceWithVat}.
     *
     * @param priceWithVat Product price including VAT.
     * @return This builder instance.
     */
    public Builder priceWithVat(Double priceWithVat) {
      this.priceWithVat = priceWithVat;
      return this;
    }

    /**
     * Sets the value for {@code quantity}.
     *
     * @param quantity Product quantity.
     * @return This builder instance.
     */
    public Builder quantity(Long quantity) {
      this.quantity = quantity;
      return this;
    }

    /**
     * Sets the value for {@code singleVatAmount}.
     *
     * @param singleVatAmount VAT amount for a single product.
     * @return This builder instance.
     */
    public Builder singleVatAmount(Double singleVatAmount) {
      this.singleVatAmount = singleVatAmount;
      return this;
    }

    /**
     * Sets the value for {@code totalPrice}.
     *
     * @param totalPrice Total price calculated as the product price multiplied by the quantity.
     * @return This builder instance.
     */
    public Builder totalPrice(Double totalPrice) {
      this.totalPrice = totalPrice;
      return this;
    }

    /**
     * Sets the value for {@code totalWithVat}.
     *
     * @param totalWithVat Total product price including VAT.
     * @return This builder instance.
     */
    public Builder totalWithVat(Double totalWithVat) {
      this.totalWithVat = totalWithVat;
      return this;
    }

    /**
     * Sets the value for {@code vatAmount}.
     *
     * @param vatAmount Total VAT amount for the product quantity.
     * @return This builder instance.
     */
    public Builder vatAmount(Double vatAmount) {
      this.vatAmount = vatAmount;
      return this;
    }

    /**
     * Sets the value for {@code vatRate}.
     *
     * @param vatRate VAT rate applied to the product price.
     * @return This builder instance.
     */
    public Builder vatRate(Double vatRate) {
      this.vatRate = vatRate;
      return this;
    }

    /**
     * Builds an immutable Product instance.
     *
     * @return Immutable Product.
     */
    public Product build() {
      return new Product(
          name,
          price,
          priceLabel,
          priceWithVat,
          quantity,
          singleVatAmount,
          totalPrice,
          totalWithVat,
          vatAmount,
          vatRate);
    }
  }
}
