// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** The current status of the transaction. */
public enum ReaderCheckoutStatusChangePayloadStatus {
  SUCCESSFUL("successful"),
  FAILED("failed");

  private final String value;

  ReaderCheckoutStatusChangePayloadStatus(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static ReaderCheckoutStatusChangePayloadStatus fromValue(String value) {
    if (value == null) {
      return null;
    }
    for (ReaderCheckoutStatusChangePayloadStatus entry : values()) {
      if (entry.value.equals(value)) {
        return entry;
      }
    }
    throw new IllegalArgumentException(
        "Unknown ReaderCheckoutStatusChangePayloadStatus value: " + value);
  }
}
