// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

public record ReaderPaymentRequestParams(
    com.sumup.sdk.models.Affiliate affiliate,

    /** Caller-supplied correlation identifier, used as the idempotency key. */
    String clientTransactionId,

    /** Optional tip amount in minor units, added on top of total_amount. */
    Long tipAmount,
    com.sumup.sdk.models.Amount totalAmount) {
  /**
   * Creates a builder for ReaderPaymentRequestParams.
   *
   * @return Builder that constructs immutable ReaderPaymentRequestParams instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for ReaderPaymentRequestParams instances. */
  public static final class Builder {
    private com.sumup.sdk.models.Affiliate affiliate;
    private String clientTransactionId;
    private Long tipAmount;
    private com.sumup.sdk.models.Amount totalAmount;

    private Builder() {}

    /**
     * Sets the value for {@code affiliate}.
     *
     * @param affiliate Value for the affiliate field.
     * @return This builder instance.
     */
    public Builder affiliate(com.sumup.sdk.models.Affiliate affiliate) {
      this.affiliate = affiliate;
      return this;
    }

    /**
     * Sets the value for {@code clientTransactionId}.
     *
     * @param clientTransactionId Caller-supplied correlation identifier, used as the idempotency
     *     key.
     * @return This builder instance.
     */
    public Builder clientTransactionId(String clientTransactionId) {
      this.clientTransactionId = clientTransactionId;
      return this;
    }

    /**
     * Sets the value for {@code tipAmount}.
     *
     * @param tipAmount Optional tip amount in minor units, added on top of total_amount.
     * @return This builder instance.
     */
    public Builder tipAmount(Long tipAmount) {
      this.tipAmount = tipAmount;
      return this;
    }

    /**
     * Sets the value for {@code totalAmount}.
     *
     * @param totalAmount Value for the totalAmount field.
     * @return This builder instance.
     */
    public Builder totalAmount(com.sumup.sdk.models.Amount totalAmount) {
      this.totalAmount = totalAmount;
      return this;
    }

    /**
     * Builds an immutable ReaderPaymentRequestParams instance.
     *
     * @return Immutable ReaderPaymentRequestParams.
     */
    public ReaderPaymentRequestParams build() {
      return new ReaderPaymentRequestParams(
          affiliate,
          Objects.requireNonNull(clientTransactionId, "clientTransactionId"),
          tipAmount,
          Objects.requireNonNull(totalAmount, "totalAmount"));
    }
  }
}
