// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

public record ReaderPaymentResponse(com.sumup.sdk.models.ReaderPaymentResponseData data) {
  /**
   * Creates a builder for ReaderPaymentResponse.
   *
   * @return Builder that constructs immutable ReaderPaymentResponse instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for ReaderPaymentResponse instances. */
  public static final class Builder {
    private com.sumup.sdk.models.ReaderPaymentResponseData data;

    private Builder() {}

    /**
     * Sets the value for {@code data}.
     *
     * @param data Value for the data field.
     * @return This builder instance.
     */
    public Builder data(com.sumup.sdk.models.ReaderPaymentResponseData data) {
      this.data = data;
      return this;
    }

    /**
     * Builds an immutable ReaderPaymentResponse instance.
     *
     * @return Immutable ReaderPaymentResponse.
     */
    public ReaderPaymentResponse build() {
      return new ReaderPaymentResponse(data);
    }
  }
}
