// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

/** The event payload. */
public record ReaderCheckoutStatusChangePayload(
    /** The unique client transaction id. It is the same returned by the Checkout. */
    java.util.UUID clientTransactionId,

    /** The merchant code associated with the transaction. */
    String merchantCode,

    /** The current status of the transaction. */
    com.sumup.sdk.models.ReaderCheckoutStatusChangePayloadStatus status,

    /** The transaction id. Deprecated: use `client_transaction_id` instead. */
    java.util.UUID transactionId) {
  /**
   * Creates a builder for ReaderCheckoutStatusChangePayload.
   *
   * @return Builder that constructs immutable ReaderCheckoutStatusChangePayload instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for ReaderCheckoutStatusChangePayload instances. */
  public static final class Builder {
    private java.util.UUID clientTransactionId;
    private String merchantCode;
    private com.sumup.sdk.models.ReaderCheckoutStatusChangePayloadStatus status;
    private java.util.UUID transactionId;

    private Builder() {}

    /**
     * Sets the value for {@code clientTransactionId}.
     *
     * @param clientTransactionId The unique client transaction id. It is the same returned by the
     *     Checkout.
     * @return This builder instance.
     */
    public Builder clientTransactionId(java.util.UUID clientTransactionId) {
      this.clientTransactionId = clientTransactionId;
      return this;
    }

    /**
     * Sets the value for {@code merchantCode}.
     *
     * @param merchantCode The merchant code associated with the transaction.
     * @return This builder instance.
     */
    public Builder merchantCode(String merchantCode) {
      this.merchantCode = merchantCode;
      return this;
    }

    /**
     * Sets the value for {@code status}.
     *
     * @param status The current status of the transaction.
     * @return This builder instance.
     */
    public Builder status(com.sumup.sdk.models.ReaderCheckoutStatusChangePayloadStatus status) {
      this.status = status;
      return this;
    }

    /**
     * Sets the value for {@code transactionId}.
     *
     * @param transactionId The transaction id. Deprecated: use `client_transaction_id` instead.
     * @return This builder instance.
     */
    public Builder transactionId(java.util.UUID transactionId) {
      this.transactionId = transactionId;
      return this;
    }

    /**
     * Builds an immutable ReaderCheckoutStatusChangePayload instance.
     *
     * @return Immutable ReaderCheckoutStatusChangePayload.
     */
    public ReaderCheckoutStatusChangePayload build() {
      return new ReaderCheckoutStatusChangePayload(
          Objects.requireNonNull(clientTransactionId, "clientTransactionId"),
          Objects.requireNonNull(merchantCode, "merchantCode"),
          Objects.requireNonNull(status, "status"),
          transactionId);
    }
  }
}
