// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/**
 * The pairing code is a 8 or 9 character alphanumeric string that is displayed on a SumUp Device
 * after initiating the pairing. It is used to link the physical device to the created pairing.
 */
public record ReaderPairingCode(String value) {}
