// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

/**
 * The status of the reader object gives information about the current state of the reader. Possible
 * values: - `unknown` - The reader status is unknown. - `processing` - The reader is created and
 * waits for the physical device to confirm the pairing. - `paired` - The reader is paired with a
 * merchant account and can be used with SumUp APIs. - `expired` - The pairing is expired and no
 * longer usable with the account. The resource needs to get recreated.
 */
public final class ReaderStatus {
  public static final ReaderStatus UNKNOWN = new ReaderStatus("unknown");
  public static final ReaderStatus PROCESSING = new ReaderStatus("processing");
  public static final ReaderStatus PAIRED = new ReaderStatus("paired");
  public static final ReaderStatus EXPIRED = new ReaderStatus("expired");

  private final String value;

  private ReaderStatus(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a ReaderStatus for a value not yet known to this SDK version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static ReaderStatus of(String value) {
    return new ReaderStatus(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static ReaderStatus fromValue(String value) {
    return value == null ? null : new ReaderStatus(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other || (other instanceof ReaderStatus that && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
