// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/**
 * The status of the reader object gives information about the current state of the reader. *
 * Possible values: * - `unknown` - The reader status is unknown. * - `processing` - The reader is
 * created and waits for the physical device to confirm the pairing. * - `paired` - The reader is
 * paired with a merchant account and can be used with SumUp APIs. * - `expired` - The pairing is
 * expired and no longer usable with the account. The resource needs to get recreated.
 */
public record ReaderStatus(String value) {
  /**
   * Creates a builder for ReaderStatus.
   *
   * @return Builder that constructs immutable ReaderStatus instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for ReaderStatus instances. */
  public static final class Builder {
    private String value;

    private Builder() {}

    /**
     * Sets the value for {@code value}.
     *
     * @param value Value for the value field.
     * @return This builder instance.
     */
    public Builder value(String value) {
      this.value = value;
      return this;
    }

    /**
     * Builds an immutable ReaderStatus instance.
     *
     * @return Immutable ReaderStatus.
     */
    public ReaderStatus build() {
      return new ReaderStatus(value);
    }
  }
}
