// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

/** The current status of the transaction. */
public final class ReaderCheckoutStatusChangePayloadStatus {
  public static final ReaderCheckoutStatusChangePayloadStatus SUCCESSFUL =
      new ReaderCheckoutStatusChangePayloadStatus("successful");
  public static final ReaderCheckoutStatusChangePayloadStatus FAILED =
      new ReaderCheckoutStatusChangePayloadStatus("failed");

  private final String value;

  private ReaderCheckoutStatusChangePayloadStatus(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a ReaderCheckoutStatusChangePayloadStatus for a value not yet known to this SDK
   * version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static ReaderCheckoutStatusChangePayloadStatus of(String value) {
    return new ReaderCheckoutStatusChangePayloadStatus(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static ReaderCheckoutStatusChangePayloadStatus fromValue(String value) {
    return value == null ? null : new ReaderCheckoutStatusChangePayloadStatus(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof ReaderCheckoutStatusChangePayloadStatus that
            && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
