// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The status of the reader object gives information about the current state of the reader. Possible
 * values: - `unknown` - The reader status is unknown. - `processing` - The reader is created and
 * waits for the physical device to confirm the pairing. - `paired` - The reader is paired with a
 * merchant account and can be used with SumUp APIs. - `expired` - The pairing is expired and no
 * longer usable with the account. The resource needs to get recreated.
 */
public enum ReaderStatus {
  UNKNOWN("unknown"),
  PROCESSING("processing"),
  PAIRED("paired"),
  EXPIRED("expired");

  private final String value;

  ReaderStatus(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static ReaderStatus fromValue(String value) {
    if (value == null) {
      return null;
    }
    for (ReaderStatus entry : values()) {
      if (entry.value.equals(value)) {
        return entry;
      }
    }
    throw new IllegalArgumentException("Unknown ReaderStatus value: " + value);
  }
}
