// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** Receipt merchant data */
public record ReceiptMerchantData(
    String locale, com.sumup.sdk.models.ReceiptMerchantDataMerchantProfile merchantProfile) {

  /**
   * Creates a builder for ReceiptMerchantData.
   *
   * @return Builder that constructs immutable ReceiptMerchantData instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for ReceiptMerchantData instances. */
  public static final class Builder {
    private String locale;
    private com.sumup.sdk.models.ReceiptMerchantDataMerchantProfile merchantProfile;

    private Builder() {}

    /**
     * Sets the value for {@code locale}.
     *
     * @param locale Value for the locale field.
     * @return This builder instance.
     */
    public Builder locale(String locale) {
      this.locale = locale;
      return this;
    }

    /**
     * Sets the value for {@code merchantProfile}.
     *
     * @param merchantProfile Value for the merchantProfile field.
     * @return This builder instance.
     */
    public Builder merchantProfile(
        com.sumup.sdk.models.ReceiptMerchantDataMerchantProfile merchantProfile) {
      this.merchantProfile = merchantProfile;
      return this;
    }

    /**
     * Builds an immutable ReceiptMerchantData instance.
     *
     * @return Immutable ReceiptMerchantData.
     */
    public ReceiptMerchantData build() {
      return new ReceiptMerchantData(locale, merchantProfile);
    }
  }
}
