// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** Transaction event details as rendered on the receipt. */
public record ReceiptEvent(
    /** Amount of the event. */
    String amount,

    /** Unique ID of the transaction event. */
    com.sumup.sdk.models.EventId id,

    /** Receipt number associated with the event. */
    String receiptNo,

    /** Status of the transaction event. */
    com.sumup.sdk.models.EventStatus status,

    /** Date and time of the transaction event. */
    java.time.OffsetDateTime timestamp,

    /** Unique ID of the transaction. */
    com.sumup.sdk.models.TransactionId transactionId,

    /** Type of the transaction event. */
    com.sumup.sdk.models.EventType type) {
  /**
   * Creates a builder for ReceiptEvent.
   *
   * @return Builder that constructs immutable ReceiptEvent instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for ReceiptEvent instances. */
  public static final class Builder {
    private String amount;
    private com.sumup.sdk.models.EventId id;
    private String receiptNo;
    private com.sumup.sdk.models.EventStatus status;
    private java.time.OffsetDateTime timestamp;
    private com.sumup.sdk.models.TransactionId transactionId;
    private com.sumup.sdk.models.EventType type;

    private Builder() {}

    /**
     * Sets the value for {@code amount}.
     *
     * @param amount Amount of the event.
     * @return This builder instance.
     */
    public Builder amount(String amount) {
      this.amount = amount;
      return this;
    }

    /**
     * Sets the value for {@code id}.
     *
     * @param id Unique ID of the transaction event.
     * @return This builder instance.
     */
    public Builder id(com.sumup.sdk.models.EventId id) {
      this.id = id;
      return this;
    }

    /**
     * Sets the value for {@code receiptNo}.
     *
     * @param receiptNo Receipt number associated with the event.
     * @return This builder instance.
     */
    public Builder receiptNo(String receiptNo) {
      this.receiptNo = receiptNo;
      return this;
    }

    /**
     * Sets the value for {@code status}.
     *
     * @param status Status of the transaction event.
     * @return This builder instance.
     */
    public Builder status(com.sumup.sdk.models.EventStatus status) {
      this.status = status;
      return this;
    }

    /**
     * Sets the value for {@code timestamp}.
     *
     * @param timestamp Date and time of the transaction event.
     * @return This builder instance.
     */
    public Builder timestamp(java.time.OffsetDateTime timestamp) {
      this.timestamp = timestamp;
      return this;
    }

    /**
     * Sets the value for {@code transactionId}.
     *
     * @param transactionId Unique ID of the transaction.
     * @return This builder instance.
     */
    public Builder transactionId(com.sumup.sdk.models.TransactionId transactionId) {
      this.transactionId = transactionId;
      return this;
    }

    /**
     * Sets the value for {@code type}.
     *
     * @param type Type of the transaction event.
     * @return This builder instance.
     */
    public Builder type(com.sumup.sdk.models.EventType type) {
      this.type = type;
      return this;
    }

    /**
     * Builds an immutable ReceiptEvent instance.
     *
     * @return Immutable ReceiptEvent.
     */
    public ReceiptEvent build() {
      return new ReceiptEvent(amount, id, receiptNo, status, timestamp, transactionId, type);
    }
  }
}
