// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Debit/Credit. */
public enum ReceiptTransactionProcessAs {
  CREDIT("CREDIT"),
  DEBIT("DEBIT");

  private final String value;

  ReceiptTransactionProcessAs(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static ReceiptTransactionProcessAs fromValue(String value) {
    if (value == null) {
      return null;
    }
    for (ReceiptTransactionProcessAs entry : values()) {
      if (entry.value.equals(value)) {
        return entry;
      }
    }
    throw new IllegalArgumentException("Unknown ReceiptTransactionProcessAs value: " + value);
  }
}
