// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** Business address of the merchant. */
public record ReceiptMerchantDataMerchantProfileAddress(
    /** First line of the merchant address. */
    String addressLine1,

    /** Second line of the merchant address. */
    String addressLine2,

    /** City of the merchant address. */
    String city,

    /** Two-letter ISO 3166-1 alpha-2 country code of the merchant address. */
    String country,

    /** English name of the country in the merchant address. */
    String countryEnName,

    /** Localized name of the country in the merchant address. */
    String countryNativeName,

    /** Landline phone number of the merchant. */
    String landline,

    /** Postal code of the merchant address. */
    String postCode,

    /** Region or state of the merchant address. */
    String regionName) {
  /**
   * Creates a builder for ReceiptMerchantDataMerchantProfileAddress.
   *
   * @return Builder that constructs immutable ReceiptMerchantDataMerchantProfileAddress instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for ReceiptMerchantDataMerchantProfileAddress instances. */
  public static final class Builder {
    private String addressLine1;
    private String addressLine2;
    private String city;
    private String country;
    private String countryEnName;
    private String countryNativeName;
    private String landline;
    private String postCode;
    private String regionName;

    private Builder() {}

    /**
     * Sets the value for {@code addressLine1}.
     *
     * @param addressLine1 First line of the merchant address.
     * @return This builder instance.
     */
    public Builder addressLine1(String addressLine1) {
      this.addressLine1 = addressLine1;
      return this;
    }

    /**
     * Sets the value for {@code addressLine2}.
     *
     * @param addressLine2 Second line of the merchant address.
     * @return This builder instance.
     */
    public Builder addressLine2(String addressLine2) {
      this.addressLine2 = addressLine2;
      return this;
    }

    /**
     * Sets the value for {@code city}.
     *
     * @param city City of the merchant address.
     * @return This builder instance.
     */
    public Builder city(String city) {
      this.city = city;
      return this;
    }

    /**
     * Sets the value for {@code country}.
     *
     * @param country Two-letter ISO 3166-1 alpha-2 country code of the merchant address.
     * @return This builder instance.
     */
    public Builder country(String country) {
      this.country = country;
      return this;
    }

    /**
     * Sets the value for {@code countryEnName}.
     *
     * @param countryEnName English name of the country in the merchant address.
     * @return This builder instance.
     */
    public Builder countryEnName(String countryEnName) {
      this.countryEnName = countryEnName;
      return this;
    }

    /**
     * Sets the value for {@code countryNativeName}.
     *
     * @param countryNativeName Localized name of the country in the merchant address.
     * @return This builder instance.
     */
    public Builder countryNativeName(String countryNativeName) {
      this.countryNativeName = countryNativeName;
      return this;
    }

    /**
     * Sets the value for {@code landline}.
     *
     * @param landline Landline phone number of the merchant.
     * @return This builder instance.
     */
    public Builder landline(String landline) {
      this.landline = landline;
      return this;
    }

    /**
     * Sets the value for {@code postCode}.
     *
     * @param postCode Postal code of the merchant address.
     * @return This builder instance.
     */
    public Builder postCode(String postCode) {
      this.postCode = postCode;
      return this;
    }

    /**
     * Sets the value for {@code regionName}.
     *
     * @param regionName Region or state of the merchant address.
     * @return This builder instance.
     */
    public Builder regionName(String regionName) {
      this.regionName = regionName;
      return this;
    }

    /**
     * Builds an immutable ReceiptMerchantDataMerchantProfileAddress instance.
     *
     * @return Immutable ReceiptMerchantDataMerchantProfileAddress.
     */
    public ReceiptMerchantDataMerchantProfileAddress build() {
      return new ReceiptMerchantDataMerchantProfileAddress(
          addressLine1,
          addressLine2,
          city,
          country,
          countryEnName,
          countryNativeName,
          landline,
          postCode,
          regionName);
    }
  }
}
