// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** Acquirer-specific metadata related to the card authorization. */
public record ReceiptAcquirerData(
    String authorizationCode, String localTime, String returnCode, String tid) {

  /**
   * Creates a builder for ReceiptAcquirerData.
   *
   * @return Builder that constructs immutable ReceiptAcquirerData instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for ReceiptAcquirerData instances. */
  public static final class Builder {
    private String authorizationCode;
    private String localTime;
    private String returnCode;
    private String tid;

    private Builder() {}

    /**
     * Sets the value for {@code authorizationCode}.
     *
     * @param authorizationCode Value for the authorizationCode field.
     * @return This builder instance.
     */
    public Builder authorizationCode(String authorizationCode) {
      this.authorizationCode = authorizationCode;
      return this;
    }

    /**
     * Sets the value for {@code localTime}.
     *
     * @param localTime Value for the localTime field.
     * @return This builder instance.
     */
    public Builder localTime(String localTime) {
      this.localTime = localTime;
      return this;
    }

    /**
     * Sets the value for {@code returnCode}.
     *
     * @param returnCode Value for the returnCode field.
     * @return This builder instance.
     */
    public Builder returnCode(String returnCode) {
      this.returnCode = returnCode;
      return this;
    }

    /**
     * Sets the value for {@code tid}.
     *
     * @param tid Value for the tid field.
     * @return This builder instance.
     */
    public Builder tid(String tid) {
      this.tid = tid;
      return this;
    }

    /**
     * Builds an immutable ReceiptAcquirerData instance.
     *
     * @return Immutable ReceiptAcquirerData.
     */
    public ReceiptAcquirerData build() {
      return new ReceiptAcquirerData(authorizationCode, localTime, returnCode, tid);
    }
  }
}
