// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/**
 * The type of the membership resource. Possible values are: * `merchant` - merchant account(s) *
 * `organization` - organization(s)
 */
public record ResourceType(String value) {}
