// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

/** Status of a device */
public record StatusResponse(com.sumup.sdk.models.StatusResponseData data) {
  /**
   * Creates a builder for StatusResponse.
   *
   * @return Builder that constructs immutable StatusResponse instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for StatusResponse instances. */
  public static final class Builder {
    private com.sumup.sdk.models.StatusResponseData data;

    private Builder() {}

    /**
     * Sets the value for {@code data}.
     *
     * @param data Value for the data field.
     * @return This builder instance.
     */
    public Builder data(com.sumup.sdk.models.StatusResponseData data) {
      this.data = data;
      return this;
    }

    /**
     * Builds an immutable StatusResponse instance.
     *
     * @return Immutable StatusResponse.
     */
    public StatusResponse build() {
      return new StatusResponse(Objects.requireNonNull(data, "data"));
    }
  }
}
