// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

/** Latest state of the device */
public final class StatusResponseDataState {
  public static final StatusResponseDataState IDLE = new StatusResponseDataState("IDLE");
  public static final StatusResponseDataState SELECTING_TIP =
      new StatusResponseDataState("SELECTING_TIP");
  public static final StatusResponseDataState WAITING_FOR_CARD =
      new StatusResponseDataState("WAITING_FOR_CARD");
  public static final StatusResponseDataState WAITING_FOR_PIN =
      new StatusResponseDataState("WAITING_FOR_PIN");
  public static final StatusResponseDataState WAITING_FOR_SIGNATURE =
      new StatusResponseDataState("WAITING_FOR_SIGNATURE");
  public static final StatusResponseDataState UPDATING_FIRMWARE =
      new StatusResponseDataState("UPDATING_FIRMWARE");

  private final String value;

  private StatusResponseDataState(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a StatusResponseDataState for a value not yet known to this SDK version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static StatusResponseDataState of(String value) {
    return new StatusResponseDataState(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static StatusResponseDataState fromValue(String value) {
    return value == null ? null : new StatusResponseDataState(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof StatusResponseDataState that && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
