// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import java.util.Objects;

public record StatusResponseData(
    /** Battery level percentage */
    Float batteryLevel,

    /** Battery temperature in Celsius */
    Long batteryTemperature,

    /** Type of connection used by the device */
    com.sumup.sdk.models.StatusResponseDataConnectionType connectionType,

    /** Firmware version of the device */
    String firmwareVersion,

    /** Timestamp of the last activity from the device */
    java.time.OffsetDateTime lastActivity,

    /** Latest state of the device */
    com.sumup.sdk.models.StatusResponseDataState state,

    /** Status of a device */
    com.sumup.sdk.models.StatusResponseDataStatus status) {
  /**
   * Creates a builder for StatusResponseData.
   *
   * @return Builder that constructs immutable StatusResponseData instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for StatusResponseData instances. */
  public static final class Builder {
    private Float batteryLevel;
    private Long batteryTemperature;
    private com.sumup.sdk.models.StatusResponseDataConnectionType connectionType;
    private String firmwareVersion;
    private java.time.OffsetDateTime lastActivity;
    private com.sumup.sdk.models.StatusResponseDataState state;
    private com.sumup.sdk.models.StatusResponseDataStatus status;

    private Builder() {}

    /**
     * Sets the value for {@code batteryLevel}.
     *
     * @param batteryLevel Battery level percentage
     * @return This builder instance.
     */
    public Builder batteryLevel(Float batteryLevel) {
      this.batteryLevel = batteryLevel;
      return this;
    }

    /**
     * Sets the value for {@code batteryTemperature}.
     *
     * @param batteryTemperature Battery temperature in Celsius
     * @return This builder instance.
     */
    public Builder batteryTemperature(Long batteryTemperature) {
      this.batteryTemperature = batteryTemperature;
      return this;
    }

    /**
     * Sets the value for {@code connectionType}.
     *
     * @param connectionType Type of connection used by the device
     * @return This builder instance.
     */
    public Builder connectionType(
        com.sumup.sdk.models.StatusResponseDataConnectionType connectionType) {
      this.connectionType = connectionType;
      return this;
    }

    /**
     * Sets the value for {@code firmwareVersion}.
     *
     * @param firmwareVersion Firmware version of the device
     * @return This builder instance.
     */
    public Builder firmwareVersion(String firmwareVersion) {
      this.firmwareVersion = firmwareVersion;
      return this;
    }

    /**
     * Sets the value for {@code lastActivity}.
     *
     * @param lastActivity Timestamp of the last activity from the device
     * @return This builder instance.
     */
    public Builder lastActivity(java.time.OffsetDateTime lastActivity) {
      this.lastActivity = lastActivity;
      return this;
    }

    /**
     * Sets the value for {@code state}.
     *
     * @param state Latest state of the device
     * @return This builder instance.
     */
    public Builder state(com.sumup.sdk.models.StatusResponseDataState state) {
      this.state = state;
      return this;
    }

    /**
     * Sets the value for {@code status}.
     *
     * @param status Status of a device
     * @return This builder instance.
     */
    public Builder status(com.sumup.sdk.models.StatusResponseDataStatus status) {
      this.status = status;
      return this;
    }

    /**
     * Builds an immutable StatusResponseData instance.
     *
     * @return Immutable StatusResponseData.
     */
    public StatusResponseData build() {
      return new StatusResponseData(
          batteryLevel,
          batteryTemperature,
          connectionType,
          firmwareVersion,
          lastActivity,
          state,
          Objects.requireNonNull(status, "status"));
    }
  }
}
