// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Latest state of the device */
public enum StatusResponseDataState {
  IDLE("IDLE"),
  SELECTING_TIP("SELECTING_TIP"),
  WAITING_FOR_CARD("WAITING_FOR_CARD"),
  WAITING_FOR_PIN("WAITING_FOR_PIN"),
  WAITING_FOR_SIGNATURE("WAITING_FOR_SIGNATURE"),
  UPDATING_FIRMWARE("UPDATING_FIRMWARE");

  private final String value;

  StatusResponseDataState(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static StatusResponseDataState fromValue(String value) {
    if (value == null) {
      return null;
    }
    for (StatusResponseDataState entry : values()) {
      if (entry.value.equals(value)) {
        return entry;
      }
    }
    throw new IllegalArgumentException("Unknown StatusResponseDataState value: " + value);
  }
}
