// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** TimeOffset Details */
public record TimeoffsetDetails(
    /** Daylight Saving Time */
    Boolean dst,

    /** UTC offset */
    Double offset,

    /** Postal code */
    String postCode) {
  /**
   * Creates a builder for TimeoffsetDetails.
   *
   * @return Builder that constructs immutable TimeoffsetDetails instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for TimeoffsetDetails instances. */
  public static final class Builder {
    private Boolean dst;
    private Double offset;
    private String postCode;

    private Builder() {}

    /**
     * Sets the value for {@code dst}.
     *
     * @param dst Daylight Saving Time
     * @return This builder instance.
     */
    public Builder dst(Boolean dst) {
      this.dst = dst;
      return this;
    }

    /**
     * Sets the value for {@code offset}.
     *
     * @param offset UTC offset
     * @return This builder instance.
     */
    public Builder offset(Double offset) {
      this.offset = offset;
      return this;
    }

    /**
     * Sets the value for {@code postCode}.
     *
     * @param postCode Postal code
     * @return This builder instance.
     */
    public Builder postCode(String postCode) {
      this.postCode = postCode;
      return this;
    }

    /**
     * Builds an immutable TimeoffsetDetails instance.
     *
     * @return Immutable TimeoffsetDetails.
     */
    public TimeoffsetDetails build() {
      return new TimeoffsetDetails(dst, offset, postCode);
    }
  }
}
