// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** Date and time of the transaction event. */
public record TimestampEvent(java.time.OffsetDateTime value) {
  /**
   * Creates a builder for TimestampEvent.
   *
   * @return Builder that constructs immutable TimestampEvent instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for TimestampEvent instances. */
  public static final class Builder {
    private java.time.OffsetDateTime value;

    private Builder() {}

    /**
     * Sets the value for {@code value}.
     *
     * @param value Value for the value field.
     * @return This builder instance.
     */
    public Builder value(java.time.OffsetDateTime value) {
      this.value = value;
      return this;
    }

    /**
     * Builds an immutable TimestampEvent instance.
     *
     * @return Immutable TimestampEvent.
     */
    public TimestampEvent build() {
      return new TimestampEvent(value);
    }
  }
}
