// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

/** Simple name of the payment type. */
public final class TransactionFullSimplePaymentType {
  public static final TransactionFullSimplePaymentType CASH =
      new TransactionFullSimplePaymentType("CASH");
  public static final TransactionFullSimplePaymentType CC_SIGNATURE =
      new TransactionFullSimplePaymentType("CC_SIGNATURE");
  public static final TransactionFullSimplePaymentType ELV =
      new TransactionFullSimplePaymentType("ELV");
  public static final TransactionFullSimplePaymentType ELV_WITHOUT_SIGNATURE =
      new TransactionFullSimplePaymentType("ELV_WITHOUT_SIGNATURE");
  public static final TransactionFullSimplePaymentType CC_CUSTOMER_ENTERED =
      new TransactionFullSimplePaymentType("CC_CUSTOMER_ENTERED");
  public static final TransactionFullSimplePaymentType MANUAL_ENTRY =
      new TransactionFullSimplePaymentType("MANUAL_ENTRY");
  public static final TransactionFullSimplePaymentType EMV =
      new TransactionFullSimplePaymentType("EMV");
  public static final TransactionFullSimplePaymentType RECURRING =
      new TransactionFullSimplePaymentType("RECURRING");
  public static final TransactionFullSimplePaymentType BALANCE =
      new TransactionFullSimplePaymentType("BALANCE");
  public static final TransactionFullSimplePaymentType MOTO =
      new TransactionFullSimplePaymentType("MOTO");
  public static final TransactionFullSimplePaymentType BOLETO =
      new TransactionFullSimplePaymentType("BOLETO");
  public static final TransactionFullSimplePaymentType APM =
      new TransactionFullSimplePaymentType("APM");
  public static final TransactionFullSimplePaymentType BITCOIN =
      new TransactionFullSimplePaymentType("BITCOIN");
  public static final TransactionFullSimplePaymentType CARD =
      new TransactionFullSimplePaymentType("CARD");

  private final String value;

  private TransactionFullSimplePaymentType(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a TransactionFullSimplePaymentType for a value not yet known to this SDK version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static TransactionFullSimplePaymentType of(String value) {
    return new TransactionFullSimplePaymentType(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static TransactionFullSimplePaymentType fromValue(String value) {
    return value == null ? null : new TransactionFullSimplePaymentType(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof TransactionFullSimplePaymentType that
            && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
