// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

public record TransactionFullVatRatesItem(
    /** Gross amount of products having this VAT rate applied. */
    Double gross,

    /** NET amount of products having this VAT rate applied. */
    Double net,

    /** VAT rate. */
    Double rate,

    /** VAT amount of this rate applied. */
    Double vat) {
  /**
   * Creates a builder for TransactionFullVatRatesItem.
   *
   * @return Builder that constructs immutable TransactionFullVatRatesItem instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for TransactionFullVatRatesItem instances. */
  public static final class Builder {
    private Double gross;
    private Double net;
    private Double rate;
    private Double vat;

    private Builder() {}

    /**
     * Sets the value for {@code gross}.
     *
     * @param gross Gross amount of products having this VAT rate applied.
     * @return This builder instance.
     */
    public Builder gross(Double gross) {
      this.gross = gross;
      return this;
    }

    /**
     * Sets the value for {@code net}.
     *
     * @param net NET amount of products having this VAT rate applied.
     * @return This builder instance.
     */
    public Builder net(Double net) {
      this.net = net;
      return this;
    }

    /**
     * Sets the value for {@code rate}.
     *
     * @param rate VAT rate.
     * @return This builder instance.
     */
    public Builder rate(Double rate) {
      this.rate = rate;
      return this;
    }

    /**
     * Sets the value for {@code vat}.
     *
     * @param vat VAT amount of this rate applied.
     * @return This builder instance.
     */
    public Builder vat(Double vat) {
      this.vat = vat;
      return this;
    }

    /**
     * Builds an immutable TransactionFullVatRatesItem instance.
     *
     * @return Immutable TransactionFullVatRatesItem.
     */
    public TransactionFullVatRatesItem build() {
      return new TransactionFullVatRatesItem(gross, net, rate, vat);
    }
  }
}
