// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

/** Type of the transaction for the registered user specified in the `user` property. */
public final class TransactionHistoryType {
  public static final TransactionHistoryType PAYMENT = new TransactionHistoryType("PAYMENT");
  public static final TransactionHistoryType REFUND = new TransactionHistoryType("REFUND");
  public static final TransactionHistoryType CHARGE_BACK =
      new TransactionHistoryType("CHARGE_BACK");

  private final String value;

  private TransactionHistoryType(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a TransactionHistoryType for a value not yet known to this SDK version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static TransactionHistoryType of(String value) {
    return new TransactionHistoryType(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static TransactionHistoryType fromValue(String value) {
    return value == null ? null : new TransactionHistoryType(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof TransactionHistoryType that && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
