// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

/** Payout type. */
public final class TransactionHistoryPayoutType {
  public static final TransactionHistoryPayoutType BANK_ACCOUNT =
      new TransactionHistoryPayoutType("BANK_ACCOUNT");
  public static final TransactionHistoryPayoutType PREPAID_CARD =
      new TransactionHistoryPayoutType("PREPAID_CARD");

  private final String value;

  private TransactionHistoryPayoutType(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a TransactionHistoryPayoutType for a value not yet known to this SDK version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static TransactionHistoryPayoutType of(String value) {
    return new TransactionHistoryPayoutType(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static TransactionHistoryPayoutType fromValue(String value) {
    return value == null ? null : new TransactionHistoryPayoutType(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof TransactionHistoryPayoutType that && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
