// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Current status of the transaction. */
public enum TransactionBaseStatus {
  SUCCESSFUL("SUCCESSFUL"),
  CANCELLED("CANCELLED"),
  FAILED("FAILED"),
  PENDING("PENDING");

  private final String value;

  TransactionBaseStatus(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static TransactionBaseStatus fromValue(String value) {
    if (value == null) {
      return null;
    }
    for (TransactionBaseStatus entry : values()) {
      if (entry.value.equals(value)) {
        return entry;
      }
    }
    throw new IllegalArgumentException("Unknown TransactionBaseStatus value: " + value);
  }
}
