// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** Full transaction resource with checkout, payout, and event details. */
public record TransactionFull(com.sumup.sdk.models.TransactionBase value) {}
