// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

/**
 * Status of the transaction event. Not every value is used for every event type. - `PENDING`: The
 * event has been created but is not final yet. Used for events that are still being processed and
 * whose final outcome is not known yet. - `SCHEDULED`: The event is planned for a future payout
 * cycle but has not been executed yet. This applies to payout events before money is actually sent
 * out. - `RECONCILED`: The underlying payment has been matched with settlement data and is ready to
 * continue through payout processing, but the funds have not been paid out yet. This applies to
 * payout events. - `PAID_OUT`: The payout event has been completed and the funds were included in a
 * merchant payout. - `REFUNDED`: A refund event has been accepted and recorded in the refund flow.
 * This is the status returned for refund events once the transaction amount is being or has been
 * returned to the payer. - `SUCCESSFUL`: The event completed successfully. Use this as the generic
 * terminal success status for event types that do not expose a more specific business outcome such
 * as `PAID_OUT` or `REFUNDED`. - `FAILED`: The event could not be completed. Typical examples are a
 * payout that could not be executed or an event that was rejected during processing.
 */
public final class TransactionEventStatus {
  public static final TransactionEventStatus FAILED = new TransactionEventStatus("FAILED");
  public static final TransactionEventStatus PAID_OUT = new TransactionEventStatus("PAID_OUT");
  public static final TransactionEventStatus PENDING = new TransactionEventStatus("PENDING");
  public static final TransactionEventStatus RECONCILED = new TransactionEventStatus("RECONCILED");
  public static final TransactionEventStatus REFUNDED = new TransactionEventStatus("REFUNDED");
  public static final TransactionEventStatus SCHEDULED = new TransactionEventStatus("SCHEDULED");
  public static final TransactionEventStatus SUCCESSFUL = new TransactionEventStatus("SUCCESSFUL");

  private final String value;

  private TransactionEventStatus(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a TransactionEventStatus for a value not yet known to this SDK version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static TransactionEventStatus of(String value) {
    return new TransactionEventStatus(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static TransactionEventStatus fromValue(String value) {
    return value == null ? null : new TransactionEventStatus(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof TransactionEventStatus that && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
