// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** Core details shared by transaction resources. */
public record TransactionBase(
    /** Total amount of the transaction. */
    Float amount,

    /**
     * Three-letter [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code of the amount.
     */
    com.sumup.sdk.models.Currency currency,

    /** Unique identifier of the transaction. */
    String id,

    /** Number of installments for a deferred payment. */
    Long installmentsCount,

    /** Payment type used for the transaction. */
    com.sumup.sdk.models.PaymentType paymentType,

    /**
     * Current status of the transaction. - `PENDING`: The transaction has been created but its
     * final outcome is not known yet. - `SUCCESSFUL`: The transaction completed successfully. -
     * `CANCELLED`: The transaction was cancelled or otherwise reversed before completion. -
     * `FAILED`: The transaction attempt did not complete successfully. - `REFUNDED`: The
     * transaction was refunded in full or in part.
     */
    com.sumup.sdk.models.TransactionStatus status,

    /** The timestamp of when the transaction was created. */
    java.time.OffsetDateTime timestamp,

    /**
     * Transaction code returned by the acquirer/processing entity after processing the transaction.
     */
    String transactionCode) {
  /**
   * Creates a builder for TransactionBase.
   *
   * @return Builder that constructs immutable TransactionBase instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for TransactionBase instances. */
  public static final class Builder {
    private Float amount;
    private com.sumup.sdk.models.Currency currency;
    private String id;
    private Long installmentsCount;
    private com.sumup.sdk.models.PaymentType paymentType;
    private com.sumup.sdk.models.TransactionStatus status;
    private java.time.OffsetDateTime timestamp;
    private String transactionCode;

    private Builder() {}

    /**
     * Sets the value for {@code amount}.
     *
     * @param amount Total amount of the transaction.
     * @return This builder instance.
     */
    public Builder amount(Float amount) {
      this.amount = amount;
      return this;
    }

    /**
     * Sets the value for {@code currency}.
     *
     * @param currency Three-letter [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code
     *     of the amount.
     * @return This builder instance.
     */
    public Builder currency(com.sumup.sdk.models.Currency currency) {
      this.currency = currency;
      return this;
    }

    /**
     * Sets the value for {@code id}.
     *
     * @param id Unique identifier of the transaction.
     * @return This builder instance.
     */
    public Builder id(String id) {
      this.id = id;
      return this;
    }

    /**
     * Sets the value for {@code installmentsCount}.
     *
     * @param installmentsCount Number of installments for a deferred payment.
     * @return This builder instance.
     */
    public Builder installmentsCount(Long installmentsCount) {
      this.installmentsCount = installmentsCount;
      return this;
    }

    /**
     * Sets the value for {@code paymentType}.
     *
     * @param paymentType Payment type used for the transaction.
     * @return This builder instance.
     */
    public Builder paymentType(com.sumup.sdk.models.PaymentType paymentType) {
      this.paymentType = paymentType;
      return this;
    }

    /**
     * Sets the value for {@code status}.
     *
     * @param status Current status of the transaction. - `PENDING`: The transaction has been
     *     created but its final outcome is not known yet. - `SUCCESSFUL`: The transaction completed
     *     successfully. - `CANCELLED`: The transaction was cancelled or otherwise reversed before
     *     completion. - `FAILED`: The transaction attempt did not complete successfully. -
     *     `REFUNDED`: The transaction was refunded in full or in part.
     * @return This builder instance.
     */
    public Builder status(com.sumup.sdk.models.TransactionStatus status) {
      this.status = status;
      return this;
    }

    /**
     * Sets the value for {@code timestamp}.
     *
     * @param timestamp The timestamp of when the transaction was created.
     * @return This builder instance.
     */
    public Builder timestamp(java.time.OffsetDateTime timestamp) {
      this.timestamp = timestamp;
      return this;
    }

    /**
     * Sets the value for {@code transactionCode}.
     *
     * @param transactionCode Transaction code returned by the acquirer/processing entity after
     *     processing the transaction.
     * @return This builder instance.
     */
    public Builder transactionCode(String transactionCode) {
      this.transactionCode = transactionCode;
      return this;
    }

    /**
     * Builds an immutable TransactionBase instance.
     *
     * @return Immutable TransactionBase.
     */
    public TransactionBase build() {
      return new TransactionBase(
          amount, currency, id, installmentsCount, paymentType, status, timestamp, transactionCode);
    }
  }
}
