// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

public record TransactionMixinHistory(
    /** Payout plan of the registered user at the time when the transaction was made. */
    String payoutPlan,

    /** Number of payouts that are made to the registered user specified in the `user` property. */
    Long payoutsReceived,

    /** Total number of payouts to the registered user specified in the `user` property. */
    Long payoutsTotal,

    /**
     * Short description of the payment. The value is taken from the `description` property of the
     * related checkout resource.
     */
    String productSummary) {
  /**
   * Creates a builder for TransactionMixinHistory.
   *
   * @return Builder that constructs immutable TransactionMixinHistory instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for TransactionMixinHistory instances. */
  public static final class Builder {
    private String payoutPlan;
    private Long payoutsReceived;
    private Long payoutsTotal;
    private String productSummary;

    private Builder() {}

    /**
     * Sets the value for {@code payoutPlan}.
     *
     * @param payoutPlan Payout plan of the registered user at the time when the transaction was
     *     made.
     * @return This builder instance.
     */
    public Builder payoutPlan(String payoutPlan) {
      this.payoutPlan = payoutPlan;
      return this;
    }

    /**
     * Sets the value for {@code payoutsReceived}.
     *
     * @param payoutsReceived Number of payouts that are made to the registered user specified in
     *     the `user` property.
     * @return This builder instance.
     */
    public Builder payoutsReceived(Long payoutsReceived) {
      this.payoutsReceived = payoutsReceived;
      return this;
    }

    /**
     * Sets the value for {@code payoutsTotal}.
     *
     * @param payoutsTotal Total number of payouts to the registered user specified in the `user`
     *     property.
     * @return This builder instance.
     */
    public Builder payoutsTotal(Long payoutsTotal) {
      this.payoutsTotal = payoutsTotal;
      return this;
    }

    /**
     * Sets the value for {@code productSummary}.
     *
     * @param productSummary Short description of the payment. The value is taken from the
     *     `description` property of the related checkout resource.
     * @return This builder instance.
     */
    public Builder productSummary(String productSummary) {
      this.productSummary = productSummary;
      return this;
    }

    /**
     * Builds an immutable TransactionMixinHistory instance.
     *
     * @return Immutable TransactionMixinHistory.
     */
    public TransactionMixinHistory build() {
      return new TransactionMixinHistory(payoutPlan, payoutsReceived, payoutsTotal, productSummary);
    }
  }
}
