// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** Details of a transaction event. */
public record TransactionEvent(
    /** Amount of the event. */
    Float amount,

    /** Date when the transaction event occurred. */
    java.time.LocalDate date,

    /** Date when the transaction event is due to occur. */
    java.time.LocalDate dueDate,

    /** Type of the transaction event. */
    com.sumup.sdk.models.EventType eventType,

    /** Unique ID of the transaction event. */
    com.sumup.sdk.models.EventId id,

    /**
     * Consecutive number of the installment that is paid. Applicable only payout events, i.e.
     * `event_type = PAYOUT`.
     */
    Long installmentNumber,

    /** Status of the transaction event. */
    com.sumup.sdk.models.EventStatus status,

    /** Date and time of the transaction event. */
    java.time.OffsetDateTime timestamp) {
  /**
   * Creates a builder for TransactionEvent.
   *
   * @return Builder that constructs immutable TransactionEvent instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for TransactionEvent instances. */
  public static final class Builder {
    private Float amount;
    private java.time.LocalDate date;
    private java.time.LocalDate dueDate;
    private com.sumup.sdk.models.EventType eventType;
    private com.sumup.sdk.models.EventId id;
    private Long installmentNumber;
    private com.sumup.sdk.models.EventStatus status;
    private java.time.OffsetDateTime timestamp;

    private Builder() {}

    /**
     * Sets the value for {@code amount}.
     *
     * @param amount Amount of the event.
     * @return This builder instance.
     */
    public Builder amount(Float amount) {
      this.amount = amount;
      return this;
    }

    /**
     * Sets the value for {@code date}.
     *
     * @param date Date when the transaction event occurred.
     * @return This builder instance.
     */
    public Builder date(java.time.LocalDate date) {
      this.date = date;
      return this;
    }

    /**
     * Sets the value for {@code dueDate}.
     *
     * @param dueDate Date when the transaction event is due to occur.
     * @return This builder instance.
     */
    public Builder dueDate(java.time.LocalDate dueDate) {
      this.dueDate = dueDate;
      return this;
    }

    /**
     * Sets the value for {@code eventType}.
     *
     * @param eventType Type of the transaction event.
     * @return This builder instance.
     */
    public Builder eventType(com.sumup.sdk.models.EventType eventType) {
      this.eventType = eventType;
      return this;
    }

    /**
     * Sets the value for {@code id}.
     *
     * @param id Unique ID of the transaction event.
     * @return This builder instance.
     */
    public Builder id(com.sumup.sdk.models.EventId id) {
      this.id = id;
      return this;
    }

    /**
     * Sets the value for {@code installmentNumber}.
     *
     * @param installmentNumber Consecutive number of the installment that is paid. Applicable only
     *     payout events, i.e. `event_type = PAYOUT`.
     * @return This builder instance.
     */
    public Builder installmentNumber(Long installmentNumber) {
      this.installmentNumber = installmentNumber;
      return this;
    }

    /**
     * Sets the value for {@code status}.
     *
     * @param status Status of the transaction event.
     * @return This builder instance.
     */
    public Builder status(com.sumup.sdk.models.EventStatus status) {
      this.status = status;
      return this;
    }

    /**
     * Sets the value for {@code timestamp}.
     *
     * @param timestamp Date and time of the transaction event.
     * @return This builder instance.
     */
    public Builder timestamp(java.time.OffsetDateTime timestamp) {
      this.timestamp = timestamp;
      return this;
    }

    /**
     * Builds an immutable TransactionEvent instance.
     *
     * @return Immutable TransactionEvent.
     */
    public TransactionEvent build() {
      return new TransactionEvent(
          amount, date, dueDate, eventType, id, installmentNumber, status, timestamp);
    }
  }
}
