// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

/** Payout type for the transaction. */
public final class TransactionFullPayoutType {
  public static final TransactionFullPayoutType BANK_ACCOUNT =
      new TransactionFullPayoutType("BANK_ACCOUNT");
  public static final TransactionFullPayoutType PREPAID_CARD =
      new TransactionFullPayoutType("PREPAID_CARD");

  private final String value;

  private TransactionFullPayoutType(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a TransactionFullPayoutType for a value not yet known to this SDK version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static TransactionFullPayoutType of(String value) {
    return new TransactionFullPayoutType(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static TransactionFullPayoutType fromValue(String value) {
    return value == null ? null : new TransactionFullPayoutType(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof TransactionFullPayoutType that && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
