// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** Checkout-specific fields associated with a transaction. */
public record TransactionCheckoutInfo(
    /**
     * Authorization code for the transaction sent by the payment card issuer or bank. Applicable
     * only to card payments.
     */
    String authCode,

    /** Entry mode of the payment details. */
    com.sumup.sdk.models.EntryMode entryMode,

    /** Internal unique ID of the transaction on the SumUp platform. */
    Long internalId,

    /** Unique code of the registered merchant to whom the payment is made. */
    String merchantCode,

    /** Amount of the tip (out of the total transaction amount). */
    Float tipAmount,

    /** Amount of the applicable VAT (out of the total transaction amount). */
    Float vatAmount) {
  /**
   * Creates a builder for TransactionCheckoutInfo.
   *
   * @return Builder that constructs immutable TransactionCheckoutInfo instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for TransactionCheckoutInfo instances. */
  public static final class Builder {
    private String authCode;
    private com.sumup.sdk.models.EntryMode entryMode;
    private Long internalId;
    private String merchantCode;
    private Float tipAmount;
    private Float vatAmount;

    private Builder() {}

    /**
     * Sets the value for {@code authCode}.
     *
     * @param authCode Authorization code for the transaction sent by the payment card issuer or
     *     bank. Applicable only to card payments.
     * @return This builder instance.
     */
    public Builder authCode(String authCode) {
      this.authCode = authCode;
      return this;
    }

    /**
     * Sets the value for {@code entryMode}.
     *
     * @param entryMode Entry mode of the payment details.
     * @return This builder instance.
     */
    public Builder entryMode(com.sumup.sdk.models.EntryMode entryMode) {
      this.entryMode = entryMode;
      return this;
    }

    /**
     * Sets the value for {@code internalId}.
     *
     * @param internalId Internal unique ID of the transaction on the SumUp platform.
     * @return This builder instance.
     */
    public Builder internalId(Long internalId) {
      this.internalId = internalId;
      return this;
    }

    /**
     * Sets the value for {@code merchantCode}.
     *
     * @param merchantCode Unique code of the registered merchant to whom the payment is made.
     * @return This builder instance.
     */
    public Builder merchantCode(String merchantCode) {
      this.merchantCode = merchantCode;
      return this;
    }

    /**
     * Sets the value for {@code tipAmount}.
     *
     * @param tipAmount Amount of the tip (out of the total transaction amount).
     * @return This builder instance.
     */
    public Builder tipAmount(Float tipAmount) {
      this.tipAmount = tipAmount;
      return this;
    }

    /**
     * Sets the value for {@code vatAmount}.
     *
     * @param vatAmount Amount of the applicable VAT (out of the total transaction amount).
     * @return This builder instance.
     */
    public Builder vatAmount(Float vatAmount) {
      this.vatAmount = vatAmount;
      return this;
    }

    /**
     * Builds an immutable TransactionCheckoutInfo instance.
     *
     * @return Immutable TransactionCheckoutInfo.
     */
    public TransactionCheckoutInfo build() {
      return new TransactionCheckoutInfo(
          authCode, entryMode, internalId, merchantCode, tipAmount, vatAmount);
    }
  }
}
