// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

/** Current status of the transaction. */
public final class TransactionFullStatus {
  public static final TransactionFullStatus SUCCESSFUL = new TransactionFullStatus("SUCCESSFUL");
  public static final TransactionFullStatus CANCELLED = new TransactionFullStatus("CANCELLED");
  public static final TransactionFullStatus FAILED = new TransactionFullStatus("FAILED");
  public static final TransactionFullStatus PENDING = new TransactionFullStatus("PENDING");

  private final String value;

  private TransactionFullStatus(String value) {
    this.value = Objects.requireNonNull(value, "value");
  }

  /**
   * Creates a TransactionFullStatus for a value not yet known to this SDK version.
   *
   * @param value Wire value sent to or received from the API.
   * @return Open enum value wrapping {@code value}.
   */
  public static TransactionFullStatus of(String value) {
    return new TransactionFullStatus(value);
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static TransactionFullStatus fromValue(String value) {
    return value == null ? null : new TransactionFullStatus(value);
  }

  @Override
  public boolean equals(Object other) {
    return this == other
        || (other instanceof TransactionFullStatus that && this.value.equals(that.value));
  }

  @Override
  public int hashCode() {
    return value.hashCode();
  }
}
