// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum TypesItem {
  PAYMENT("PAYMENT"),
  REFUND("REFUND"),
  CHARGE_BACK("CHARGE_BACK");

  private final String value;

  TypesItem(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static TypesItem fromValue(String value) {
    if (value == null) {
      return null;
    }
    for (TypesItem entry : values()) {
      if (entry.value.equals(value)) {
        return entry;
      }
    }
    throw new IllegalArgumentException("Unknown TypesItem value: " + value);
  }
}
