// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Key indicating type of error */
public enum UnauthorizedErrorsType {
  INVALID_ACCESS_TOKEN("INVALID_ACCESS_TOKEN"),
  INVALID_PASSWORD("INVALID_PASSWORD");

  private final String value;

  UnauthorizedErrorsType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return value;
  }

  @JsonCreator
  public static UnauthorizedErrorsType fromValue(String value) {
    if (value == null) {
      return null;
    }
    for (UnauthorizedErrorsType entry : values()) {
      if (entry.value.equals(value)) {
        return entry;
      }
    }
    throw new IllegalArgumentException("Unknown UnauthorizedErrorsType value: " + value);
  }
}
