// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

public record UpdateSubAccountRequest(
    Boolean disabled,
    String nickname,
    String password,
    com.sumup.sdk.models.UpdateSubAccountRequestPermissions permissions,
    String username) {
  /**
   * Creates a builder for UpdateSubAccountRequest.
   *
   * @return Builder that constructs immutable UpdateSubAccountRequest instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for UpdateSubAccountRequest instances. */
  public static final class Builder {
    private Boolean disabled;
    private String nickname;
    private String password;
    private com.sumup.sdk.models.UpdateSubAccountRequestPermissions permissions;
    private String username;

    private Builder() {}

    /**
     * Sets the value for {@code disabled}.
     *
     * @param disabled Value for the disabled field.
     * @return This builder instance.
     */
    public Builder disabled(Boolean disabled) {
      this.disabled = disabled;
      return this;
    }

    /**
     * Sets the value for {@code nickname}.
     *
     * @param nickname Value for the nickname field.
     * @return This builder instance.
     */
    public Builder nickname(String nickname) {
      this.nickname = nickname;
      return this;
    }

    /**
     * Sets the value for {@code password}.
     *
     * @param password Value for the password field.
     * @return This builder instance.
     */
    public Builder password(String password) {
      this.password = password;
      return this;
    }

    /**
     * Sets the value for {@code permissions}.
     *
     * @param permissions Value for the permissions field.
     * @return This builder instance.
     */
    public Builder permissions(
        com.sumup.sdk.models.UpdateSubAccountRequestPermissions permissions) {
      this.permissions = permissions;
      return this;
    }

    /**
     * Sets the value for {@code username}.
     *
     * @param username Value for the username field.
     * @return This builder instance.
     */
    public Builder username(String username) {
      this.username = username;
      return this;
    }

    /**
     * Builds an immutable UpdateSubAccountRequest instance.
     *
     * @return Immutable UpdateSubAccountRequest.
     */
    public UpdateSubAccountRequest build() {
      return new UpdateSubAccountRequest(disabled, nickname, password, permissions, username);
    }
  }
}
