// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

public record UpdateReaderRequest(
    /**
     * Set of user-defined key-value pairs attached to the object. Partial updates are not
     * supported. When updating, always submit whole metadata. Maximum of 64 parameters are allowed
     * in the object.
     */
    com.sumup.sdk.models.Metadata metadata,

    /** Custom human-readable, user-defined name for easier identification of the reader. */
    com.sumup.sdk.models.ReaderName name) {
  /**
   * Creates a builder for UpdateReaderRequest.
   *
   * @return Builder that constructs immutable UpdateReaderRequest instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for UpdateReaderRequest instances. */
  public static final class Builder {
    private com.sumup.sdk.models.Metadata metadata;
    private com.sumup.sdk.models.ReaderName name;

    private Builder() {}

    /**
     * Sets the value for {@code metadata}.
     *
     * @param metadata Set of user-defined key-value pairs attached to the object. Partial updates
     *     are not supported. When updating, always submit whole metadata. Maximum of 64 parameters
     *     are allowed in the object.
     * @return This builder instance.
     */
    public Builder metadata(com.sumup.sdk.models.Metadata metadata) {
      this.metadata = metadata;
      return this;
    }

    /**
     * Sets the value for {@code name}.
     *
     * @param name Custom human-readable, user-defined name for easier identification of the reader.
     * @return This builder instance.
     */
    public Builder name(com.sumup.sdk.models.ReaderName name) {
      this.name = name;
      return this;
    }

    /**
     * Builds an immutable UpdateReaderRequest instance.
     *
     * @return Immutable UpdateReaderRequest.
     */
    public UpdateReaderRequest build() {
      return new UpdateReaderRequest(metadata, name);
    }
  }
}
