// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

public record UpdateMerchantRoleRequest(
    /** User-defined description of the role. */
    String description,

    /** User-defined name of the role. */
    String name,

    /** User's permissions. */
    java.util.List<String> permissions) {
  /**
   * Creates a builder for UpdateMerchantRoleRequest.
   *
   * @return Builder that constructs immutable UpdateMerchantRoleRequest instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for UpdateMerchantRoleRequest instances. */
  public static final class Builder {
    private String description;
    private String name;
    private java.util.List<String> permissions;

    private Builder() {}

    /**
     * Sets the value for {@code description}.
     *
     * @param description User-defined description of the role.
     * @return This builder instance.
     */
    public Builder description(String description) {
      this.description = description;
      return this;
    }

    /**
     * Sets the value for {@code name}.
     *
     * @param name User-defined name of the role.
     * @return This builder instance.
     */
    public Builder name(String name) {
      this.name = name;
      return this;
    }

    /**
     * Sets the value for {@code permissions}.
     *
     * @param permissions User's permissions.
     * @return This builder instance.
     */
    public Builder permissions(java.util.List<String> permissions) {
      this.permissions = permissions;
      return this;
    }

    /**
     * Builds an immutable UpdateMerchantRoleRequest instance.
     *
     * @return Immutable UpdateMerchantRoleRequest.
     */
    public UpdateMerchantRoleRequest build() {
      return new UpdateMerchantRoleRequest(description, name, permissions);
    }
  }
}
