// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

public record UpdateSubAccountRequestPermissions(
    Boolean createMotoPayments,
    Boolean createReferral,
    Boolean fullTransactionHistoryView,
    Boolean refundTransactions) {
  /**
   * Creates a builder for UpdateSubAccountRequestPermissions.
   *
   * @return Builder that constructs immutable UpdateSubAccountRequestPermissions instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for UpdateSubAccountRequestPermissions instances. */
  public static final class Builder {
    private Boolean createMotoPayments;
    private Boolean createReferral;
    private Boolean fullTransactionHistoryView;
    private Boolean refundTransactions;

    private Builder() {}

    /**
     * Sets the value for {@code createMotoPayments}.
     *
     * @param createMotoPayments Value for the createMotoPayments field.
     * @return This builder instance.
     */
    public Builder createMotoPayments(Boolean createMotoPayments) {
      this.createMotoPayments = createMotoPayments;
      return this;
    }

    /**
     * Sets the value for {@code createReferral}.
     *
     * @param createReferral Value for the createReferral field.
     * @return This builder instance.
     */
    public Builder createReferral(Boolean createReferral) {
      this.createReferral = createReferral;
      return this;
    }

    /**
     * Sets the value for {@code fullTransactionHistoryView}.
     *
     * @param fullTransactionHistoryView Value for the fullTransactionHistoryView field.
     * @return This builder instance.
     */
    public Builder fullTransactionHistoryView(Boolean fullTransactionHistoryView) {
      this.fullTransactionHistoryView = fullTransactionHistoryView;
      return this;
    }

    /**
     * Sets the value for {@code refundTransactions}.
     *
     * @param refundTransactions Value for the refundTransactions field.
     * @return This builder instance.
     */
    public Builder refundTransactions(Boolean refundTransactions) {
      this.refundTransactions = refundTransactions;
      return this;
    }

    /**
     * Builds an immutable UpdateSubAccountRequestPermissions instance.
     *
     * @return Immutable UpdateSubAccountRequestPermissions.
     */
    public UpdateSubAccountRequestPermissions build() {
      return new UpdateSubAccountRequestPermissions(
          createMotoPayments, createReferral, fullTransactionHistoryView, refundTransactions);
    }
  }
}
