// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/** Merchant VAT rates */
public record VatRates(
    /** Country ISO code */
    String country,

    /** Description */
    String description,

    /** Internal ID */
    Double id,

    /** Ordering */
    Double ordering,

    /** Rate */
    Double rate) {
  /**
   * Creates a builder for VatRates.
   *
   * @return Builder that constructs immutable VatRates instances.
   */
  public static Builder builder() {
    return new Builder();
  }

  /** Builder for VatRates instances. */
  public static final class Builder {
    private String country;
    private String description;
    private Double id;
    private Double ordering;
    private Double rate;

    private Builder() {}

    /**
     * Sets the value for {@code country}.
     *
     * @param country Country ISO code
     * @return This builder instance.
     */
    public Builder country(String country) {
      this.country = country;
      return this;
    }

    /**
     * Sets the value for {@code description}.
     *
     * @param description Description
     * @return This builder instance.
     */
    public Builder description(String description) {
      this.description = description;
      return this;
    }

    /**
     * Sets the value for {@code id}.
     *
     * @param id Internal ID
     * @return This builder instance.
     */
    public Builder id(Double id) {
      this.id = id;
      return this;
    }

    /**
     * Sets the value for {@code ordering}.
     *
     * @param ordering Ordering
     * @return This builder instance.
     */
    public Builder ordering(Double ordering) {
      this.ordering = ordering;
      return this;
    }

    /**
     * Sets the value for {@code rate}.
     *
     * @param rate Rate
     * @return This builder instance.
     */
    public Builder rate(Double rate) {
      this.rate = rate;
      return this;
    }

    /**
     * Builds an immutable VatRates instance.
     *
     * @return Immutable VatRates.
     */
    public VatRates build() {
      return new VatRates(country, description, id, ordering, rate);
    }
  }
}
