// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.models;

/**
 * The version of the resource. The version reflects a specific change submitted to the API via one
 * of the `PATCH` endpoints.
 */
public record Version(String value) {}
