// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.clients;

import com.fasterxml.jackson.core.type.TypeReference;
import com.sumup.sdk.core.ApiClient;
import com.sumup.sdk.core.ApiException;
import com.sumup.sdk.core.HttpMethod;
import com.sumup.sdk.core.RequestOptions;
import java.util.Objects;

/**
 * Client for the "Merchants" API group.
 *
 * <p>A Merchant represents a single business which can use SumUp products like payment processing.
 */
public final class MerchantsClient {
  private final ApiClient apiClient;

  /**
   * Creates a new MerchantsClient instance backed by the provided ApiClient.
   *
   * @param apiClient Configured API client used to send HTTP requests.
   */
  public MerchantsClient(ApiClient apiClient) {
    this.apiClient = Objects.requireNonNull(apiClient, "apiClient");
  }

  /**
   * Get Merchant
   *
   * <p>Returns a Merchant for a valid Merchant code.
   *
   * <p>Operation ID: GetMerchant
   *
   * @param merchantCode Short unique identifier for the merchant.
   *     <p>Call the overload that accepts RequestOptions to customize headers, authorization, or
   *     request timeout.
   * @return com.sumup.sdk.models.Merchant parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public com.sumup.sdk.models.Merchant get(String merchantCode) throws ApiException {
    return get(merchantCode, null);
  }

  /**
   * Get Merchant
   *
   * <p>Returns a Merchant for a valid Merchant code.
   *
   * <p>Operation ID: GetMerchant
   *
   * @param merchantCode Short unique identifier for the merchant.
   * @param requestOptions Request-specific overrides (headers, authorization, or timeout). Pass
   *     {@code null} to use client defaults.
   * @return com.sumup.sdk.models.Merchant parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public com.sumup.sdk.models.Merchant get(String merchantCode, RequestOptions requestOptions)
      throws ApiException {
    Objects.requireNonNull(merchantCode, "merchantCode");
    String path = "/v1/merchants/{merchant_code}";
    path =
        path.replace(
            "{merchant_code}", ApiClient.urlEncode(ApiClient.parameterValue(merchantCode)));

    return this.apiClient.send(
        HttpMethod.GET,
        path,
        null,
        null,
        null,
        new TypeReference<com.sumup.sdk.models.Merchant>() {},
        requestOptions);
  }

  /**
   * Get Person
   *
   * <p>Returns a single Person related to a Merchant.
   *
   * <p>Operation ID: GetPerson
   *
   * @param merchantCode Short unique identifier for the merchant.
   * @param personId Person ID
   *     <p>Call the overload that accepts RequestOptions to customize headers, authorization, or
   *     request timeout.
   * @return com.sumup.sdk.models.Person parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public com.sumup.sdk.models.Person getPerson(String merchantCode, String personId)
      throws ApiException {
    return getPerson(merchantCode, personId, null);
  }

  /**
   * Get Person
   *
   * <p>Returns a single Person related to a Merchant.
   *
   * <p>Operation ID: GetPerson
   *
   * @param merchantCode Short unique identifier for the merchant.
   * @param personId Person ID
   * @param requestOptions Request-specific overrides (headers, authorization, or timeout). Pass
   *     {@code null} to use client defaults.
   * @return com.sumup.sdk.models.Person parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public com.sumup.sdk.models.Person getPerson(
      String merchantCode, String personId, RequestOptions requestOptions) throws ApiException {
    Objects.requireNonNull(merchantCode, "merchantCode");
    Objects.requireNonNull(personId, "personId");
    String path = "/v1/merchants/{merchant_code}/persons/{person_id}";
    path =
        path.replace(
            "{merchant_code}", ApiClient.urlEncode(ApiClient.parameterValue(merchantCode)));
    path = path.replace("{person_id}", ApiClient.urlEncode(ApiClient.parameterValue(personId)));

    return this.apiClient.send(
        HttpMethod.GET,
        path,
        null,
        null,
        null,
        new TypeReference<com.sumup.sdk.models.Person>() {},
        requestOptions);
  }

  /**
   * List Persons
   *
   * <p>Returns the Persons related to a Merchant.
   *
   * <p>Operation ID: ListPersons
   *
   * @param merchantCode Short unique identifier for the merchant.
   *     <p>Call the overload that accepts RequestOptions to customize headers, authorization, or
   *     request timeout.
   * @return com.sumup.sdk.models.ListPersonsResponseBody parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public com.sumup.sdk.models.ListPersonsResponseBody listPersons(String merchantCode)
      throws ApiException {
    return listPersons(merchantCode, null);
  }

  /**
   * List Persons
   *
   * <p>Returns the Persons related to a Merchant.
   *
   * <p>Operation ID: ListPersons
   *
   * @param merchantCode Short unique identifier for the merchant.
   * @param requestOptions Request-specific overrides (headers, authorization, or timeout). Pass
   *     {@code null} to use client defaults.
   * @return com.sumup.sdk.models.ListPersonsResponseBody parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public com.sumup.sdk.models.ListPersonsResponseBody listPersons(
      String merchantCode, RequestOptions requestOptions) throws ApiException {
    Objects.requireNonNull(merchantCode, "merchantCode");
    String path = "/v1/merchants/{merchant_code}/persons";
    path =
        path.replace(
            "{merchant_code}", ApiClient.urlEncode(ApiClient.parameterValue(merchantCode)));

    return this.apiClient.send(
        HttpMethod.GET,
        path,
        null,
        null,
        null,
        new TypeReference<com.sumup.sdk.models.ListPersonsResponseBody>() {},
        requestOptions);
  }
}
