// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.clients;

import com.fasterxml.jackson.core.type.TypeReference;
import com.sumup.sdk.core.ApiClient;
import com.sumup.sdk.core.ApiException;
import com.sumup.sdk.core.HttpMethod;
import com.sumup.sdk.core.RequestOptions;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;

/** Client for the "Payouts" API group. */
public final class PayoutsClient {
  private final ApiClient apiClient;

  /**
   * Creates a new PayoutsClient instance backed by the provided ApiClient.
   *
   * @param apiClient Configured API client used to send HTTP requests.
   */
  public PayoutsClient(ApiClient apiClient) {
    this.apiClient = Objects.requireNonNull(apiClient, "apiClient");
  }

  /**
   * List payouts
   *
   * <p>Lists ordered payouts for the merchant profile.
   *
   * <p>Operation ID: ListPayouts
   *
   * @param endDate End date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).
   * @param startDate Start date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).
   *     <p>Call the overload that accepts optional parameter objects or RequestOptions to customize
   *     headers, authorization, query values, or timeouts.
   * @return com.sumup.sdk.models.FinancialPayouts parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public com.sumup.sdk.models.FinancialPayouts listPayouts(
      java.time.LocalDate endDate, java.time.LocalDate startDate) throws ApiException {
    return listPayouts(endDate, startDate, null);
  }

  /**
   * List payouts
   *
   * <p>Lists ordered payouts for the merchant profile.
   *
   * <p>Operation ID: ListPayouts
   *
   * @param endDate End date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).
   * @param startDate Start date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).
   * @param listPayouts Optional query parameters for this request.
   *     <p>Call the overload that accepts RequestOptions to customize headers, authorization, or
   *     request timeout.
   * @return com.sumup.sdk.models.FinancialPayouts parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public com.sumup.sdk.models.FinancialPayouts listPayouts(
      java.time.LocalDate endDate,
      java.time.LocalDate startDate,
      ListPayoutsQueryParams listPayouts)
      throws ApiException {
    return listPayouts(endDate, startDate, listPayouts, null);
  }

  /**
   * List payouts
   *
   * <p>Lists ordered payouts for the merchant profile.
   *
   * <p>Operation ID: ListPayouts
   *
   * @param endDate End date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).
   * @param startDate Start date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).
   * @param listPayouts Optional query parameters for this request.
   * @param requestOptions Request-specific overrides (headers, authorization, or timeout). Pass
   *     {@code null} to use client defaults.
   * @return com.sumup.sdk.models.FinancialPayouts parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public com.sumup.sdk.models.FinancialPayouts listPayouts(
      java.time.LocalDate endDate,
      java.time.LocalDate startDate,
      ListPayoutsQueryParams listPayouts,
      RequestOptions requestOptions)
      throws ApiException {
    Objects.requireNonNull(endDate, "endDate");
    Objects.requireNonNull(startDate, "startDate");
    String path = "/v0.1/me/financials/payouts";
    Map<String, Object> queryParams = new LinkedHashMap<>();
    queryParams.put("end_date", endDate);
    queryParams.put("start_date", startDate);
    if (listPayouts != null) {
      queryParams.putAll(listPayouts.toMap());
    }
    Map<String, String> headerParams = null;

    return this.apiClient.send(
        HttpMethod.GET,
        path,
        queryParams,
        null,
        null,
        new TypeReference<com.sumup.sdk.models.FinancialPayouts>() {},
        requestOptions);
  }

  /**
   * List payouts
   *
   * <p>Lists ordered payouts for the merchant profile.
   *
   * <p>Operation ID: ListPayoutsV1
   *
   * @param merchantCode Path parameter.
   * @param endDate End date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).
   * @param startDate Start date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).
   *     <p>Call the overload that accepts optional parameter objects or RequestOptions to customize
   *     headers, authorization, query values, or timeouts.
   * @return com.sumup.sdk.models.FinancialPayouts parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public com.sumup.sdk.models.FinancialPayouts listPayoutsV1(
      String merchantCode, java.time.LocalDate endDate, java.time.LocalDate startDate)
      throws ApiException {
    return listPayoutsV1(merchantCode, endDate, startDate, null);
  }

  /**
   * List payouts
   *
   * <p>Lists ordered payouts for the merchant profile.
   *
   * <p>Operation ID: ListPayoutsV1
   *
   * @param merchantCode Path parameter.
   * @param endDate End date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).
   * @param startDate Start date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).
   * @param listPayoutsV1 Optional query parameters for this request.
   *     <p>Call the overload that accepts RequestOptions to customize headers, authorization, or
   *     request timeout.
   * @return com.sumup.sdk.models.FinancialPayouts parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public com.sumup.sdk.models.FinancialPayouts listPayoutsV1(
      String merchantCode,
      java.time.LocalDate endDate,
      java.time.LocalDate startDate,
      ListPayoutsV1QueryParams listPayoutsV1)
      throws ApiException {
    return listPayoutsV1(merchantCode, endDate, startDate, listPayoutsV1, null);
  }

  /**
   * List payouts
   *
   * <p>Lists ordered payouts for the merchant profile.
   *
   * <p>Operation ID: ListPayoutsV1
   *
   * @param merchantCode Path parameter.
   * @param endDate End date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).
   * @param startDate Start date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).
   * @param listPayoutsV1 Optional query parameters for this request.
   * @param requestOptions Request-specific overrides (headers, authorization, or timeout). Pass
   *     {@code null} to use client defaults.
   * @return com.sumup.sdk.models.FinancialPayouts parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public com.sumup.sdk.models.FinancialPayouts listPayoutsV1(
      String merchantCode,
      java.time.LocalDate endDate,
      java.time.LocalDate startDate,
      ListPayoutsV1QueryParams listPayoutsV1,
      RequestOptions requestOptions)
      throws ApiException {
    Objects.requireNonNull(merchantCode, "merchantCode");
    Objects.requireNonNull(endDate, "endDate");
    Objects.requireNonNull(startDate, "startDate");
    String path = "/v1.0/merchants/{merchant_code}/payouts";
    path = path.replace("{merchant_code}", ApiClient.urlEncode(String.valueOf(merchantCode)));
    Map<String, Object> queryParams = new LinkedHashMap<>();
    queryParams.put("end_date", endDate);
    queryParams.put("start_date", startDate);
    if (listPayoutsV1 != null) {
      queryParams.putAll(listPayoutsV1.toMap());
    }
    Map<String, String> headerParams = null;

    return this.apiClient.send(
        HttpMethod.GET,
        path,
        queryParams,
        null,
        null,
        new TypeReference<com.sumup.sdk.models.FinancialPayouts>() {},
        requestOptions);
  }

  /** Optional query parameters for this request. */
  public static final class ListPayoutsQueryParams {
    private final Map<String, Object> values = new LinkedHashMap<>();

    /**
     * Sets the format query parameter.
     *
     * @param value Query parameter value.
     * @return This ListPayoutsQueryParams instance.
     */
    public ListPayoutsQueryParams format(String value) {
      this.values.put("format", Objects.requireNonNull(value, "format"));
      return this;
    }

    /**
     * Sets the limit query parameter.
     *
     * @param value Query parameter value.
     * @return This ListPayoutsQueryParams instance.
     */
    public ListPayoutsQueryParams limit(Long value) {
      this.values.put("limit", Objects.requireNonNull(value, "limit"));
      return this;
    }

    /**
     * Sets the order query parameter.
     *
     * @param value Query parameter value.
     * @return This ListPayoutsQueryParams instance.
     */
    public ListPayoutsQueryParams order(String value) {
      this.values.put("order", Objects.requireNonNull(value, "order"));
      return this;
    }

    /**
     * Converts query parameters to a map understood by ApiClient.
     *
     * @return Collected query parameters keyed by API name.
     */
    Map<String, Object> toMap() {
      return values;
    }
  }

  /** Optional query parameters for this request. */
  public static final class ListPayoutsV1QueryParams {
    private final Map<String, Object> values = new LinkedHashMap<>();

    /**
     * Sets the format query parameter.
     *
     * @param value Query parameter value.
     * @return This ListPayoutsV1QueryParams instance.
     */
    public ListPayoutsV1QueryParams format(String value) {
      this.values.put("format", Objects.requireNonNull(value, "format"));
      return this;
    }

    /**
     * Sets the limit query parameter.
     *
     * @param value Query parameter value.
     * @return This ListPayoutsV1QueryParams instance.
     */
    public ListPayoutsV1QueryParams limit(Long value) {
      this.values.put("limit", Objects.requireNonNull(value, "limit"));
      return this;
    }

    /**
     * Sets the order query parameter.
     *
     * @param value Query parameter value.
     * @return This ListPayoutsV1QueryParams instance.
     */
    public ListPayoutsV1QueryParams order(String value) {
      this.values.put("order", Objects.requireNonNull(value, "order"));
      return this;
    }

    /**
     * Converts query parameters to a map understood by ApiClient.
     *
     * @return Collected query parameters keyed by API name.
     */
    Map<String, Object> toMap() {
      return values;
    }
  }
}
