// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.clients;

import com.fasterxml.jackson.core.type.TypeReference;
import com.sumup.sdk.core.ApiClient;
import com.sumup.sdk.core.ApiException;
import com.sumup.sdk.core.HttpMethod;
import com.sumup.sdk.core.RequestOptions;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;

/** Client for the "Subaccounts" API group. */
public final class SubaccountsClient {
  private final ApiClient apiClient;

  /**
   * Creates a new SubaccountsClient instance backed by the provided ApiClient.
   *
   * @param apiClient Configured API client used to send HTTP requests.
   */
  public SubaccountsClient(ApiClient apiClient) {
    this.apiClient = Objects.requireNonNull(apiClient, "apiClient");
  }

  /**
   * Retrieve an operator
   *
   * <p>Returns specific operator.
   *
   * <p>Operation ID: CompatGetOperator
   *
   * @param operatorId The unique identifier for the operator.
   *     <p>Call the overload that accepts RequestOptions to customize headers, authorization, or
   *     request timeout.
   * @return com.sumup.sdk.models.Operator parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public com.sumup.sdk.models.Operator compatGetOperator(Integer operatorId) throws ApiException {
    return compatGetOperator(operatorId, null);
  }

  /**
   * Retrieve an operator
   *
   * <p>Returns specific operator.
   *
   * <p>Operation ID: CompatGetOperator
   *
   * @param operatorId The unique identifier for the operator.
   * @param requestOptions Request-specific overrides (headers, authorization, or timeout). Pass
   *     {@code null} to use client defaults.
   * @return com.sumup.sdk.models.Operator parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public com.sumup.sdk.models.Operator compatGetOperator(
      Integer operatorId, RequestOptions requestOptions) throws ApiException {
    Objects.requireNonNull(operatorId, "operatorId");
    String path = "/v0.1/me/accounts/{operator_id}";
    path = path.replace("{operator_id}", ApiClient.urlEncode(String.valueOf(operatorId)));
    Map<String, Object> queryParams = null;
    Map<String, String> headerParams = null;

    return this.apiClient.send(
        HttpMethod.GET,
        path,
        null,
        null,
        null,
        new TypeReference<com.sumup.sdk.models.Operator>() {},
        requestOptions);
  }

  /**
   * Create an operator
   *
   * <p>Creates new operator for currently authorized users' merchant.
   *
   * <p>Operation ID: CreateSubAccount
   *
   * @param request Request body payload.
   *     <p>Call the overload that accepts RequestOptions to customize headers, authorization, or
   *     request timeout.
   * @return com.sumup.sdk.models.Operator parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public com.sumup.sdk.models.Operator createSubAccount(
      com.sumup.sdk.models.CreateSubAccountRequest request) throws ApiException {
    return createSubAccount(request, null);
  }

  /**
   * Create an operator
   *
   * <p>Creates new operator for currently authorized users' merchant.
   *
   * <p>Operation ID: CreateSubAccount
   *
   * @param request Request body payload.
   * @param requestOptions Request-specific overrides (headers, authorization, or timeout). Pass
   *     {@code null} to use client defaults.
   * @return com.sumup.sdk.models.Operator parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public com.sumup.sdk.models.Operator createSubAccount(
      com.sumup.sdk.models.CreateSubAccountRequest request, RequestOptions requestOptions)
      throws ApiException {
    Objects.requireNonNull(request, "request");
    String path = "/v0.1/me/accounts";
    Map<String, Object> queryParams = null;
    Map<String, String> headerParams = null;

    return this.apiClient.send(
        HttpMethod.POST,
        path,
        null,
        null,
        request,
        new TypeReference<com.sumup.sdk.models.Operator>() {},
        requestOptions);
  }

  /**
   * Disable an operator.
   *
   * <p>Disable the specified operator for the merchant account.
   *
   * <p>Operation ID: DeactivateSubAccount
   *
   * @param operatorId The unique identifier for the operator.
   *     <p>Call the overload that accepts RequestOptions to customize headers, authorization, or
   *     request timeout.
   * @return com.sumup.sdk.models.Operator parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public com.sumup.sdk.models.Operator deactivateSubAccount(Integer operatorId)
      throws ApiException {
    return deactivateSubAccount(operatorId, null);
  }

  /**
   * Disable an operator.
   *
   * <p>Disable the specified operator for the merchant account.
   *
   * <p>Operation ID: DeactivateSubAccount
   *
   * @param operatorId The unique identifier for the operator.
   * @param requestOptions Request-specific overrides (headers, authorization, or timeout). Pass
   *     {@code null} to use client defaults.
   * @return com.sumup.sdk.models.Operator parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public com.sumup.sdk.models.Operator deactivateSubAccount(
      Integer operatorId, RequestOptions requestOptions) throws ApiException {
    Objects.requireNonNull(operatorId, "operatorId");
    String path = "/v0.1/me/accounts/{operator_id}";
    path = path.replace("{operator_id}", ApiClient.urlEncode(String.valueOf(operatorId)));
    Map<String, Object> queryParams = null;
    Map<String, String> headerParams = null;

    return this.apiClient.send(
        HttpMethod.DELETE,
        path,
        null,
        null,
        null,
        new TypeReference<com.sumup.sdk.models.Operator>() {},
        requestOptions);
  }

  /**
   * List operators
   *
   * <p>Returns list of operators for currently authorized user's merchant.
   *
   * <p>Operation ID: ListSubAccounts
   *
   * <p>Call the overload that accepts optional parameter objects or RequestOptions to customize
   * headers, authorization, query values, or timeouts.
   *
   * @return {@code java.util.List<com.sumup.sdk.models.Operator>} parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public java.util.List<com.sumup.sdk.models.Operator> listSubAccounts() throws ApiException {
    return listSubAccounts(null);
  }

  /**
   * List operators
   *
   * <p>Returns list of operators for currently authorized user's merchant.
   *
   * <p>Operation ID: ListSubAccounts
   *
   * @param listSubAccounts Optional query parameters for this request.
   *     <p>Call the overload that accepts RequestOptions to customize headers, authorization, or
   *     request timeout.
   * @return {@code java.util.List<com.sumup.sdk.models.Operator>} parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public java.util.List<com.sumup.sdk.models.Operator> listSubAccounts(
      ListSubAccountsQueryParams listSubAccounts) throws ApiException {
    return listSubAccounts(listSubAccounts, null);
  }

  /**
   * List operators
   *
   * <p>Returns list of operators for currently authorized user's merchant.
   *
   * <p>Operation ID: ListSubAccounts
   *
   * @param listSubAccounts Optional query parameters for this request.
   * @param requestOptions Request-specific overrides (headers, authorization, or timeout). Pass
   *     {@code null} to use client defaults.
   * @return {@code java.util.List<com.sumup.sdk.models.Operator>} parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public java.util.List<com.sumup.sdk.models.Operator> listSubAccounts(
      ListSubAccountsQueryParams listSubAccounts, RequestOptions requestOptions)
      throws ApiException {
    String path = "/v0.1/me/accounts";
    Map<String, Object> queryParams = new LinkedHashMap<>();
    if (listSubAccounts != null) {
      queryParams.putAll(listSubAccounts.toMap());
    }
    Map<String, String> headerParams = null;

    return this.apiClient.send(
        HttpMethod.GET,
        path,
        queryParams,
        null,
        null,
        new TypeReference<java.util.List<com.sumup.sdk.models.Operator>>() {},
        requestOptions);
  }

  /**
   * Update an operator
   *
   * <p>Updates operator. If the operator was disabled and their password is updated they will be
   * unblocked.
   *
   * <p>Operation ID: UpdateSubAccount
   *
   * @param operatorId The unique identifier for the operator.
   * @param request Request body payload.
   *     <p>Call the overload that accepts RequestOptions to customize headers, authorization, or
   *     request timeout.
   * @return com.sumup.sdk.models.Operator parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public com.sumup.sdk.models.Operator updateSubAccount(
      Integer operatorId, com.sumup.sdk.models.UpdateSubAccountRequest request)
      throws ApiException {
    return updateSubAccount(operatorId, request, null);
  }

  /**
   * Update an operator
   *
   * <p>Updates operator. If the operator was disabled and their password is updated they will be
   * unblocked.
   *
   * <p>Operation ID: UpdateSubAccount
   *
   * @param operatorId The unique identifier for the operator.
   * @param request Request body payload.
   * @param requestOptions Request-specific overrides (headers, authorization, or timeout). Pass
   *     {@code null} to use client defaults.
   * @return com.sumup.sdk.models.Operator parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public com.sumup.sdk.models.Operator updateSubAccount(
      Integer operatorId,
      com.sumup.sdk.models.UpdateSubAccountRequest request,
      RequestOptions requestOptions)
      throws ApiException {
    Objects.requireNonNull(operatorId, "operatorId");
    Objects.requireNonNull(request, "request");
    String path = "/v0.1/me/accounts/{operator_id}";
    path = path.replace("{operator_id}", ApiClient.urlEncode(String.valueOf(operatorId)));
    Map<String, Object> queryParams = null;
    Map<String, String> headerParams = null;

    return this.apiClient.send(
        HttpMethod.PUT,
        path,
        null,
        null,
        request,
        new TypeReference<com.sumup.sdk.models.Operator>() {},
        requestOptions);
  }

  /** Optional query parameters for this request. */
  public static final class ListSubAccountsQueryParams {
    private final Map<String, Object> values = new LinkedHashMap<>();

    /**
     * Sets the include_primary query parameter.
     *
     * @param value If true the list of operators will include also the primary user.
     * @return This ListSubAccountsQueryParams instance.
     */
    public ListSubAccountsQueryParams includePrimary(Boolean value) {
      this.values.put("include_primary", Objects.requireNonNull(value, "includePrimary"));
      return this;
    }

    /**
     * Sets the query query parameter.
     *
     * @param value Search query used to filter users that match given query term. Current
     *     implementation allow querying only over the email address. All operators whos email
     *     address contains the query string are returned.
     * @return This ListSubAccountsQueryParams instance.
     */
    public ListSubAccountsQueryParams query(String value) {
      this.values.put("query", Objects.requireNonNull(value, "query"));
      return this;
    }

    /**
     * Converts query parameters to a map understood by ApiClient.
     *
     * @return Collected query parameters keyed by API name.
     */
    Map<String, Object> toMap() {
      return values;
    }
  }
}
