// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.clients;

import com.fasterxml.jackson.core.type.TypeReference;
import com.sumup.sdk.core.ApiClient;
import com.sumup.sdk.core.ApiException;
import com.sumup.sdk.core.HttpMethod;
import com.sumup.sdk.core.RequestOptions;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.CompletableFuture;

/** Client for the "Transactions" API group. */
public final class TransactionsAsyncClient {
  private final ApiClient apiClient;

  /**
   * Creates a new TransactionsAsyncClient instance backed by the provided ApiClient.
   *
   * @param apiClient Configured API client used to send HTTP requests.
   */
  public TransactionsAsyncClient(ApiClient apiClient) {
    this.apiClient = Objects.requireNonNull(apiClient, "apiClient");
  }

  /**
   * Retrieve a transaction
   *
   * <p>Retrieves the full details of an identified transaction. The transaction resource is
   * identified by a query parameter and *one* of following parameters is required: * `id` *
   * `internal_id` * `transaction_code` * `foreign_transaction_id` * `client_transaction_id`
   *
   * <p>Operation ID: GetTransaction
   *
   * <p>Call the overload that accepts optional parameter objects or RequestOptions to customize
   * headers, authorization, query values, or timeouts.
   *
   * @return CompletableFuture resolved with com.sumup.sdk.models.TransactionFull parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public CompletableFuture<com.sumup.sdk.models.TransactionFull> getTransaction()
      throws ApiException {
    return getTransaction(null);
  }

  /**
   * Retrieve a transaction
   *
   * <p>Retrieves the full details of an identified transaction. The transaction resource is
   * identified by a query parameter and *one* of following parameters is required: * `id` *
   * `internal_id` * `transaction_code` * `foreign_transaction_id` * `client_transaction_id`
   *
   * <p>Operation ID: GetTransaction
   *
   * @param getTransaction Optional query parameters for this request.
   *     <p>Call the overload that accepts RequestOptions to customize headers, authorization, or
   *     request timeout.
   * @return CompletableFuture resolved with com.sumup.sdk.models.TransactionFull parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public CompletableFuture<com.sumup.sdk.models.TransactionFull> getTransaction(
      GetTransactionQueryParams getTransaction) throws ApiException {
    return getTransaction(getTransaction, null);
  }

  /**
   * Retrieve a transaction
   *
   * <p>Retrieves the full details of an identified transaction. The transaction resource is
   * identified by a query parameter and *one* of following parameters is required: * `id` *
   * `internal_id` * `transaction_code` * `foreign_transaction_id` * `client_transaction_id`
   *
   * <p>Operation ID: GetTransaction
   *
   * @param getTransaction Optional query parameters for this request.
   * @param requestOptions Request-specific overrides (headers, authorization, or timeout). Pass
   *     {@code null} to use client defaults.
   * @return CompletableFuture resolved with com.sumup.sdk.models.TransactionFull parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public CompletableFuture<com.sumup.sdk.models.TransactionFull> getTransaction(
      GetTransactionQueryParams getTransaction, RequestOptions requestOptions) throws ApiException {
    String path = "/v0.1/me/transactions";
    Map<String, Object> queryParams = new LinkedHashMap<>();
    if (getTransaction != null) {
      queryParams.putAll(getTransaction.toMap());
    }
    Map<String, String> headerParams = null;

    return this.apiClient.sendAsync(
        HttpMethod.GET,
        path,
        queryParams,
        null,
        null,
        new TypeReference<com.sumup.sdk.models.TransactionFull>() {},
        requestOptions);
  }

  /**
   * Retrieve a transaction
   *
   * <p>Retrieves the full details of an identified transaction. The transaction resource is
   * identified by a query parameter and *one* of following parameters is required: * `id` *
   * `internal_id` * `transaction_code` * `foreign_transaction_id` * `client_transaction_id`
   *
   * <p>Operation ID: GetTransactionV2.1
   *
   * @param merchantCode Path parameter.
   *     <p>Call the overload that accepts optional parameter objects or RequestOptions to customize
   *     headers, authorization, query values, or timeouts.
   * @return CompletableFuture resolved with com.sumup.sdk.models.TransactionFull parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public CompletableFuture<com.sumup.sdk.models.TransactionFull> getTransactionV21(
      String merchantCode) throws ApiException {
    return getTransactionV21(merchantCode, null);
  }

  /**
   * Retrieve a transaction
   *
   * <p>Retrieves the full details of an identified transaction. The transaction resource is
   * identified by a query parameter and *one* of following parameters is required: * `id` *
   * `internal_id` * `transaction_code` * `foreign_transaction_id` * `client_transaction_id`
   *
   * <p>Operation ID: GetTransactionV2.1
   *
   * @param merchantCode Path parameter.
   * @param getTransactionV21 Optional query parameters for this request.
   *     <p>Call the overload that accepts RequestOptions to customize headers, authorization, or
   *     request timeout.
   * @return CompletableFuture resolved with com.sumup.sdk.models.TransactionFull parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public CompletableFuture<com.sumup.sdk.models.TransactionFull> getTransactionV21(
      String merchantCode, GetTransactionV21QueryParams getTransactionV21) throws ApiException {
    return getTransactionV21(merchantCode, getTransactionV21, null);
  }

  /**
   * Retrieve a transaction
   *
   * <p>Retrieves the full details of an identified transaction. The transaction resource is
   * identified by a query parameter and *one* of following parameters is required: * `id` *
   * `internal_id` * `transaction_code` * `foreign_transaction_id` * `client_transaction_id`
   *
   * <p>Operation ID: GetTransactionV2.1
   *
   * @param merchantCode Path parameter.
   * @param getTransactionV21 Optional query parameters for this request.
   * @param requestOptions Request-specific overrides (headers, authorization, or timeout). Pass
   *     {@code null} to use client defaults.
   * @return CompletableFuture resolved with com.sumup.sdk.models.TransactionFull parsed response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public CompletableFuture<com.sumup.sdk.models.TransactionFull> getTransactionV21(
      String merchantCode,
      GetTransactionV21QueryParams getTransactionV21,
      RequestOptions requestOptions)
      throws ApiException {
    Objects.requireNonNull(merchantCode, "merchantCode");
    String path = "/v2.1/merchants/{merchant_code}/transactions";
    path = path.replace("{merchant_code}", ApiClient.urlEncode(String.valueOf(merchantCode)));
    Map<String, Object> queryParams = new LinkedHashMap<>();
    if (getTransactionV21 != null) {
      queryParams.putAll(getTransactionV21.toMap());
    }
    Map<String, String> headerParams = null;

    return this.apiClient.sendAsync(
        HttpMethod.GET,
        path,
        queryParams,
        null,
        null,
        new TypeReference<com.sumup.sdk.models.TransactionFull>() {},
        requestOptions);
  }

  /**
   * List transactions
   *
   * <p>Lists detailed history of all transactions associated with the merchant profile.
   *
   * <p>Operation ID: ListTransactions
   *
   * <p>Call the overload that accepts optional parameter objects or RequestOptions to customize
   * headers, authorization, query values, or timeouts.
   *
   * @return CompletableFuture resolved with com.sumup.sdk.models.ListTransactionsResponse parsed
   *     response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public CompletableFuture<com.sumup.sdk.models.ListTransactionsResponse> listTransactions()
      throws ApiException {
    return listTransactions(null);
  }

  /**
   * List transactions
   *
   * <p>Lists detailed history of all transactions associated with the merchant profile.
   *
   * <p>Operation ID: ListTransactions
   *
   * @param listTransactions Optional query parameters for this request.
   *     <p>Call the overload that accepts RequestOptions to customize headers, authorization, or
   *     request timeout.
   * @return CompletableFuture resolved with com.sumup.sdk.models.ListTransactionsResponse parsed
   *     response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public CompletableFuture<com.sumup.sdk.models.ListTransactionsResponse> listTransactions(
      ListTransactionsQueryParams listTransactions) throws ApiException {
    return listTransactions(listTransactions, null);
  }

  /**
   * List transactions
   *
   * <p>Lists detailed history of all transactions associated with the merchant profile.
   *
   * <p>Operation ID: ListTransactions
   *
   * @param listTransactions Optional query parameters for this request.
   * @param requestOptions Request-specific overrides (headers, authorization, or timeout). Pass
   *     {@code null} to use client defaults.
   * @return CompletableFuture resolved with com.sumup.sdk.models.ListTransactionsResponse parsed
   *     response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public CompletableFuture<com.sumup.sdk.models.ListTransactionsResponse> listTransactions(
      ListTransactionsQueryParams listTransactions, RequestOptions requestOptions)
      throws ApiException {
    String path = "/v0.1/me/transactions/history";
    Map<String, Object> queryParams = new LinkedHashMap<>();
    if (listTransactions != null) {
      queryParams.putAll(listTransactions.toMap());
    }
    Map<String, String> headerParams = null;

    return this.apiClient.sendAsync(
        HttpMethod.GET,
        path,
        queryParams,
        null,
        null,
        new TypeReference<com.sumup.sdk.models.ListTransactionsResponse>() {},
        requestOptions);
  }

  /**
   * List transactions
   *
   * <p>Lists detailed history of all transactions associated with the merchant profile.
   *
   * <p>Operation ID: ListTransactionsV2.1
   *
   * @param merchantCode Path parameter.
   *     <p>Call the overload that accepts optional parameter objects or RequestOptions to customize
   *     headers, authorization, query values, or timeouts.
   * @return CompletableFuture resolved with com.sumup.sdk.models.ListTransactionsV21Response parsed
   *     response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public CompletableFuture<com.sumup.sdk.models.ListTransactionsV21Response> listTransactionsV21(
      String merchantCode) throws ApiException {
    return listTransactionsV21(merchantCode, null);
  }

  /**
   * List transactions
   *
   * <p>Lists detailed history of all transactions associated with the merchant profile.
   *
   * <p>Operation ID: ListTransactionsV2.1
   *
   * @param merchantCode Path parameter.
   * @param listTransactionsV21 Optional query parameters for this request.
   *     <p>Call the overload that accepts RequestOptions to customize headers, authorization, or
   *     request timeout.
   * @return CompletableFuture resolved with com.sumup.sdk.models.ListTransactionsV21Response parsed
   *     response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public CompletableFuture<com.sumup.sdk.models.ListTransactionsV21Response> listTransactionsV21(
      String merchantCode, ListTransactionsV21QueryParams listTransactionsV21) throws ApiException {
    return listTransactionsV21(merchantCode, listTransactionsV21, null);
  }

  /**
   * List transactions
   *
   * <p>Lists detailed history of all transactions associated with the merchant profile.
   *
   * <p>Operation ID: ListTransactionsV2.1
   *
   * @param merchantCode Path parameter.
   * @param listTransactionsV21 Optional query parameters for this request.
   * @param requestOptions Request-specific overrides (headers, authorization, or timeout). Pass
   *     {@code null} to use client defaults.
   * @return CompletableFuture resolved with com.sumup.sdk.models.ListTransactionsV21Response parsed
   *     response.
   * @throws ApiException if the SumUp API returns an error.
   */
  public CompletableFuture<com.sumup.sdk.models.ListTransactionsV21Response> listTransactionsV21(
      String merchantCode,
      ListTransactionsV21QueryParams listTransactionsV21,
      RequestOptions requestOptions)
      throws ApiException {
    Objects.requireNonNull(merchantCode, "merchantCode");
    String path = "/v2.1/merchants/{merchant_code}/transactions/history";
    path = path.replace("{merchant_code}", ApiClient.urlEncode(String.valueOf(merchantCode)));
    Map<String, Object> queryParams = new LinkedHashMap<>();
    if (listTransactionsV21 != null) {
      queryParams.putAll(listTransactionsV21.toMap());
    }
    Map<String, String> headerParams = null;

    return this.apiClient.sendAsync(
        HttpMethod.GET,
        path,
        queryParams,
        null,
        null,
        new TypeReference<com.sumup.sdk.models.ListTransactionsV21Response>() {},
        requestOptions);
  }

  /**
   * Refund a transaction
   *
   * <p>Refunds an identified transaction either in full or partially.
   *
   * <p>Operation ID: RefundTransaction
   *
   * @param txnId Unique ID of the transaction.
   * @param request Request body payload.
   *     <p>Call the overload that accepts RequestOptions to customize headers, authorization, or
   *     request timeout.
   * @return CompletableFuture completed when the request finishes.
   * @throws ApiException if the SumUp API returns an error.
   */
  public CompletableFuture<Void> refundTransaction(
      String txnId, com.sumup.sdk.models.RefundTransactionRequest request) throws ApiException {
    return refundTransaction(txnId, request, null);
  }

  /**
   * Refund a transaction
   *
   * <p>Refunds an identified transaction either in full or partially.
   *
   * <p>Operation ID: RefundTransaction
   *
   * @param txnId Unique ID of the transaction.
   * @param request Request body payload.
   * @param requestOptions Request-specific overrides (headers, authorization, or timeout). Pass
   *     {@code null} to use client defaults.
   * @return CompletableFuture completed when the request finishes.
   * @throws ApiException if the SumUp API returns an error.
   */
  public CompletableFuture<Void> refundTransaction(
      String txnId,
      com.sumup.sdk.models.RefundTransactionRequest request,
      RequestOptions requestOptions)
      throws ApiException {
    Objects.requireNonNull(txnId, "txnId");
    String path = "/v0.1/me/refund/{txn_id}";
    path = path.replace("{txn_id}", ApiClient.urlEncode(String.valueOf(txnId)));
    Map<String, Object> queryParams = null;
    Map<String, String> headerParams = null;

    return this.apiClient.sendAsync(
        HttpMethod.POST, path, null, null, request, null, requestOptions);
  }

  /** Optional query parameters for this request. */
  public static final class GetTransactionQueryParams {
    private final Map<String, Object> values = new LinkedHashMap<>();

    /**
     * Sets the id query parameter.
     *
     * @param value Retrieves the transaction resource with the specified transaction ID (the `id`
     *     parameter in the transaction resource).
     * @return This GetTransactionQueryParams instance.
     */
    public GetTransactionQueryParams id(String value) {
      this.values.put("id", Objects.requireNonNull(value, "id"));
      return this;
    }

    /**
     * Sets the internal_id query parameter.
     *
     * @param value Retrieves the transaction resource with the specified internal transaction ID
     *     (the `internal_id` parameter in the transaction resource).
     * @return This GetTransactionQueryParams instance.
     */
    public GetTransactionQueryParams internalId(String value) {
      this.values.put("internal_id", Objects.requireNonNull(value, "internalId"));
      return this;
    }

    /**
     * Sets the transaction_code query parameter.
     *
     * @param value Retrieves the transaction resource with the specified transaction code.
     * @return This GetTransactionQueryParams instance.
     */
    public GetTransactionQueryParams transactionCode(String value) {
      this.values.put("transaction_code", Objects.requireNonNull(value, "transactionCode"));
      return this;
    }

    /**
     * Converts query parameters to a map understood by ApiClient.
     *
     * @return Collected query parameters keyed by API name.
     */
    Map<String, Object> toMap() {
      return values;
    }
  }

  /** Optional query parameters for this request. */
  public static final class GetTransactionV21QueryParams {
    private final Map<String, Object> values = new LinkedHashMap<>();

    /**
     * Sets the client_transaction_id query parameter.
     *
     * @param value Client transaction id.
     * @return This GetTransactionV21QueryParams instance.
     */
    public GetTransactionV21QueryParams clientTransactionId(String value) {
      this.values.put(
          "client_transaction_id", Objects.requireNonNull(value, "clientTransactionId"));
      return this;
    }

    /**
     * Sets the foreign_transaction_id query parameter.
     *
     * @param value External/foreign transaction id (passed by clients).
     * @return This GetTransactionV21QueryParams instance.
     */
    public GetTransactionV21QueryParams foreignTransactionId(String value) {
      this.values.put(
          "foreign_transaction_id", Objects.requireNonNull(value, "foreignTransactionId"));
      return this;
    }

    /**
     * Sets the id query parameter.
     *
     * @param value Retrieves the transaction resource with the specified transaction ID (the `id`
     *     parameter in the transaction resource).
     * @return This GetTransactionV21QueryParams instance.
     */
    public GetTransactionV21QueryParams id(String value) {
      this.values.put("id", Objects.requireNonNull(value, "id"));
      return this;
    }

    /**
     * Sets the internal_id query parameter.
     *
     * @param value Retrieves the transaction resource with the specified internal transaction ID
     *     (the `internal_id` parameter in the transaction resource).
     * @return This GetTransactionV21QueryParams instance.
     */
    public GetTransactionV21QueryParams internalId(String value) {
      this.values.put("internal_id", Objects.requireNonNull(value, "internalId"));
      return this;
    }

    /**
     * Sets the transaction_code query parameter.
     *
     * @param value Retrieves the transaction resource with the specified transaction code.
     * @return This GetTransactionV21QueryParams instance.
     */
    public GetTransactionV21QueryParams transactionCode(String value) {
      this.values.put("transaction_code", Objects.requireNonNull(value, "transactionCode"));
      return this;
    }

    /**
     * Converts query parameters to a map understood by ApiClient.
     *
     * @return Collected query parameters keyed by API name.
     */
    Map<String, Object> toMap() {
      return values;
    }
  }

  /** Optional query parameters for this request. */
  public static final class ListTransactionsQueryParams {
    private final Map<String, Object> values = new LinkedHashMap<>();

    /**
     * Sets the changes_since query parameter.
     *
     * @param value Filters the results by the latest modification time of resources and returns
     *     only transactions that are modified *at or after* the specified timestamp (in
     *     [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).
     * @return This ListTransactionsQueryParams instance.
     */
    public ListTransactionsQueryParams changesSince(java.time.OffsetDateTime value) {
      this.values.put("changes_since", Objects.requireNonNull(value, "changesSince"));
      return this;
    }

    /**
     * Sets the limit query parameter.
     *
     * @param value Specifies the maximum number of results per page. Value must be a positive
     *     integer and if not specified, will return 10 results.
     * @return This ListTransactionsQueryParams instance.
     */
    public ListTransactionsQueryParams limit(Long value) {
      this.values.put("limit", Objects.requireNonNull(value, "limit"));
      return this;
    }

    /**
     * Sets the newest_ref query parameter.
     *
     * @param value Filters the results by the reference ID of transaction events and returns only
     *     transactions with events whose IDs are *smaller* than the specified value. This
     *     parameters supersedes the `newest_time` parameter (if both are provided in the request).
     * @return This ListTransactionsQueryParams instance.
     */
    public ListTransactionsQueryParams newestRef(String value) {
      this.values.put("newest_ref", Objects.requireNonNull(value, "newestRef"));
      return this;
    }

    /**
     * Sets the newest_time query parameter.
     *
     * @param value Filters the results by the creation time of resources and returns only
     *     transactions that are created *before* the specified timestamp (in
     *     [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).
     * @return This ListTransactionsQueryParams instance.
     */
    public ListTransactionsQueryParams newestTime(java.time.OffsetDateTime value) {
      this.values.put("newest_time", Objects.requireNonNull(value, "newestTime"));
      return this;
    }

    /**
     * Sets the oldest_ref query parameter.
     *
     * @param value Filters the results by the reference ID of transaction events and returns only
     *     transactions with events whose IDs are *greater* than the specified value. This
     *     parameters supersedes the `oldest_time` parameter (if both are provided in the request).
     * @return This ListTransactionsQueryParams instance.
     */
    public ListTransactionsQueryParams oldestRef(String value) {
      this.values.put("oldest_ref", Objects.requireNonNull(value, "oldestRef"));
      return this;
    }

    /**
     * Sets the oldest_time query parameter.
     *
     * @param value Filters the results by the creation time of resources and returns only
     *     transactions that are created *at or after* the specified timestamp (in
     *     [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).
     * @return This ListTransactionsQueryParams instance.
     */
    public ListTransactionsQueryParams oldestTime(java.time.OffsetDateTime value) {
      this.values.put("oldest_time", Objects.requireNonNull(value, "oldestTime"));
      return this;
    }

    /**
     * Sets the order query parameter.
     *
     * @param value Specifies the order in which the returned results are displayed.
     * @return This ListTransactionsQueryParams instance.
     */
    public ListTransactionsQueryParams order(com.sumup.sdk.models.Order2 value) {
      this.values.put("order", Objects.requireNonNull(value, "order"));
      return this;
    }

    /**
     * Sets the payment_types query parameter.
     *
     * @param value Filters the returned results by the specified list of payment types used for the
     *     transactions.
     * @return This ListTransactionsQueryParams instance.
     */
    public ListTransactionsQueryParams paymentTypes(
        java.util.List<com.sumup.sdk.models.PaymentType> value) {
      this.values.put("payment_types", Objects.requireNonNull(value, "paymentTypes"));
      return this;
    }

    /**
     * Sets the statuses query parameter.
     *
     * @param value Filters the returned results by the specified list of final statuses of the
     *     transactions.
     * @return This ListTransactionsQueryParams instance.
     */
    public ListTransactionsQueryParams statuses(
        java.util.List<com.sumup.sdk.models.StatusesItem2> value) {
      this.values.put("statuses", Objects.requireNonNull(value, "statuses"));
      return this;
    }

    /**
     * Sets the transaction_code query parameter.
     *
     * @param value Retrieves the transaction resource with the specified transaction code.
     * @return This ListTransactionsQueryParams instance.
     */
    public ListTransactionsQueryParams transactionCode(String value) {
      this.values.put("transaction_code", Objects.requireNonNull(value, "transactionCode"));
      return this;
    }

    /**
     * Sets the types query parameter.
     *
     * @param value Filters the returned results by the specified list of transaction types.
     * @return This ListTransactionsQueryParams instance.
     */
    public ListTransactionsQueryParams types(
        java.util.List<com.sumup.sdk.models.TypesItem2> value) {
      this.values.put("types", Objects.requireNonNull(value, "types"));
      return this;
    }

    /**
     * Sets the users query parameter.
     *
     * @param value Filters the returned results by user email.
     * @return This ListTransactionsQueryParams instance.
     */
    public ListTransactionsQueryParams users(java.util.List<String> value) {
      this.values.put("users", Objects.requireNonNull(value, "users"));
      return this;
    }

    /**
     * Converts query parameters to a map understood by ApiClient.
     *
     * @return Collected query parameters keyed by API name.
     */
    Map<String, Object> toMap() {
      return values;
    }
  }

  /** Optional query parameters for this request. */
  public static final class ListTransactionsV21QueryParams {
    private final Map<String, Object> values = new LinkedHashMap<>();

    /**
     * Sets the changes_since query parameter.
     *
     * @param value Filters the results by the latest modification time of resources and returns
     *     only transactions that are modified *at or after* the specified timestamp (in
     *     [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).
     * @return This ListTransactionsV21QueryParams instance.
     */
    public ListTransactionsV21QueryParams changesSince(java.time.OffsetDateTime value) {
      this.values.put("changes_since", Objects.requireNonNull(value, "changesSince"));
      return this;
    }

    /**
     * Sets the limit query parameter.
     *
     * @param value Specifies the maximum number of results per page. Value must be a positive
     *     integer and if not specified, will return 10 results.
     * @return This ListTransactionsV21QueryParams instance.
     */
    public ListTransactionsV21QueryParams limit(Long value) {
      this.values.put("limit", Objects.requireNonNull(value, "limit"));
      return this;
    }

    /**
     * Sets the newest_ref query parameter.
     *
     * @param value Filters the results by the reference ID of transaction events and returns only
     *     transactions with events whose IDs are *smaller* than the specified value. This
     *     parameters supersedes the `newest_time` parameter (if both are provided in the request).
     * @return This ListTransactionsV21QueryParams instance.
     */
    public ListTransactionsV21QueryParams newestRef(String value) {
      this.values.put("newest_ref", Objects.requireNonNull(value, "newestRef"));
      return this;
    }

    /**
     * Sets the newest_time query parameter.
     *
     * @param value Filters the results by the creation time of resources and returns only
     *     transactions that are created *before* the specified timestamp (in
     *     [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).
     * @return This ListTransactionsV21QueryParams instance.
     */
    public ListTransactionsV21QueryParams newestTime(java.time.OffsetDateTime value) {
      this.values.put("newest_time", Objects.requireNonNull(value, "newestTime"));
      return this;
    }

    /**
     * Sets the oldest_ref query parameter.
     *
     * @param value Filters the results by the reference ID of transaction events and returns only
     *     transactions with events whose IDs are *greater* than the specified value. This
     *     parameters supersedes the `oldest_time` parameter (if both are provided in the request).
     * @return This ListTransactionsV21QueryParams instance.
     */
    public ListTransactionsV21QueryParams oldestRef(String value) {
      this.values.put("oldest_ref", Objects.requireNonNull(value, "oldestRef"));
      return this;
    }

    /**
     * Sets the oldest_time query parameter.
     *
     * @param value Filters the results by the creation time of resources and returns only
     *     transactions that are created *at or after* the specified timestamp (in
     *     [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).
     * @return This ListTransactionsV21QueryParams instance.
     */
    public ListTransactionsV21QueryParams oldestTime(java.time.OffsetDateTime value) {
      this.values.put("oldest_time", Objects.requireNonNull(value, "oldestTime"));
      return this;
    }

    /**
     * Sets the order query parameter.
     *
     * @param value Specifies the order in which the returned results are displayed.
     * @return This ListTransactionsV21QueryParams instance.
     */
    public ListTransactionsV21QueryParams order(com.sumup.sdk.models.Order value) {
      this.values.put("order", Objects.requireNonNull(value, "order"));
      return this;
    }

    /**
     * Sets the payment_types query parameter.
     *
     * @param value Filters the returned results by the specified list of payment types used for the
     *     transactions.
     * @return This ListTransactionsV21QueryParams instance.
     */
    public ListTransactionsV21QueryParams paymentTypes(
        java.util.List<com.sumup.sdk.models.PaymentType> value) {
      this.values.put("payment_types", Objects.requireNonNull(value, "paymentTypes"));
      return this;
    }

    /**
     * Sets the statuses query parameter.
     *
     * @param value Filters the returned results by the specified list of final statuses of the
     *     transactions.
     * @return This ListTransactionsV21QueryParams instance.
     */
    public ListTransactionsV21QueryParams statuses(
        java.util.List<com.sumup.sdk.models.StatusesItem> value) {
      this.values.put("statuses", Objects.requireNonNull(value, "statuses"));
      return this;
    }

    /**
     * Sets the transaction_code query parameter.
     *
     * @param value Retrieves the transaction resource with the specified transaction code.
     * @return This ListTransactionsV21QueryParams instance.
     */
    public ListTransactionsV21QueryParams transactionCode(String value) {
      this.values.put("transaction_code", Objects.requireNonNull(value, "transactionCode"));
      return this;
    }

    /**
     * Sets the types query parameter.
     *
     * @param value Filters the returned results by the specified list of transaction types.
     * @return This ListTransactionsV21QueryParams instance.
     */
    public ListTransactionsV21QueryParams types(
        java.util.List<com.sumup.sdk.models.TypesItem> value) {
      this.values.put("types", Objects.requireNonNull(value, "types"));
      return this;
    }

    /**
     * Sets the users query parameter.
     *
     * @param value Filters the returned results by user email.
     * @return This ListTransactionsV21QueryParams instance.
     */
    public ListTransactionsV21QueryParams users(java.util.List<String> value) {
      this.values.put("users", Objects.requireNonNull(value, "users"));
      return this;
    }

    /**
     * Converts query parameters to a map understood by ApiClient.
     *
     * @return Collected query parameters keyed by API name.
     */
    Map<String, Object> toMap() {
      return values;
    }
  }
}
