// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.events;

import com.sumup.sdk.core.ApiClient;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.CancellationException;

/**
 * Verifies and dispatches events to typed callbacks, using the fallback for unregistered types.
 * Register callbacks before serving requests; registering again replaces the previous callback.
 * Deliveries may repeat. Make processing idempotent using the event ID.
 */
public final class EventsHandler {
  private final ApiClient client;
  private final String secret;
  private final EventCallback<EventNotification> fallback;
  private final Map<String, EventCallback<EventNotification>> callbacks = new HashMap<>();

  /**
   * Creates a handler bound to an API client.
   *
   * @param client client used for resource fetches
   * @param secret endpoint signing secret, not an API key
   * @param fallback callback for unknown and unregistered event types
   */
  public EventsHandler(ApiClient client, String secret, EventCallback<EventNotification> fallback) {
    EventSignature.requireSecret(secret);
    this.client = Objects.requireNonNull(client);
    this.secret = secret;
    this.fallback = Objects.requireNonNull(fallback);
  }

  /**
   * Verifies and parses an event without invoking a callback.
   *
   * @param body original HTTP request bytes
   * @param signature complete signature header value
   * @return typed notification, or a base notification for an unknown event type
   * @throws EventSignatureException if signature verification fails
   * @throws EventPayloadException if the JSON cannot be deserialized
   */
  public EventNotification parse(byte[] body, String signature) {
    return EventNotification.parse(client, body, signature, secret);
  }

  /**
   * Registers the callback for {@code "members.created"}, replacing any previous registration.
   *
   * @param callback callback to complete before acknowledging delivery
   * @return this handler for chaining
   */
  public EventsHandler onMemberCreated(EventCallback<MemberCreatedEvent> callback) {
    Objects.requireNonNull(callback);
    callbacks.put(
        "members.created",
        event -> {
          callback.handle((MemberCreatedEvent) event);
        });
    return this;
  }

  /**
   * Registers the callback for {@code "members.deleted"}, replacing any previous registration.
   *
   * @param callback callback to complete before acknowledging delivery
   * @return this handler for chaining
   */
  public EventsHandler onMemberDeleted(EventCallback<MemberDeletedEvent> callback) {
    Objects.requireNonNull(callback);
    callbacks.put(
        "members.deleted",
        event -> {
          callback.handle((MemberDeletedEvent) event);
        });
    return this;
  }

  /**
   * Registers the callback for {@code "members.updated"}, replacing any previous registration.
   *
   * @param callback callback to complete before acknowledging delivery
   * @return this handler for chaining
   */
  public EventsHandler onMemberUpdated(EventCallback<MemberUpdatedEvent> callback) {
    Objects.requireNonNull(callback);
    callbacks.put(
        "members.updated",
        event -> {
          callback.handle((MemberUpdatedEvent) event);
        });
    return this;
  }

  /**
   * Registers the callback for {@code "readers.created"}, replacing any previous registration.
   *
   * @param callback callback to complete before acknowledging delivery
   * @return this handler for chaining
   */
  public EventsHandler onReaderCreated(EventCallback<ReaderCreatedEvent> callback) {
    Objects.requireNonNull(callback);
    callbacks.put(
        "readers.created",
        event -> {
          callback.handle((ReaderCreatedEvent) event);
        });
    return this;
  }

  /**
   * Registers the callback for {@code "readers.deleted"}, replacing any previous registration.
   *
   * @param callback callback to complete before acknowledging delivery
   * @return this handler for chaining
   */
  public EventsHandler onReaderDeleted(EventCallback<ReaderDeletedEvent> callback) {
    Objects.requireNonNull(callback);
    callbacks.put(
        "readers.deleted",
        event -> {
          callback.handle((ReaderDeletedEvent) event);
        });
    return this;
  }

  /**
   * Verifies, parses, and invokes the selected callback.
   *
   * @param body original HTTP request bytes; do not reserialize the JSON
   * @param signature complete signature header value
   * @throws EventSignatureException if signature verification fails
   * @throws EventPayloadException if deserialization fails
   * @throws EventCallbackException if the callback fails
   */
  public void handle(byte[] body, String signature) {
    var event = parse(body, signature);
    var callback = callbacks.getOrDefault(event.type(), fallback);
    try {
      callback.handle(event);
    } catch (CancellationException cause) {
      throw cause;
    } catch (Exception cause) {
      if (cause instanceof InterruptedException) Thread.currentThread().interrupt();
      throw new EventCallbackException("Event callback failed.", cause);
    }
  }
}
