// Code generated by sumup-java/codegen. DO NOT EDIT.
package com.sumup.sdk.events;

import com.fasterxml.jackson.core.type.TypeReference;
import com.sumup.sdk.models.Member;

/** Sent when a member is updated, disabled, rejected, or expires for a merchant account. */
public final class MemberUpdatedEvent extends FetchableEvent<Member> {
  @Override
  TypeReference<Member> resourceType() {
    return new TypeReference<>() {};
  }
}
