import org.gradle.language.jvm.tasks.ProcessResources

plugins {
    id 'java-library'
    id 'com.diffplug.spotless'
    id 'maven-publish'
    id 'signing'
    id 'cl.franciscosolis.sonatype-central-upload' version '1.0.3'
}

base {
    archivesName = 'sumup-sdk'
}

java {
    withSourcesJar()
    withJavadocJar()
}

sourceSets {
    def emptyDirs = []
    main {
        java.srcDirs = ['main/java']
        resources.srcDirs = ['main/resources']
    }
    test {
        java.srcDirs = ['test/java']
        resources.srcDirs = emptyDirs
    }
}

dependencies {
    api 'com.fasterxml.jackson.core:jackson-annotations:2.21'
    api 'com.fasterxml.jackson.core:jackson-core:2.21'
    api 'com.fasterxml.jackson.core:jackson-databind:2.21'
    api 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.21.0'

    testImplementation 'org.junit.jupiter:junit-jupiter:6.0.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('processResources', ProcessResources) {
    from(rootProject.file('VERSION')) {
        into('com/sumup/sdk')
        rename { 'sdk-version.txt' }
    }
}

tasks.withType(Javadoc).configureEach {
    options.addBooleanOption('Xdoclint:none', true)
    options.quiet()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = 'sumup-sdk'
            from components.java

            pom {
                name.set('SumUp Java SDK')
                description.set('Java SDK for the SumUp API.')
                url.set('https://github.com/sumup/sumup-java')

                licenses {
                    license {
                        name.set('Apache License, Version 2.0')
                        url.set('https://www.apache.org/licenses/LICENSE-2.0')
                    }
                }

                developers {
                    developer {
                        id.set('sumup')
                        name.set('SumUp')
                        email.set('opensource@sumup.com')
                        organization.set('SumUp')
                        organizationUrl.set('https://sumup.com')
                    }
                }

                scm {
                    url.set('https://github.com/sumup/sumup-java')
                    connection.set('scm:git:https://github.com/sumup/sumup-java.git')
                    developerConnection.set('scm:git:ssh://git@github.com/sumup/sumup-java.git')
                }
            }
        }
    }
}

sonatypeCentralUpload {
    username = System.getenv('SONATYPE_USERNAME')
    password = System.getenv('SONATYPE_PASSWORD')

    archives = files(
        "$buildDir/libs/sumup-sdk-${project.version}.jar",
        "$buildDir/libs/sumup-sdk-${project.version}-sources.jar",
        "$buildDir/libs/sumup-sdk-${project.version}-javadoc.jar"
    )

    pom = layout.buildDirectory.file("publications/mavenJava/pom-default.xml").get().asFile
    signingKey = System.getenv('SIGNING_KEY')
    signingKeyPassphrase = System.getenv('SIGNING_PASSWORD')
}

signing {
    def signingKey = System.getenv('SIGNING_KEY')
    def signingPassword = System.getenv('SIGNING_PASSWORD')
    if (signingKey && signingPassword) {
        useInMemoryPgpKeys(signingKey, signingPassword)
        sign(publishing.publications.mavenJava)
    }
}

tasks.named('sonatypeCentralUpload') {
    dependsOn(tasks.named('build'))
    dependsOn(tasks.named('generatePomFileForMavenJavaPublication'))
}
